### ISSUE TITLE
Installation issue MacOS

### ISSUE THREAD

**Issue by Nick-nale** [ViennaRNA/ViennaRNA#105]
Hello,

Actually I'm using MacOS. I'm trying to install the program to run locally. However I'm having an issue running it as it says there is a missing module.

Traceback (most recent call last):
File "", line 1, in 
ModuleNotFoundError: No module named 'RNA'

Do you know where this module is located? I've been trying to fix the issue but haven't be successful.

Thank you

**Comment by RaumZeit** [comment]
Did you install using the official MacOS X installer?
If so, please try setting the `PYTHONPATH` variable to point to the installation directory of the python interface, i.e.
```
PYTHONPATH=/usr/local/lib/python2.7/site-packages:${PYTHONPATH} python -c 'import RNA; print RNA.__version__'
```
should print the version of the installed `RNA` package.
If you installed into a different directory, adjust the above path accordingly. To make the changes permanent, simply add an
```
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:${PYTHONPATH}
```
to your `~/.bashrc` config file, as stated at the end of the MacOS X installer.
