### ISSUE TITLE
Issue installing and importing ViennaRNA in Python 3.8 using Conda

### ISSUE THREAD

**Issue by ayaanhossain** [ViennaRNA/ViennaRNA#110]
Hi, there seems to be a couple of problems related to installing and using the latest versions of ViennaRNA on conda environments using python=3.8 and possibly higher versions.

The first problem is by default when installing ViennRNA in a py3.8 environment, it seems to preferentially install ViennaRNA v2.3.3 which is rather old.

```
 🡲 conda install -c bioconda viennarna
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ayaan/miniconda3/envs/testvrna

  added / updated specs:
    - viennarna


The following NEW packages will be INSTALLED:

  viennarna          bioconda/linux-64::viennarna-2.3.3-hfc679d8_2


Proceed ([y]/n)? n


CondaSystemExit: Exiting.
```

This issue is nonexistent in environments with python 3.7 though (although it seems to still install upto 2.4.13 only ... which I guess is fine).

```
🡲 conda install -c bioconda viennarna
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ayaan/miniconda3/envs/testvrna

  added / updated specs:
    - viennarna


The following NEW packages will be INSTALLED:

  viennarna          bioconda/linux-64::viennarna-2.4.13-py37hdbcaa40_2


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

When trying to install ViennaRNA v2.4.17 forcibly, conda seems to preferentially install v2.4.7, and not higher, when Python is 3.8 (contrast this to v2.4.13 for py3.7, as shown above).

```
🡲 conda install -c bioconda/label/cf201901 viennarna
Collecting package metadata (current_repodata.json): done
Solving environment: / 
Warning: 3 possible package resolutions (only showing differing packages):
  - bioconda/label/cf201901/linux-64::viennarna-2.4.7-py27_2
  - bioconda/label/cf201901/linux-64::viennarna-2.4.7-py35_2
  - bioconda/label/cf201901/linux-64::viennarna-2.4.7-py36done

## Package Plan ##

  environment location: /home/ayaan/miniconda3/envs/testvrna

  added / updated specs:
    - viennarna


The following NEW packages will be INSTALLED:

  libgcc             pkgs/main/linux-64::libgcc-7.2.0-h69d50b8_2
  viennarna          bioconda/label/cf201901/linux-64::viennarna-2.4.7-py27_2


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

And no matter which version of ViennaRNA is installed in py3.8 environment, importing ViennaRNA does not seem to work.

```
🡲 python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import RNA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'RNA'
>>> quit()
```

Any insights as to how to fix this issue? Is this problem on my end or is this something specific to conda or the bioconda recipe?

**Comment by s-will** [comment]
Hi @ayaanhossain,
thanks for reporting this and already looking at the problem in good detail.

Indeed, there is a tricky problem related to how bioconda builds the viennarna package(s) from our recipe, which 'implicitly' pins viennarna package builds to specific python versions. I have an apparently analogous problem with installing ViennaRNA for Python 3.9 (but I cannot reproduce or explain everything that you observe.)

One can list the different package builds by ```conda search -c bioconda viennarna```, which reports four different builds for 2.4.17:
```
viennarna                     2.4.17  py27heb12742_0  bioconda            
viennarna                     2.4.17  py36hd181a71_0  bioconda            
viennarna                     2.4.17  py37h13b99d1_0  bioconda            
viennarna                     2.4.17  py38h8162308_0  bioconda            
```
That is, version 2.4.17 should work for the different Python versions 2.7, 3.6, 3.7, 3.8 - but according to the available package builds, it must fail for other Python version (than, conda will suggest to install other viennarna versions or report conflict, if we force 2.4.17)

In accordande to this, I manage to install viennarna for the four Python versions 2.7,3.6,3.7,3.8, but not for the newest version 3.9. For 3.9, conda suggests to install 2.3.3. I tested this with the following command:
```conda create -c bioconda -n viennarna-test 'python == x.y' viennarna```
(for different Python versions x.y).

For example,
```conda create -c bioconda -n viennarna-test 'python == 3.9' 'viennarna == 2.4.17'```
results in this conflict:
```Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                            

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python==3.9
viennarna==2.4.17 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0']
viennarna==2.4.17 -> python_abi=3.7[build=*_cp37m] -> python[version='2.7.*|3.7.*|3.6.*|3.8.*']
```

So, I observe in detail different behavior than you, but at least in part, we see the same phenomenon. The very chaotic evasion to much older versions happens very likely, because these packages have less strict constraints on the Python version. Additionally, there seems something wrong on your side. The last observation "importing ViennaRNA does not seem to work" is explicable, since here only the py27 package is installed (this means, RNAlib is not installed for Python 3.8 at all), but I don't know, why your conda  does not use the available py38 build.

Currently, at least for me, viennarna doesn't work with Python 3.9, which will be fixed with the next package build.

**Comment by ayaanhossain** [comment]
Thanks for looking into this.

My `conda search -c bioconda viennarna` output is same as yours.
```
...
viennarna                     2.4.15  py27heb12742_0  bioconda            
viennarna                     2.4.15  py36hd181a71_0  bioconda            
viennarna                     2.4.15  py37h13b99d1_0  bioconda            
viennarna                     2.4.15  py38h8162308_0  bioconda            
viennarna                     2.4.17  py27heb12742_0  bioconda            
viennarna                     2.4.17  py36hd181a71_0  bioconda            
viennarna                     2.4.17  py37h13b99d1_0  bioconda            
viennarna                     2.4.17  py38h8162308_0  bioconda 
```

I tried your testing command, and was thrown the following error for python 3.8.
```
 🡲 conda create -c bioconda -n viennarna-test 'python == 3.8' 'viennarna == 2.4.17'
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
viennarna==2.4.17 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0']
python==3.8
```

Installing v2.4.17 on py3.7 also seems problematic
```
 🡲 conda create -c bioconda -n viennarna-test 'python == 3.8' 'viennarna == 2.4.17'
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
viennarna==2.4.17 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0']
python==3.8
```
I am on conda 4.9.2 by the way.

The crux of the problem might be from:
`version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0'`.

Technically, this should be telling `conda` that py2.7 is good, py3.7 is good, py3.6 is good or py3.9 is good, but clearly, the way the version specification is made, it could also be telling conda the anything more than 3.7.0a0 is bad, anything more than 3.8.0a0 is bad etc.?  Clearly, how this statement is evaluated determines whether ViennaRNA v2.4.17 would be installed or not, and on my system, v2.4.17 cannot be installed in either 3.7 or 3.8.

I have no idea how to resolve this, other than perhaps rewriting the version statement more cleanly as:
`version='>=2.7,<2.8.0a0|>=3.7,<4.0.0a0'`

which should open up v2.4.17 for all version of python 3.7 and up, but less than 4.0? What do you think?

**Comment by ayaanhossain** [comment]
Might I also suggest, publishing ViennaRNA as a PyPI package/wheel? Then installing and using ViennaRNA for python usage is as simple as : `pip install viennarna`? Frankly, I just care about using RNAlib via python.

**Comment by rubyFeedback** [comment]
Adding it to PyPI would be quite useful, IMO. I use primarily ruby, but also python; I tend to batch-compile a new ViennaRNA release from source (using the download URL such as https://www.tbi.univie.ac.at/RNA/#download actually), but I also have a commandline variant to batch-install python-addons via some ruby scripts.

Perhaps some github actions could be used for automatically making available a package for PyPI as well? That could ease any manual maintenance burden perhaps. (I am not quite so familiar with the github actions, so perhaps I am totally wrong. But some python-heavy user may know perhaps; there are tons of C++ or C projects with python bindings out there.)

**Comment by ayaanhossain** [comment]
Problem solved! One can now `pip install ViennaRNA --upgrade` from shell. Once can also now specify ViennaRNA as a dependency for their projects using `install_requires` inside their `setup.py:setup`.
