### ISSUE TITLE
Warning message with '...from traverse_loop. Loop # has crossed regions'

### ISSUE THREAD

**Issue by andrewjjung47** [ViennaRNA/ViennaRNA#116]
Hi, I have a question regarding a warning message I've been getting from running `RNAfold`.

Sometimes I get a message like 
```
WARNING: ...from traverse_loop. Loop 3 has crossed regions
``` 

It seems like there is a similar message here http://rna.tbi.univie.ac.at//cgi-bin/RNAWebSuite/RNAfold.cgi?PAGE=3&ID=Dwpdujwe1W&r=49

I am having trouble understanding what this means and wondering if it is possible to get some help? 

Thank you in advance!

**Comment by RaumZeit** [comment]
This warning can, in most cases, simply be ignored. It stems from the RNA structure plotting layout algorithm which failed to draw the secondary structure in a non-crossing manner. You might want to use a different plot layout algorithm if the result is really ugly. For that purpose, please see the `-t` or `--layout-type` command line options of [RNAfold](https://www.tbi.univie.ac.at/RNA/RNAfold.1.html).

**Comment by andrewjjung47** [comment]
I see, thank you so much for your answer!
