### ISSUE TITLE
Unable to debug ViennaRNA functions (VS Code)

### ISSUE THREAD

**Issue by v-raja** [ViennaRNA/ViennaRNA#118]
I'm trying to debug some ViennaRNA code by trying to step into function included from `fold.h` (`vrna_fold` specifically). However, the VSCode debugger always steps over functions from ViennaRNA when I try to step into them.

I thought this might be due to not compiling with a `-g` flag, but I did so with `./configure CFLAGS=-g && make && sudo make install` and I still can't step into functions included from ViennaRNA.

Does anyone have any suggestions for how I can compile ViennaRNA / setup my debugging env to be able to step into functions included from ViennaRNA?

**Comment by RaumZeit** [comment]
This might be due to code optimization. Please try compiling the ViennaRNA Package with `-O 0` and without link time optimization, e.g.:

```
./configure CFLAGS="-O0 -g" --disable-lto
```
