### ISSUE TITLE
diffrent mfe value from python calulationa and webserver

### ISSUE THREAD

**Issue by Zahraalirezaei** [ViennaRNA/ViennaRNA#119]
Hi,
I am trying to find the mfe of series of sequence in python, but I noticed that the mfe values are different from webserver prediction. can You please help me with that.
-------------------------
seq = "AAATTTTCTCCGGAATATTGATTGAATGAA"

# create fold_compound data structure (required for all subsequently applied  algorithms)
fc = RNA.fold_compound(seq)

# compute MFE and MFE structure
(mfe_struct, mfe) = fc.mfe()

# print everything like RNAfold -p --MEA
print("%s\n%s (%6.2f)" % (seq, mfe_struct, mfe))
-------------------------

The webserver prediction is:
AAAUUUUCUCCGGAAUAUUGAUUGAAUGAA
.(((.(((....))).)))...........

Thanks.

**Comment by Shunsuke-1994** [comment]
Convert DNA to RNA
```
seq = "AAATTTTCTCCGGAATATTGATTGAATGAA").replace("T", "U") # DNA to RNA
fc = RNA.fold_compound(seq)
(mfe_struct, mfe) = fc.mfe()
print("%s\n%s (%6.2f)" % (seq, mfe_struct, mfe))
```

This outputs:
```
AAAUUUUCUCCGGAAUAUUGAUUGAAUGAA  
.(((.(((....))).)))........... ( -1.70)
```

**Comment by RaumZeit** [comment]
@Shunsuke-1994 is right here.

While the webserver uses our executable programs to compute everything, the Python interface provides low-level access to our implementations. The latter __always__ require RNA sequences in RNA alphabet (ACGU) and upper-case characters. The executable programs, on the other hand, will automagically convert the input accordingly before passing it to the implemented algorithms.
