### ISSUE TITLE
Explanation of `MAXALPHA `

### ISSUE THREAD

**Issue by vivkr** [ViennaRNA/ViennaRNA#122]

**Comment by vivkr** [comment]
(Apologies for abusing Issues for explanations. There is no Discussions tab for this repo yet.)

Can anyone explain why `MAXALPHA` is set to 20? It's documented with the comment `/* maximal length of alphabet */`, but I still don't understand why that means this constant is set to 20.

**Comment by RaumZeit** [comment]
There is no special reason for that. it simply has been that size forever.
