### ISSUE TITLE
Why are sequences made "circular" in func `vrna_seq_encode_simple`?

### ISSUE THREAD

**Issue by vivkr** [ViennaRNA/ViennaRNA#123]
In `vrna_seq_encode_simple` a sequence is encoded into it's numerical representation (A -> 1, C-> 2, G -> 3, T/U -> 4). The start of the encoded sequence (`S[0]`) is appended with the length of the sequence (on line 303).

Why is the last int in the array set to encoded value of the first letter of the sequence?
https://github.com/ViennaRNA/ViennaRNA/blob/d6fbaf2b33d65944f9249a91ed5ab4b3277f7d06/src/ViennaRNA/alphabet.c#L302

**Comment by RaumZeit** [comment]
To avoid conditions when adding dangling end contributions for circular RNAs, where the 1st base of the linearized sequence follows the last one.
