### ISSUE TITLE
Explanation of base pair types

### ISSUE THREAD

**Issue by vivkr** [ViennaRNA/ViennaRNA#124]
The struct `vrna_md_s` has a [field `pair`](https://github.com/ViennaRNA/ViennaRNA/blob/master/src/ViennaRNA/model.h) which is a 2D matrix (type `int`) which is documented with the brief "Integer representation of a base pair". 

Could anyone please explain what this integer representation is based on? Is there a paper or a known standard in the syn-bio community that agrees on these integers as base pair types? If not, where do these integers come from? I've searched the repo (and online for papers about this) but can't find any documentation about this.

The default values for the 2D matrix of base pair types are set [here](https://github.com/ViennaRNA/ViennaRNA/blob/d6fbaf2b33d65944f9249a91ed5ab4b3277f7d06/src/ViennaRNA/model.c#L128).

**Comment by RaumZeit** [comment]
No paper for that! This is simply our way to encode base pairs and it has to stay consistent with how energy parameters are stored.

**Comment by vivkr** [comment]
Thanks for all the info @RaumZeit. Could you please let me know why the matrix isn't symmetric?
From what I understand, this is the default `pair` matrix:
```
//       _  A  C  G  U  X  K  I
/* _ */ {0, 0, 0, 0, 0, 0, 0, 0},
/* A */ {0, 0, 0, 0, 5, 0, 0, 5},
/* C */ {0, 0, 0, 1, 0, 0, 0, 0},
/* G */ {0, 0, 2, 0, 3, 0, 0, 0},
/* U */ {0, 6, 0, 4, 0, 0, 0, 6},
/* X */ {0, 0, 0, 0, 0, 0, 2, 0},
/* K */ {0, 0, 0, 0, 0, 1, 0, 0},
/* I */ {0, 6, 0, 0, 5, 0, 0, 0},
```
Why isn't `pair[G][C]` (which is 2) equal to `pair[C][G]` (which is 1)? 

How are the values in the matrix computed? (i.e. Given two nucleotides `G` and `C`, how do we get the value 2?)

**Comment by vivkr** [comment]
After reading a bit more of the code, I now understand that the actual values of `pair[G][C] == 2` and `pair[C][G] == 1` were just arbitrary decisions and that the pair matrix helps us find the relevant energy values in the energy parameters in all the energy calculation functions.
