### ISSUE TITLE
Potential bug: Incorrect order of `p` and `q` when checking for base pair type in `stack_energy`

### ISSUE THREAD

**Issue by v-raja** [ViennaRNA/ViennaRNA#125]
In `stack_energy`, I came across this line where we check for the type of the base pair (p,q):
https://github.com/ViennaRNA/ViennaRNA/blob/d6fbaf2b33d65944f9249a91ed5ab4b3277f7d06/src/ViennaRNA/eval.c#L1047

Given that `p` is the nucleotide from the 5' end of the sequence, shouldn't the line be:
```
if (md->pair[s[p]][s[q]] == 0) {
```

In all other code where we check for the pair type, we access it with `pair[nucleotide at 5' end][nucleotide at 3' end]`.

**Comment by RaumZeit** [comment]
see my comment in https://github.com/ViennaRNA/ViennaRNA/issues/126
