### ISSUE TITLE
RNAsubopt sorting algorithm tiebreaks differently on Mac vs Linux

### ISSUE THREAD

**Issue by croots** [ViennaRNA/ViennaRNA#127]
Affects python 3.7, 3.8, and 3.9, ViennaRNA version 2.4.18.

**Behavior:**
While the output of RNAsubopt always reports the same folds, the order of folds within a given dG may differ depending on the platform that is used to run the analysis. This can result in some inconsistency problems for downstream users that may run automated solutions on either Mac on Linux.

For example, the following output appears for Mac users:

> echo "CTGACCATTACGGTGAGCGTTTAGCTCGCGAACAG&ACCUCCUUA" | RNAsubopt -e 5.481 -T 37.0 -d0 --sorted --en-only --noLP -P rna_turner2004.par
> CUGACCAUUACGGUGAGCGUUUAGCUCGCGAACAG&ACCUCCUUA  -8.40   5.48
> ............((((((.....))))))......&.........  -8.40
> (((.........((((((.....))))))...)))&.........  -7.90
> ..........((.(((((.....))))))).....&.........  -7.00
> (((....((.((.(((((.....))))))))))))&.........  -6.60
> (((....((...((((((.....)))))).)))))&.........  -6.40
> ..((........((((((.....))))))......&...))....  -6.20
> ............((((((.....))))))((....&...))....  -6.20
> .......((...((((((.....))))))....))&.........  -6.10
> .......((.((.(((((.....)))))))))...&.........  -6.00
> ............((((((.....))))))....((&..)).....  -5.90
> ............((((((.....))))))....((&.....))..  -5.90
> .......((...((((((.....)))))).))...&.........  -5.80
> (((.......((.(((((.....)))))))..)))&.........  -5.80
> ..........((..((((.....)))).)).....&.........  -5.80
> (((....((...((((((.....)))))))).)))&.........  -5.70
> .(((........((((((.....))))))......&......)))  -5.60
> .......((...((((((.....))))))))....&.........  -5.50
> .............(((((.....))))).......&.........  -5.40
> (((....((.((..((((.....)))).)))))))&.........  -5.40
> ...........(((((((.....))))........&)))......  -5.40
> .((.........((((((.....))))))...)).&.........  -5.30
> ...(((.....)))((((.....))))........&.........  -5.30
> ((..........((((((.....))))))....))&.........  -4.90
> ..((......((.(((((.....))))))).....&...))....  -4.80
> .......((.((..((((.....)))).))))...&.........  -4.80
> ...........(((((((.....))))).......&....))...  -4.60
> ........((..((((((.....))))))......&.......))  -4.60
> ..((........((((((.....))))))......&......)).  -4.60
> ............((((((.....))))))((....&......)).  -4.60
> ............((((((.....))))))((..((&..))..)).  -4.60
> ...........(((((((.....))))).......&.))......  -4.60
> (((.......((..((((.....)))).))..)))&.........  -4.60
> ..........((.(((((.....)))))))...((&.....))..  -4.50
> ....((.....))(((((.....))))).......&.........  -4.50
> ..............((((.....))))........&.........  -4.50
> ..........((.(((((.....)))))))...((&..)).....  -4.50
> .((.......))((((((.....))))))......&.........  -4.40
> .((.........((((((.....))))))......&.......))  -4.30
> .(((...)))..((((((.....))))))......&.........  -4.30
> .(((......((.(((((.....))))))).....&......)))  -4.20
> ........((.(((((((.....))))).......&....)).))  -4.20
> ............((((((.....)))))).((...&......)).  -4.20
> ((.(((.....))).))..................&.........  -4.10
> .......((.((.(((((.....)))))))...))&.........  -4.10
> (((.......)))(((((.....))))).......&.........  -4.00
> .((....((.((.(((((.....))))))))))).&.........  -4.00
> ..((...((...((((((.....))))))....))&...))....  -3.90
> ............((((((.....))))))....((&......)).  -3.90
> .((....((...((((((.....)))))).)))).&.........  -3.80
> ..((...((.((.(((((.....)))))))))...&...))....  -3.80
> ...........((.((((.....))))........&.))......  -3.70
> ...........((.((((.....))))........&....))...  -3.70
> .((.....))..((((((.....))))))......&.........  -3.70
> ....((.....)).((((.....))))........&.........  -3.60
> ..((...((...((((((.....)))))).))...&...))....  -3.60
> ............((..(((.......)))..))..&.........  -3.60
> ..((......((..((((.....)))).)).....&...))....  -3.60
> .......((.((.(((((.....))))))))).((&.....))..  -3.50
> ............(((((.......)))))......&.........  -3.50
> (((..........(((((.....)))))....)))&.........  -3.50
> .......((.((.(((((.....))))))))).((&..)).....  -3.50
> ............(((.((.....)).)))......&.........  -3.40
> ........((.((.((((.....))))........&....)).))  -3.30
> .(((...((...((((((.....))))))....))&......)))  -3.30
> .......((...((((((.....)))))).)).((&.....))..  -3.30
> ..........((..((((.....)))).))...((&.....))..  -3.30
> ..((...((...((((((.....))))))))....&...))....  -3.30
> .......((...((((((.....)))))).)).((&..)).....  -3.30
> ..........((..((((.....)))).))...((&..)).....  -3.30
> ..((...))...((((((.....))))))......&.........  -3.30
> .((.......((.(((((.....)))))))..)).&.........  -3.20
> .............(((((.....))))).((....&...))....  -3.20
> ..((.........(((((.....))))).......&...))....  -3.20
> ..((......((.(((((.....))))))).....&......)).  -3.20
> ........((((.(((((.....))))))).....&.......))  -3.20
> .(((...((.((.(((((.....)))))))))...&......)))  -3.20
> .((....((...((((((.....)))))))).)).&.........  -3.10
> (((.......))).((((.....))))........&.........  -3.10
> ............((((((.....)))))).((.((&..))..)).  -3.10
> ((.(((.....))).))(((.......))).....&.........  -3.10
> (((....((....(((((.....)))))..)))))&.........  -3.10
> ...(((.....)))((((.....))))..((....&...))....  -3.10
> .(((...((...((((((.....)))))).))...&......)))  -3.00
> (((.........(((((.......)))))...)))&.........  -3.00
> .......((...((((((.....))))))))..((&.....))..  -3.00
> .......((...((((((.....))))))))..((&..)).....  -3.00
> .(((......((..((((.....)))).)).....&......)))  -3.00

versus Linux users

> echo 'CTGACCATTACGGTGAGCGTTTAGCTCGCGAACAG&ACCUCCUUA' | RNAsubopt -e 5.481 -T 37.0 -d0 --sorted --en-only --noLP -P rna_turner2004.par
> CUGACCAUUACGGUGAGCGUUUAGCUCGCGAACAG&ACCUCCUUA  -8.40   5.48
> ............((((((.....))))))......&.........  -8.40
> (((.........((((((.....))))))...)))&.........  -7.90
> ..........((.(((((.....))))))).....&.........  -7.00
> (((....((.((.(((((.....))))))))))))&.........  -6.60
> (((....((...((((((.....)))))).)))))&.........  -6.40
> ..((........((((((.....))))))......&...))....  -6.20
> ............((((((.....))))))((....&...))....  -6.20
> .......((...((((((.....))))))....))&.........  -6.10
> .......((.((.(((((.....)))))))))...&.........  -6.00
> ............((((((.....))))))....((&.....))..  -5.90
> ............((((((.....))))))....((&..)).....  -5.90
> (((.......((.(((((.....)))))))..)))&.........  -5.80
> .......((...((((((.....)))))).))...&.........  -5.80
> ..........((..((((.....)))).)).....&.........  -5.80
> (((....((...((((((.....)))))))).)))&.........  -5.70
> .(((........((((((.....))))))......&......)))  -5.60
> .......((...((((((.....))))))))....&.........  -5.50
> ...........(((((((.....))))........&)))......  -5.40
> (((....((.((..((((.....)))).)))))))&.........  -5.40
> .............(((((.....))))).......&.........  -5.40
> .((.........((((((.....))))))...)).&.........  -5.30
> ...(((.....)))((((.....))))........&.........  -5.30
> ((..........((((((.....))))))....))&.........  -4.90
> ..((......((.(((((.....))))))).....&...))....  -4.80
> .......((.((..((((.....)))).))))...&.........  -4.80
> ........((..((((((.....))))))......&.......))  -4.60
> ..((........((((((.....))))))......&......)).  -4.60
> ............((((((.....))))))((....&......)).  -4.60
> ............((((((.....))))))((..((&..))..)).  -4.60
> ...........(((((((.....))))).......&....))...  -4.60
> ...........(((((((.....))))).......&.))......  -4.60
> (((.......((..((((.....)))).))..)))&.........  -4.60
> ..........((.(((((.....)))))))...((&.....))..  -4.50
> ..........((.(((((.....)))))))...((&..)).....  -4.50
> ....((.....))(((((.....))))).......&.........  -4.50
> ..............((((.....))))........&.........  -4.50
> .((.......))((((((.....))))))......&.........  -4.40
> .((.........((((((.....))))))......&.......))  -4.30
> .(((...)))..((((((.....))))))......&.........  -4.30
> .(((......((.(((((.....))))))).....&......)))  -4.20
> ........((.(((((((.....))))).......&....)).))  -4.20
> ............((((((.....)))))).((...&......)).  -4.20
> .......((.((.(((((.....)))))))...))&.........  -4.10
> ((.(((.....))).))..................&.........  -4.10
> .((....((.((.(((((.....))))))))))).&.........  -4.00
> (((.......)))(((((.....))))).......&.........  -4.00
> ............((((((.....))))))....((&......)).  -3.90
> ..((...((...((((((.....))))))....))&...))....  -3.90
> ..((...((.((.(((((.....)))))))))...&...))....  -3.80
> .((....((...((((((.....)))))).)))).&.........  -3.80
> ...........((.((((.....))))........&....))...  -3.70
> ...........((.((((.....))))........&.))......  -3.70
> .((.....))..((((((.....))))))......&.........  -3.70
> ..((...((...((((((.....)))))).))...&...))....  -3.60
> ..((......((..((((.....)))).)).....&...))....  -3.60
> ............((..(((.......)))..))..&.........  -3.60
> ....((.....)).((((.....))))........&.........  -3.60
> .......((.((.(((((.....))))))))).((&.....))..  -3.50
> .......((.((.(((((.....))))))))).((&..)).....  -3.50
> (((..........(((((.....)))))....)))&.........  -3.50
> ............(((((.......)))))......&.........  -3.50
> ............(((.((.....)).)))......&.........  -3.40
> .(((...((...((((((.....))))))....))&......)))  -3.30
> ........((.((.((((.....))))........&....)).))  -3.30
> .......((...((((((.....)))))).)).((&.....))..  -3.30
> ..........((..((((.....)))).))...((&.....))..  -3.30
> ..((...((...((((((.....))))))))....&...))....  -3.30
> .......((...((((((.....)))))).)).((&..)).....  -3.30
> ..........((..((((.....)))).))...((&..)).....  -3.30
> ..((...))...((((((.....))))))......&.........  -3.30
> .(((...((.((.(((((.....)))))))))...&......)))  -3.20
> ........((((.(((((.....))))))).....&.......))  -3.20
> ..((......((.(((((.....))))))).....&......)).  -3.20
> ..((.........(((((.....))))).......&...))....  -3.20
> .............(((((.....))))).((....&...))....  -3.20
> .((.......((.(((((.....)))))))..)).&.........  -3.20
> ............((((((.....)))))).((.((&..))..)).  -3.10
> ...(((.....)))((((.....))))..((....&...))....  -3.10
> (((....((....(((((.....)))))..)))))&.........  -3.10
> .((....((...((((((.....)))))))).)).&.........  -3.10
> ((.(((.....))).))(((.......))).....&.........  -3.10
> (((.......))).((((.....))))........&.........  -3.10
> .(((...((...((((((.....)))))).))...&......)))  -3.00
> .(((......((..((((.....)))).)).....&......)))  -3.00
> .......((...((((((.....))))))))..((&.....))..  -3.00
> .......((...((((((.....))))))))..((&..)).....  -3.00
> (((.........(((((.......)))))...)))&.........  -3.00

The resulting folds are the same, but are displayed in a different order.

**Expected Behavior:**

Outputs are consistently ordered across platforms (or machines. Only tested on 2 macs and 1 linux box)

**Comment by RaumZeit** [comment]
Hi,

since we use `quick sort` which is **not** stable, it is not unexpected that you receive different order in the output on different platforms. In fact, you provided the `--en--only` flag which reduces the sorting criterion to free energy. So I don't see any difficulties on our side here. The different implementations of `quick sort` on Mac and Linux are to blame, since I don't think that the order in which structures are produced by the subopt algorithm is different on different platforms.

To keep your output consistent, you should remove the `--en-only` flag and let `RNAsubopt` sort by lexicographic order as well.
