### ISSUE TITLE
API documentation for RNAup and RNAplex

### ISSUE THREAD

**Issue by ShaniCohen** [ViennaRNA/ViennaRNA#131]
I have installed your package and using it with Python (import RNA).
I would like to use the RNAup and RNAplex capabilities, but couldn't find any documentation for the API functions that are available (except to a few general examples provided [here](https://github.com/ViennaRNA/ViennaRNA/tree/master/examples/Python)).
For example, I would like to use RNAup to get the location and free energy, dG, for the optimal region of interaction between 2 RNA sequences. I would also like to get the accessibility measures for each sequence.

Will appreciate your help with providing the functions' names of RNAup and RNAplex.

**Comment by RaumZeit** [comment]
Unfortunately, there is no proper Python or Perl API for the implementation of `RNAup` and `RNAplex` available at the moment. Both programs have been implemented a long time ago and the respective authors did not take care of providing a useful library interface. Therefore, at the moment, the only way to use both tools from within `Python` is to do system calls and process the output the programs generate on stdout and some output files.
