### ISSUE TITLE
RNAup with python API

### ISSUE THREAD

**Issue by gregmcinnes** [ViennaRNA/ViennaRNA#134]
I'd like to run [RNAup](http://rna.tbi.univie.ac.at//cgi-bin/RNAWebSuite/RNAup.cgi) from within python but I haven't been able to find the equivalent function.

Is there a way to do this with the python package?

```
RNAup -b -d2 --noLP -c 'S' < sequences.fa > RNAup.out
```

**Comment by RaumZeit** [comment]
As of now, there is no Perl 5 or Python interface for `RNAup` available in the ViennaRNA Package.

See also https://github.com/ViennaRNA/ViennaRNA/issues/131
