### ISSUE TITLE
edge case base pair probabilities - wrong or floating point issue?

### ISSUE THREAD

**Issue by sjanssen2** [ViennaRNA/ViennaRNA#136]
This might be an extreme edge case, however I thought it might help reporting it. 

I am using Vienna 2.4.18 from https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_4_x/ViennaRNA-2.4.18.tar.gz program `RNAalifold`. 

My input **alignment** consists of only one row that contains gaps. Biologically, this doesn't make sense. I am using that to use a shared coordinate system:
```
CLUSTAL X (1.81) multiple sequence alignment


tail                                --------------------------------------------------

tail                                --------------------------------------------------

tail                                --------------------------------------------------

tail                                --------------------------------------------------

tail                                ----------------------------------------TGGCCACTAT

tail                                TTAAGCAAGTTACGGGCGCTCATTTATTCGTAAGTTAGAATATCTTGAGA

tail                                AGTAAGTAGCAAGACAAAGAATTCGCCTACTTGTTTGAAAATGCCTCACC

tail                                GTTTTCCGAATGTTGTATGTTTATTCAGAAACATCCAGACATAGTCCGGC

tail                                CCATCAGATGAGTGGCAAGACAAGCTCATCCGAAAAGAAAAACCCCGCGT

tail                                GACGAAA-TCGTCATTCGGGGTTTTTTGA-
```

the command I am using is `RNAalifold-2.4.18 --input-format=C -p --noPS input` where `input` is the filename of the above alignment.

The resulting `alidot.ps` file containes positive base pair probabilities for the part of the sequence that only consists of gaps?!
```
%start of base pair probability data
0.00 0.00 hsb 1 5 0.141118 ubox
0.00 0.00 hsb 1 6 0.105999 ubox
```
This doesn't make sense to me. Why should `-` on position 1 form a pair with `-` on position 6 ?

**Comment by RaumZeit** [comment]
I've had a closer look into this this behavior and found the following:
Two columns in an MSA are allowed to pair (thus will be included in base pairing probability computations), if there are not too many counter-examples among the sequences in the alignment.

However, the counter-example threshold condition is a little odd in such corner-cases of MSAs with just a single sequence. In fact, the current implementation checks, whether there are more than 50% of the sequences with non-canonical base pairs (`n_c`) and/or too many gap-gap combinations (`n_g`). In mathematical terms, the following inequality has to be fulfilled:
```
2 * n_c + n_g > n_seq
```
where `n_seq` is the number of sequences in the alignment.

For the upcoming release of v2.5.0, I've adapted this criterion to the following:
```
2 * n_c + n_g >= n_seq
```
which makes more sense and also requires that there is at least one canonical base pair possible among the sequences.

**Comment by sjanssen2** [comment]
Hi @RaumZeit, 

many thanks for digging into this!

I aim to stay in sync with my https://github.com/jlab/fold-grammars repository, i.e. want to apply the same change to my code. Thus, I want to be sure about your intended changes. Am I right that you are referring to these code lines: https://github.com/ViennaRNA/ViennaRNA/blob/5d0cf4fb5e794a9859c893fad2a7f34ac64cc403/src/ViennaRNA/utils/msa_utils.c#L281

**Comment by RaumZeit** [comment]
That's exactly it!

**Comment by sjanssen2** [comment]
perfect! Making the corresponding change in my code base leads to a lot of different results in my test suite: https://github.com/jlab/fold-grammars/runs/4094525266?check_suite_focus=true lines 2140ff
I figure you have your own tests, could you let me know if you also spot larger changes?!

**Comment by RaumZeit** [comment]
Yes,
there are quite some changes in the `RNAalifold` prediction output for our test cases, see this diff: [ba.txt](https://github.com/ViennaRNA/ViennaRNA/files/7472935/ba.txt)

However, to me, the changes in the output make total sense.

**Comment by RaumZeit** [comment]
Solved with https://github.com/ViennaRNA/ViennaRNA/commit/3aef803cfd5485663d45860693f4bab10af9eef4
