### ISSUE TITLE
Installation on Windows for Python3.8

### ISSUE THREAD

**Issue by chadroluna** [ViennaRNA/ViennaRNA#138]
Hi, 

I am trying to install ViennaRNA on Windows for Python3.8.
However, I am having some issues..
First, I tried 
pip install ViennaRNA 
from https://pypi.org/project/ViennaRNA/#description
However, a large error (below) appears.
Is pip install ViennaRNA no longer available?
.............................
 Using cached ViennaRNA-2.4.18a1.tar.gz (38.5 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ViennaRNA
  Building wheel for ViennaRNA (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\programdata\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LG\\AppData\\Local\\Temp\\pip-install-8ifwstuu\\viennarna_9aa4521eeb194922b3c66b2ab68462b7\\setup.py'"'"'; __file__='"'"'C:\\Users\\LG\\AppData\\Local\\Temp\\pip-install-8ifwstuu\\viennarna_9aa4521eeb194922b3c66b2ab68462b7\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\LG\AppData\Local\Temp\pip-wheel-2wggwpbi'
       cwd: C:\Users\LG\AppData\Local\Temp\pip-install-8ifwstuu\viennarna_9aa4521eeb194922b3c66b2ab68462b7\
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\ViennaRNA
  copying ViennaRNA\__init__.py -> build\lib\ViennaRNA
  installing to build\bdist.win-amd64\wheel
  running install
.
.
.
.
.........................................................

Second, I tried 
conda install -c bioconda viennarna
However, PackagesNotFoundError appears. (below)
Any help would be truly appreciated.
I am really excited to use viennaRNA.
Thanks!

------------------------------
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - viennarna

Current channels:

  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
----------------------------------------------------

**Comment by ayaanhossain** [comment]
Hi @chadroluna, ViennaRNA can be installed only in a Linux or MacOS environment. I maintain the PyPI version, and yes, the `conda` version has been broken for sometime. If you must install ViennaRNA on Windows, you should install Windows Subsystem for Linux (WSL), and then install ViennaRNA via `pip install ViennaRNA` using that. If your WSL is brand new, you might need to install `GCC Compiler`. See the following link for details.

Link: https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/#installing-gcc-on-ubuntu

**Comment by chadroluna** [comment]
Thank you for your help!
I installed ViennaRNA on Ubuntu and it works perfectly.

**Comment by rubyFeedback** [comment]
WSL in generally works really well. I much prefer linux as-is (and I just compile viennarna into /usr/ prefix which works fine) but WSL really works very well IMO (both WSL1 and WSL2).
