### ISSUE TITLE
[Mini-"typo" in RNAlib2.pc] should perhaps use https than http in the .pc file as such

### ISSUE THREAD

**Issue by rubyFeedback** [ViennaRNA/ViennaRNA#139]
Sorry for using german past this line but this is such a tiny "typo", not even sure I should report it.

---

Sers Ronny,

In der Datei pkgconfig/RNAlib2.pc steht:

URL: http://www.tbi.univie.ac.at/RNA

Verwendet man im browser diese URL so wird man automatisch umgeleitet auf:

https://www.tbi.univie.ac.at/RNA/

Eventuell sollte die .pc Datei auch https verwenden statt dem http Eintrag; vermutlich
reicht es wenn die Datei "configure.ac" adaptiert wird i. e.:

    AC_INIT([ViennaRNA],[vrna_version_major.vrna_version_minor.vrna_version_patch],
    [rna@tbi.univie.ac.at],[ViennaRNA],[http://www.tbi.univie.ac.at/RNA])
                                       # ^^^ zu https

Ist so oder so kein echtes Problem aber zumindest einfach zu ändern - hoffe dieser mini-report ist ok!

**Comment by RaumZeit** [comment]
Thank you for this comment!
It has been fixed for next release.
