### ISSUE TITLE
RNAfold .ps output with --circ option

### ISSUE THREAD

**Issue by Cdk29** [ViennaRNA/ViennaRNA#14]
Good morning. 

I observed that when I run RNAfold with the --circ option I get a different calculation of the free energy structure (see examples below), but the .ps output have the same aspect in both case, with no circularity. Is it the normal behavior or there is some trouble here ?
 
$ RNAfold --circ output_for_vienna.txt 
>0
UUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUUCAGAUAAAUAAGCUAUUUUUUUUUAUUUUUUCAGAUAAAUAAGCUAUUUUUUUUUAUUUUUUCAGAUAAAUAAGCUA
.................((((((.((((..((((.............))))....))))................((((((.........................)))))).....((((................((((((.........................)))))).....)))).........(((((((....)))))))..((((((((.(((..(....)..))).)))).)))).......(((((((....))))))))))))). ( -9.30)

$ RNAfold output_for_vienna.txt 
>0
UUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUCGAGUUUAGUGCAAUAUUUUUUUUUAUUUUUUCAGAUAAAUAAGCUAUUUUUUUUUAUUUUUUCAGAUAAAUAAGCUAUUUUUUUUUAUUUUUUCAGAUAAAUAAGCUA
.................((((((.((((..((((.............))))....))))................((((((.........................)))))).....((((................((((((.........................)))))).....)))).........(((((((....)))))))..((((((((.(((..(....)..))).)))).)))).......(((((((....))))))))))))). (-16.50)

I am using the version 2.4.1 of VienneRNA

**Comment by RaumZeit** [comment]
This is so far the correct behavior. The layout drawing algorithm does not care whether the RNA is circular or linear. However, I agree that it would be nice just having an extra backbone edge between 5' and 3' end in case this is a circular RNA. I'll see what I can do about it...
