### ISSUE TITLE
Install errors at clang -V and -qversion and c-version

### ISSUE THREAD

**Issue by yyw-informatics** [ViennaRNA/ViennaRNA#142]
Hi, 
Thanks for making this package! I followed the installation instructions - especially the notes to Mac users. However, I still can't run the configure file successfully. Please see the config.log file attached.

Also I notice that, in the config.log file, there were a few errors associated with the clang version checks, please see below. These seem to be variations of the "version" options/argument, for example, -V, -qversion, and c-version don't seem to work. I wonder if these are the problems and how should I fix them. 

configure:3961: clang --version >&5
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Users/yuanyuanwang/opt/anaconda3/bin
configure:3972: $? = 0
configure:3961: clang -v >&5
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Users/yuanyuanwang/opt/anaconda3/bin
configure:3972: $? = 0
**configure:3961: clang -V >&5
clang-4.0: error: argument to '-V' is missing (expected 1 value)
clang-4.0: error: no input files**
configure:3972: $? = 1
**configure:3961: clang -qversion >&5
clang-4.0: error: unknown argument: '-qversion'
clang-4.0: error: no input files**
configure:3972: $? = 1
**configure:3961: clang -version >&5
clang-4.0: error: unknown argument: '-version'
clang-4.0: error: no input files**

Thank you,
Yuanyuan
[config.log](https://github.com/ViennaRNA/ViennaRNA/files/7929173/config.log)

**Comment by RaumZeit** [comment]
How did you run the `./configure` script, i.e. which environment variables have been set?
The error messages you were referring are not necessarily the problem here. The configure script errors out with error 77, which usually indicates that the compiler could not create executables. Can you verify that you are running the script within a directory that is writable and where programs can be executed from?

**Comment by yyw-informatics** [comment]
> How did you run the `./configure` script, i.e. which environment variables have been set?
> The error messages you were referring are not necessarily the problem here. The configure script errors out with error 77, which usually indicates that the compiler could not create executables. Can you verify that you are running the script within a directory that is writable and where programs can be executed from?

Hi thanks for replying, my issues was solved with conda install. Cheers!
