### ISSUE TITLE
Salt concentration effect on folding

### ISSUE THREAD

**Issue by meehanca** [ViennaRNA/ViennaRNA#144]
Hello, 

Really enjoying using the software so far, I just want to know whether there are options in RNAfold to tune how salt concentrations effect hybridisation or any way to more specifically tune the program to a particular solution space similar to the UNAfold web server?

Thanks,
Cathal

**Comment by RaumZeit** [comment]
At the moment, salt concentration dependence can not be changed from the default 1M NaCl. The feature is on our wihslist, though and might be added in the future.

**Comment by nh13** [comment]
@RaumZeit can you point me to where the default salt concentration is set?  I'd want to understand what it would take for us to contribute a feature for adding this, and if you'd be open to that.
