### ISSUE TITLE
Perl5 Interface:    Not to be installed

### ISSUE THREAD

**Issue by manishbiotechie** [ViennaRNA/ViennaRNA#15]
Hi I am installing Vienna RNA 2.4.2 package on ubuntu 16.04 but I am getting a trouble as 
Perl5 Interface:    Not to be installed

I want Perl5 interface to be installed. I am new to this kindly help

**Comment by RaumZeit** [comment]
To successfully compile and install the scripting language interfaces, the corresponding development files are required to be installed. For perl and Ubuntu, this should be the `libperl-dev` package.
Please try instalingl said package and `./configure` the ViennaRNA Package again.
