### ISSUE TITLE
rna_profile_alignment.cpp:933:64: error:  MacOS installation error

### ISSUE THREAD

**Issue by adumita** [ViennaRNA/ViennaRNA#151]
Hi, I've had and used ViennaRNA on my mac successfully before. After I updated the system to Monterey version, I had to reinstall the package but this time I get this error:

rna_profile_alignment.cpp:933:64: error: use of undeclared identifier
      'VRNA_PLOT_TYPE_DEFAULT'
    i = vrna_plot_coords_pt((const short *)pair_table, &X, &Y, VRNA_PL...
                                                               ^
1 error generated.
make[5]: *** [rna_profile_alignment.o] Error 1
make[4]: *** [all] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Any help and/or tips how to work around it?

**Comment by mwittep** [comment]
Any update on this? Same error on Monterey 12.3.

**Comment by RaumZeit** [comment]
Hi,
this must be a wrong header that is included during the build process. The file `src/RNAforester/src/rna_profile_alignment.cpp` includes `ViennaRNA/plotting/layouts.h` which in turn defines the identifier that is seemingly missing at line 92 or 94.

If the compiler complains about this identifier missing here, then somehow the `RNAforester` build process includes the wrong header, maybe a remnant of a previous installation. Uninstalling the old version might help here. But I'll have a look at how to adapt the `RNAforester` build process to include the latest headers first.
