### ISSUE TITLE
Conda installation of ViennaRNA in linux is finding conflicts.

### ISSUE THREAD

**Issue by shafat010** [ViennaRNA/ViennaRNA#153]
Update : I later found out that it actually is a conda problem as the solving environment problem applied to other packages as well. I reinstalled conda and now it's working.

Hi, 

So a couple months ago I tried to install the ViennaRNA package in a older version of anaconda and it failed. I didn't know what was wrong, then I had a hunch and reinstalled the latest anaconda and it worked. Today, although my anaconda is the latest version, my installation is finding conflicts and examining conflicts for several hours. I ran `conda install -c bioconda viennarna`, and my conda channels are updated. After a few hours, it's still examining conflicts:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for matplotlib-base intake nltk astroid pylint dask jupyter/ 

```

**Comment by RaumZeit** [comment]
> Update : I later found out that it actually is a conda problem as the solving environment problem applied to other packages as well. I reinstalled conda and now it's working.
Good to know! Sometimes, `conda` is very picky about the order of channels, so simply reordering the channels might already help...
