### ISSUE TITLE
How to use constraints_add method 

### ISSUE THREAD

**Issue by mehrankr** [ViennaRNA/ViennaRNA#155]
Hello,

Thank you for maintaining this useful package,
I was able to use the contraint option through the commandline, but not the Python API.
Here (https://github.com/ViennaRNA/ViennaRNA/blob/master/tests/python/test-RNA-constraints.py) there is an example showing a file "hc.txt" should contain the constraint option, but I tail to use it.
If you could provide a link to how "hc.txt" should look like, it would be very useful.

For exampe, in the command line option, I generate a fasta file:

```
>seq1
GCCCGAUAUAUAUAUCGCGCGCGAUAUAUAUCACCU
....xx.........x..............x.....
>seq1_2
GCCCGAUAUAUAUAUCGCGCGCGAUAUAUAUCACCU
....................................
```

And run `RNAfold -C <pathToFasta.fa>` and get:

```
>seq1
GCCCGAUAUAUAUAUCGCGCGCGAUAUAUAUCACCU
........(((((((........)))))))...... ( -2.00)
>seq1_2
GCCCGAUAUAUAUAUCGCGCGCGAUAUAUAUCACCU
.......((((((((((....))))))))))..... ( -8.60)
```

But in the python version, when I have a file containing the constraint, I get:

```
fc = RNA.fold_compound(seq)
hc_file = "temp.txt"
fc.constraints_add(hc_file)
WARNING: Ignoring unknown command in file "temp.txt":
line 1: ....xx.........x..............x.....
```

**Comment by RaumZeit** [comment]
Hi,
(hard) constraints can be supplied either using pseudo-dot-bracket strings or via constraint/command files. The former is what you provide in your example where some of the nucleotides are supposed to stay unpaired. However, the correct function/method to apply these constraints is to use the
```
constraint_string = "....xx.........x..............x....."
fc.hc_add_from_db(constraint_string)
```
or
```
fc.hc_add(constraints_string, RNA.CONSTRAINT_DB_DEFAULT)
```
methods.  For that, you need to read the constraint from your input file and pass the dot-bracket string to the method `hc_add_from_db()` (see also https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/group__hard__constraints.html#ga5b4de3247b67358080c176b94591a8e6 and https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/group__constraints.html#ga35a401f680969a556858a8dd5f1d07cc).
For the constraint (or better command) files, you need to use a different syntax. See here for details: https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/file_formats.html#constraint-formats-file

In your example for `seq1`, the command file `temp.txt` would probably look like:
```
P 5 0 2
P 16 0 1
P 31 0 1
```
To prohibit nucleotides 5, 6, 16 and 31 to pair.

Alternatively, you can use the `hc_add*()` methods of the `fc` object directly, e.g.:
```
for nt in [5, 6, 16, 31]:
    fc.hc_add_up(nt)
```
will also constrain the nucletodides 5, 6, 16 and 31 to stay unpaired.
