### ISSUE TITLE
Incongruency between CLI and SWIG API Output

### ISSUE THREAD

**Issue by croots** [ViennaRNA/ViennaRNA#159]
Hi,

I'm trying to speed up my code in barricklab/ostir to make high throughput analysis more manageable, and the bottleneck in my code is waiting to spawn subprocesses and for ViennaRNA to spit results back out. The original implementation of the RBS calculator used this spawn-import process rather than through a native API, so I'm hoping to eliminate some overhead by switching to the API.

The issue I am facing is that in rare cases ViennaRNA appears to output two different MFEs for the same input sequences with default paramaters or with any of the parameters I am manually setting (dangles, temperature, paramater file, noLP, and PS). Either this is a difference in the way things are calculated between the two versions, or the API and CLI versions have different default parameters. This is complicated by the incomplete documentation of the API's defaults.

Attached is a replication of the issue. This appears in 2.4.18 (which is what my software uses) and 2.5.1 (the latest bioconda distribution). I am on Kubuntu and python 3.9.13.

Code credit: The implementation of the sub process handler was mostly adapted from the Salis lab's RBS Calculator 1.0, distributed under GPL3

Does anybody have any tips for resolution?

[vienna_issue.txt](https://github.com/ViennaRNA/ViennaRNA/files/9305072/vienna_issue.txt) (Run as a python script)

**Comment by croots** [comment]
An additional incongruity: `RNA.fold_compound.subopt` requires an integer input for the parameter `delta`. The command line doesn't seem picky about what type of numeric value is given to `--deltaEnergy`.

**Comment by RaumZeit** [comment]
So I finally found some time to look into your issue.
In fact, the problem you are facing here is that the command line programs automatically handle input sequence preparations, like converting the DNA alphabet `T` to its RNA counterpart `U`, as well as converting all input sequence letters to `uppercase`.
This is **not** done by the API functions, so you need to do that yourself, e.g. by adding a line like:
```
seq = seq.replace("T", "U")
```
Predictions using the `swig` interface should then be identical to those obtained from the command line tools.

Regarding your second post, this (again) is a convenience feature of the command line programs. the API functions are strict on their input types as the background library is written in `C`. So you must always follow the API reference manual and provide the correct input type.

I hope these answers are of help for your tasks!
Best,
Ronny
