### ISSUE TITLE
RNAplfold output problem

### ISSUE THREAD

**Issue by sfsdfd62** [ViennaRNA/ViennaRNA#160]
Hi,

The output format of RNAplfold is in a ps format. I want to get the probabilities in a txt format 
for example :
0.7,0.4,0.8...
What can I do to solve this? Please help! I offer my sincere thank you.

**Comment by RaumZeit** [comment]
The postscript output file, in fact, also is just a text file (with postscript code). The actual base pairing probabilities are stored within this file as lines that look like:
```
i j p ubox
```
where `i` and `j` are the nucleotide positions that pair and `p` is the square-root of the base pairing probability. So you could parse these files and extract the relevant pairing probabilities.

Alternativelty, `RNAplfold` also provides the `-o/--print_onthefly` parameter option. This option flag tells `RNAplfold` to not create the postscript file but to create a regular text file with 3 columns where the first two specify the nucleotide positions that pair and the third is the pairing probability. I believe this is the option you might have been looking for.
