### ISSUE TITLE
Unexpected large magnitude discriminant

### ISSUE THREAD

**Issue by VandaLovejoy** [ViennaRNA/ViennaRNA#163]
Hi! I'm getting this error message when using this command `RNAalifold --noLP --ribosum_scoring test.txt`

ERROR: Unexpected large magnitude discriminant = -1.08759 0.489399

[test.txt](https://github.com/ViennaRNA/ViennaRNA/files/9700354/test.txt)

**Comment by RaumZeit** [comment]
This is an error message of the RNA secondary structure layout algorithm that tries to create the plot (alirna.ps). For some reason the layout algorithm is failing on your input alignment and the corresponding predicted structure. Unfortunately, there is nothing that can be done at this point to make the naview algorithm plot the predicted structure.
But you can try using another layout algorithm, e.g. RNApuzzler (`-t 4`) , RNAturtle (`-t 3`) or even a much simpler, such as a circular plot (`-t 2`).
