### ISSUE TITLE
RNAfold: Setting jobs with `-j` does not impact on the number of threads being ran

### ISSUE THREAD

**Issue by jakeb1996** [ViennaRNA/ViennaRNA#164]
Hi there,

I compiled the package from source v2.5.1 (config log is attached). When I run RNAfold using the command `RNAfold -j16 <input-file>`, the program does not seem to run in multithreaded mode. I am checking htop and watching the load that each CPU core is under. I only see one core being used. This is on an AWS EC2 aarch64 virtual machine.

[config.log](https://github.com/ViennaRNA/ViennaRNA/files/9782831/config.log)

Could you please help me with compiling/running RNAfold in multithreaded mode on an aarch64 machine?

Kind regards,

[config.log](https://github.com/ViennaRNA/ViennaRNA/files/9782831/config.log)

**Comment by RaumZeit** [comment]
`RNAfold` and the other programs are using a mutlithread-queue to process multi-FASTA input files in parallel. The prediction algorithm itself does not scale well with parallelization and therefore is **not multithreaded**.
So, using the `-j16` option only makes sense if there are at least 16 sequences in the input. Note, that you can either have multi-FASTA input files or you run `RNAfold -j16 file1.fa file2.fa ... file16.fa`.
I hope this is of help.

Please let me know if `RNAfold` still doesn't result in high load even if there are multiple sequences in the input.

**Comment by jakeb1996** [comment]
Hi @RaumZeit ,
Thank for your quick response.
Sorry, I should have clarified my input.

I indeed provide a multifasta file:
```
GCTCTTTAGTTTCTTTTTGGGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGCUUUU
GTGCCTCCCAGCTAGGTAGGGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGCUUUU
GGAGGCTAATTATAAGAGGGGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGCUUUU
GGGCCTGGGTTGTAACCACAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGCUUUU
GTCTCAACTTCTGAGGATGGGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGCUUUU
...
<10,000 lines total>
```

Using this input on a x86 architecture machine, RNAfold will process using `-j` CPU cores. However, when I try on aarch64 it does not. 

Any help is greatly appreciated.

Cheers

**Comment by RaumZeit** [comment]
That's strange! Unfortunately, I don't have access to an aarch64 machine to reproduce this issue. Are there any additional errors printed when RNAfold is running?
Actually, the thread-pool implementation should be architecture independent, since it simply uses `pthreads`. From the config.log you posted it seems that everything went fine during the set-up phase. There might still be some compilation/linker issues, who knows. Did you use the `-j` flag or did you also specify the number of cores to use? 
Also, I looked up again, how the `-j` option is processed internally, and it might be that this is the actual root cause of the issue.
`RNAfold` queries `sysconf(_SC_CHILD_MAX)` which is supposed to return the maximum number of child processes per user. This might return an error or just `1` such that in turn `RNAfold` only starts a single thread,

Could you please compile and run the following C code on your aarch64 machine and post its output? (Github didn't allow me to upload C code so I had to rename it to .txt...)

[test_sysconf.txt](https://github.com/ViennaRNA/ViennaRNA/files/9803098/test_sysconf.txt)

```
mv test_sysconf.txt test_sysconf.c
gcc -o test test_sysconf.c
./test
```

This will essentially run the same queries for the maximum number of cores that `RNAfold` and the other tools do.

**Comment by jakeb1996** [comment]
Hi @RaumZeit ,

Thanks again for your quick response.

No errors are reported when RNAfold is running.

I used the `-j` flag. How would I specify the number of cores to use? I assumed that `-j` was specifying the number of cores (aka jobs).

Thanks for providing the C code.  This is what it returns:

```
max_user_threads = -1
proc_cores = 16
proc_cores_conf = 16
```

From the [manual pages](https://man7.org/linux/man-pages/man3/sysconf.3.html#RETURN_VALUE), it seems that `_SC_CHILD_MAX` is not supported. I walked through checking each return condition:

> *  On error, -1 is returned and errno is set to indicate the
>    error (for example, EINVAL, indicating that name is invalid).

I added some code to check `errno`:

```{c}
int
main(int  argc,
     char *argv[])
{
  int proc_cores, proc_cores_conf;
  (void)num_proc_cores(&proc_cores, &proc_cores_conf);
  
  printf("errno: %s\n", strerror(errno));
  errno = 0;
  printf("errno: %s\n", strerror(errno));
  int mut;
  mut  = max_user_threads();
  printf("errno: %s\n", strerror(errno));

  printf("max_user_threads = %d\nproc_cores = %d\nproc_cores_conf = %d\n", mut, proc_cores, proc_cores_conf);
  
}
````

```
errno: Success
errno: Success
errno: Success
max_user_threads = -1
proc_cores = 16
proc_cores_conf = 16
```

`errno` is not changing. I think `_SC_CHILD_MAX` is indeterminate.

> *  If name corresponds to a maximum or minimum limit, and that
>    limit is indeterminate, -1 is returned and errno is not
>    changed.  (To distinguish an indeterminate limit from an
>    error, set errno to zero before the call, and then check
>    whether errno is nonzero when -1 is returned.)

Just for interest sake, the other return values are:

> *  If name corresponds to an option, a positive value is returned
>    if the option is supported, and -1 is returned if the option
>    is not supported.
>
> *  Otherwise, the current value of the option or limit is
>    returned.  This value will not be more restrictive than the
>    corresponding value that was described to the application in
>    <unistd.h> or <limits.h> when the application was compiled.

Any ideas where to go from here?

Cheers

**Comment by RaumZeit** [comment]
I implemented a work-around for this case now and limit the maximum number of threads to the number of configured cores in cases where `sysconf` returns any error. You could try applying the patch attached from within the ViennaRNA source code directory:
```
patch -p1 -i threads.txt
```

Let me know if this solves your problem...
[threads.txt](https://github.com/ViennaRNA/ViennaRNA/files/9808334/threads.txt)

**Comment by jakeb1996** [comment]
Thanks for your support, @RaumZeit .

I've used a similar approach to your patch. Thanks for the inspiration.
