### ISSUE TITLE
Possible Constraints Bug in v2.5.1

### ISSUE THREAD

**Issue by domonik** [ViennaRNA/ViennaRNA#167]
Whilst testing nonspecific constraints i figured out that in v2.5.1 `fc.hc_add_bp_nonspecific` of the PythonAPI has no effect at all. 
I did not do further testing but from the first impression this might be also the case for the Comman Line Interface.

I used the following code for testing the python API

``` python
import RNA
import random


def fold_constr(seq, cons: bool, pos: int):
    fc = RNA.fold_compound(seq)
    if cons:
        fc.hc_add_bp_nonspecific(pos+1, 0)
    ss, mfe = fc.mfe()
    if ss[pos] == ".":
        return False
    else:
        return True


def run_test(num_tests):
    paired_resulst = {
        True: 0,
        False: 0
    }
    paired_nocons = {
        True: 0,
        False: 0
    }
    for _ in range(num_tests):
        seq_len = random.randint(20, 300)
        seq = "".join(random.choices(["A", "U", "G", "C"], k=seq_len))
        pos = random.randrange(0, len(seq))
        paired_w_const = fold_constr(seq, cons=True, pos=pos)
        paired_wo_const = fold_constr(seq, cons=False, pos=pos)
        paired_resulst[paired_w_const] += 1
        paired_nocons[paired_wo_const] += 1
    print("constraint", paired_resulst)
    print("no constraint", paired_nocons)


if __name__ == '__main__':
    random.seed(42)
    run_test(1000)

```

It produces the following result:

```
constraint {True: 523, False: 477}
no constraint {True: 523, False: 477}
```

Here `True` specifies whether the base that is supposed to be paired with any other base was actually paired. 

In contrast using version 2.4.13:

```
constraint {True: 999, False: 1}
no constraint {True: 523, False: 477}
```
Also i am still wondering why there is one False in the 2.4.13 but it might be by chance a sequence without possible basepairs

**Comment by RaumZeit** [comment]
I think you are just missing a `RNA.CONSTRAINT_DB_ENFORCE_BP` option in the `fc.hc_add_bp_nonspecific()` call...
Can you please check that, i.e.?
```
fc.hc_add_bp_nonspecific(pos+1, 0, RNA.CONSTRAINT_DB_ENFORCE_BP)
```

**Comment by domonik** [comment]
Adding this for me results in:
```
constraint {True: 0, False: 1000}
no constraint {True: 523, False: 477}
```

Which is the opposite of the expected behavior if I get it correctly.

**Comment by RaumZeit** [comment]
It has been a while since you posted this issue, but I believe I found the mistake that was built-in your example. So my previous reply of using the `RNA.CONSTRAINT_DB_ENFORCE_BP` flag was wrong. This is only meant to be provided to the `constraints_add()` method. In you case, you require the `RNA.CONSTRAINT_CONTEXT_ENFORCE` flag, in conjunction with the `RNA.CONSTRAINT_CONTEXT_ALL_LOOPS` flag to indicate that the base may pair in all distinguished contexts.
So the actual code block should be something like:
```python
def fold_constr(seq, cons: bool, pos: int):
    fc = RNA.fold_compound(seq)
    if cons:
        fc.hc_add_bp_nonspecific(pos+1, 0, RNA.CONSTRAINT_CONTEXT_ENFORCE | RNA.CONSTRAINT_CONTEXT_ALL_LOOPS)
    ss, mfe = fc.mfe()
    print(seq, "\n", ss, mfe)
    print(ss[pos])
    if ss[pos] == ".":
        return False
    else:
        return True
```

**Comment by RaumZeit** [comment]
I believe this issue is fixed now, so I'm closing it...
Please feel free to re-open if any questions remain
