### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by eumhh** [ViennaRNA/ViennaRNA#170]
Hi,
I'm trying to install the _ViennaRNA package_ to run _forna_ in locally.

**### First,** I tried to install using source code by following commands, but it failed.
```
conda create -n viennaRNA
conda activate viennaRNA
pip install --upgrade forgi[all]
cd ViennaRNA-2.5.1
./configure --with-python
```
Configuration returned followings:
```
Successfully configured with the following options:

Sub Packages
------------
  * Kinfold                   : yes
  * RNAforester               : yes
  * Analyse{Dists,Seqs}       : no
  * RNAlocmin                 : yes
  * Kinwalker                 : no

Extra Libraries
---------------
  * Support Vector Machine    : yes
  * GNU Scientific Library    : no
  * GNU MPFR                  : no
  * JSON                      : yes

Features
--------
  * Use hash for NR Sampling  : no
  * C11 features              : yes
  * TTY colors                : yes
  * Float Precision(PF}       : no
  * Deprecation Warnings      : no

Optimizations
-------------
  * Auto Vectorization        : yes
  * Explicit SIMD Extension   : yes 
  * Link Time Optimization    : yes
  * POSIX Threads             : yes
  * OpenMP                    : yes

Scripting Language Interfaces
-----------------------------
  * Perl 5                    : yes
  * Python 3.x                : yes
  * Python 2.x                : no

Documentation
-------------
  * Reference Manual (PDF)    : yes 
  * Reference Manual (HTML)   : yes 
  * Tutorial (PDF)            : yes 
  * Tutorial (HTML)           : no 
  * CLA (PDF)                 : yes 

Unit Tests
----------
  * Executable Programs       : yes
  * C-Library                 : no
  * Perl 5 Interface          : yes
  * Python 3.x Interface      : yes
  * Python 2.x Interface      : no

MacOS X
-------
  * Universal Binary          : no
  * Installer                 : no
  * SDK                       : no

Install Directories
-------------------
  * Executables               : /usr/local/bin
  * Libraries                 : /usr/local/lib
  * Header files              : /usr/local/include
  * Extra Data                : /usr/local/share
  * Man pages                 : /usr/local/share/man
  * Documentation             : /usr/local/share/doc/ViennaRNA
      (HTML)                  : /usr/local/share/doc/ViennaRNA/html
      (PDF)                   : /usr/local/share/doc/ViennaRNA
  * Perl5 Interface           : 
      (binaries)              : /usr/local/lib/x86_64-linux-gnu/perl/5.30.0
      (scripts)               : /usr/local/share/perl/5.30.0
  * Python 3.x Interface      : 
      (binaries)              : /usr/local/lib/python3.8/site-packages
      (scripts)               : /usr/local/lib/python3.8/site-packages
  * Python 2.x Interface      : Not to be installed Python.h missing
      (binaries)              : 
      (scripts)               : 

You can run 'make', 'make check', and 'make install' now!
```
After configuration, I ran 'make' and 'sudo make install' without errors, but the Python module 'RNA' was not found.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'RNA'
```

**### Next,** I tried to install using bioconda channel and it worked. But previously installed packages including 'forgi' were removed during viennarna installation.
```
conda create -n viennarna
conda activate viennarna
pip install --upgrade forgi[all]
conda install -c bioconda viennarna
python -c 'import RNA' # imported
python -c 'import forgi' # ModuleNotFoundError: No module named 'forgi'
```
Upon digging, it may be some kind of conda bug that existing libraries or packages get deleted while installing new package.
(https://github.com/conda/conda/issues/3603)

My Ubuntu environment is:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

conda 22.9.0
Python 3.8.5
```

Does anyone have any ideas on this issue?

**Comment by RaumZeit** [comment]
First, it seems that your installation is a little mixed up. Lets go through that step by step.
When you install the package from source you see the install destination path for the Python module at the end of the `./configure` step. In your case this was:
```
  * Python 3.x Interface      : 
      (binaries)              : /usr/local/lib/python3.8/site-packages
      (scripts)               : /usr/local/lib/python3.8/site-packages
```
When you now run the python interpreter, make sure that this path is among your python library paths. You can check that with:
```
import sys
print (sys.path)
```
If that is not the case, you need to either set the `PYTHONPATH` variable or change the `sys.path` accordingly.

Installation from bioconda should always work out-of-the-box. If installation of some package from bioconda results in removal of a local installation of another package then your bioconda setup might be wrong. Or you installed a local package from within the conda environment which conda was then not aware of.

**Comment by eumhh** [comment]
> First, it seems that your installation is a little mixed up. Lets go through that step by step. When you install the package from source you see the install destination path for the Python module at the end of the `./configure` step. In your case this was:
> 
> ```
>   * Python 3.x Interface      : 
>       (binaries)              : /usr/local/lib/python3.8/site-packages
>       (scripts)               : /usr/local/lib/python3.8/site-packages
> ```
> 
> When you now run the python interpreter, make sure that this path is among your python library paths. You can check that with:
> 
> ```
> import sys
> print (sys.path)
> ```
> 
> If that is not the case, you need to either set the `PYTHONPATH` variable or change the `sys.path` accordingly.
> 
> Installation from bioconda should always work out-of-the-box. If installation of some package from bioconda results in removal of a local installation of another package then your bioconda setup might be wrong. Or you installed a local package from within the conda environment which conda was then not aware of.


Thanks! The problem was solved by setting the PYTHONPATH.
```
echo "export PYTHONPATH=${PYTHONPATH}:/usr/local/lib/python3.8/site-packages" >> ~/.bashrc
source ~/.bashrc
```
And thanks again for the clarification on the problem with the installation from bioconda.
