### ISSUE TITLE
Probabilities and Python

### ISSUE THREAD

**Issue by StillJosh** [ViennaRNA/ViennaRNA#175]
Hey everyone, 

I am trying to achieve the same output as on the RNAfold Webserver in python. I am using python 2.7 and ViennaRNA 2.4, as in the webservice. However, I have noticed some slight differences when calculating the pairing probabilities for a specific RNA and hope you can help me out here. 

The setup is the following: 
```
import RNA

# Get DNA/RNA sequence from input and transform it to uppercase RNA sequence
seq = "ATGACTTCCTACAGCTATCGCCAGTCGTCGGCCACGTCGTCCTTCGGAGGCCTGGGCGGCGGCTCCGTGCGTTTTGGGCCGGGGGTCGCCTTTCGCGCGCCCAGCATTCACGGGGGCTCCGGCGGCCGCGGCGTATCCGTGTCCTCCGCCCGCTTTGTGTCCTCGTCCTCCTCGGGGGCCTACGGCGGCGGCTACGGCGGCGTCCTGACCGCGTCCGACGGGCTGCTGGCGGGCAACGAGAAGCTAACCATGCAGAACCTCAACGACCGCCTGGCCTCCTACCTGGACAAGGTGCGCGCCCTGGAGGCGGCCAACGGCGAGCTAGAGGTGAAGATCCGCGACTGGTACCAGAAGCAGGGGCCTGGGCCCTCCCGCGACTACAGCCACTACTACACGACCATCCAGGACCTGCGGGACAAGATTCTTGGTGCCACCATTGAGAACTCCAGGATTGTCCTGCAGATCGACAATGCCCGTCTGGCTGCAGATGACTTCCGAACCAAGTTTGAGACGGAACAGGCTCTGCGCATGAGCGTGGAGGCCGACATCAACGGCCTGCGCAGGGTGCTGGATGAGCTGACCCTGGCCAGGACCGACCTGGAGATGCAGATCGAAGGCCTGAAGGAAGAGCTGGCCTACCTGAAGAAGAACCATGAGGAGGAAATCAGTACGCTGAGGGGCCAAGTGGGAGGCCAGGTCAGTGTGGAGGTGGATTCCGCTCCGGGCACCGATCTCGCCAAGATCCTGAGTGACATGCGAAGCCAATATGAGGTCATGGCCGAGCAGAACCGGAAGGATGCTGAAGCCTGGTTCACCAGCCGGACTGAAGAATTGAACCGGGAGGTCGCTGGCCACACGGAGCAGCTCCAGATGAGCAGGTCCGAGGTTACTGACCTGCGGCGCACCCTTCAGGGTCTTGAGATTGAGCTGCAGTCACAGCTGAGCATGAAAGCTGCCTTGGAAGACACACTGGCAGAAACGGAGGCGCGCTTTGGAGCCCAGCTGGCGCATATCCAGGCGCTGATCAGCGGTATTGAAGCCCAGCTGGGCGATGTGCGAGCTGATAGTGAGCGGCAGAATCAGGAGTACCAGCGGCTCATGGACATCAAGTCGCGGCTGGAGCAGGAGATTGCCACCTACCGCAGCCTGCTCGAGGGACAGGAAGATCACTACAACAATTTGTCTGCCTCCAAGGTCCTCTGA"
seq = seq.replace("T", "U")
seq = seq.upper()

# Set --noLP as in the web interface to "Produce structures without lonely pairs (helices of length 1)"
RNA.cvar.noLP = 1

fc = RNA.fold_compound(seq)
(bp_propensity, dG) = fc.pf()

# Calculate Centroid-Folding (i.e. dot-bracket-notation)
(centroid_struct, centroid_dist) = fc.centroid()

# Calculate basepair-probability
basepair_probs = fc.bpp()
```

Now we calculate the probabilities as in the coloring, by taking $p_i = 1 - \sum_{j\neq i} p_{i,j}$ if $i$ has a dot "." and $p_{i,j}$ if $i$ and $j$ have matching brackets. We then compare this with the probabilities in the webservice coloring (where we use the values in the FORNA View -> Colors -> Custom "Set" as comparison) and see see that for the most parts, the Webserver probabilities match the python calculated probabilities. Somewhere around index 40, however, we see that they diverge heavily. 

Here are the first 50 absolute differences between webserver and self-calculated values, rounded to 3 decimals.
`0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.002, 0.004, 0.003, 0.0, 0.001, 0.001, 0.001, 0.0, 0.014, 0.014, 0.0, 0.005, 0.005, 0.005, 0.001, 0.003, 0.002, 0.0, 0.001, 0.001, 0.001, 0.001, 0.0, 0.003, 0.005, 0.003, 0.005, 0.003, 0.001, 0.0,  0.0, 0.0, 0.0, 0.011, 0.469, 0.464, 0.4,0.47, 0.478`

The first 40 small differences are surely rounding errors, but then, without a visible reason, the numbers explode. Notice, that up until index 60 or so, we only have "." in our folding. 

Does anyone have an idea why this happens and how it can be fixed? 
Any help is highly appreciated! Cheers!

Also on a side note, as I might want to work with you tool a bit more: Is there some place where questions aside from possible bugs can be asked (like e.g. github discussion forum) or do you prefer not to answer general questions?

**Comment by RaumZeit** [comment]
Hi,
I just tried to reproduce your problem with the Python interface of v2.5.1 but could not detect any differences between the webserver and the local python script apart from possible rounding errors.
I used the following additional code to compute your vector of position-wise probabilities:
```
pt = RNA.ptable(centroid_struct)

for i in range(1, pt[0] + 1):
    if pt[i] == 0:
        q = 0
        for j in range(1, i):
            q += basepair_probs[j][i]
        for j in range(i + 1, pt[0] + 1):
            q += basepair_probs[i][j]
        print("{:}\t{}".format(i, 1-q))
    elif pt[i] > i:
        print("{}\t{}".format(i, basepair_probs[i][pt[i]]))
    else:
        print("{}\t{}".format(i, basepair_probs[pt[i]][i]))
```

Can you re-check whether you may have any mistakes in your own computation?
I've attached my results as 4 column tab separated file, 1st column index, 2nd column python probabilities, 3rd column webserver probabilities and 4th column pytonprob - webserverprob.

[probs_diff.txt](https://github.com/ViennaRNA/ViennaRNA/files/11163129/probs_diff.txt)

**Comment by RaumZeit** [comment]
No further update have been provided for this issue. So I'm closing it for now. If the problem persists, please feel free to re-open...
