### ISSUE TITLE
Segmentation fault when Lfoldz is called using Python Bindings

### ISSUE THREAD

**Issue by rajgopals** [ViennaRNA/ViennaRNA#176]
Lfoldz, from version 2.5.1, when called from python 3 crashes with a segmentation fault.  For e.g.

bash-5.2$ python3
Python 3.11.1 (main, Dec 16 2022, 23:18:04) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import RNA
>>> RNA.Lfoldz('GUCUACGGCCAUACCACCGGGAAAAAACCGGUUCUCGUCCGAUCACCGAAGUCAAGCCCGGUAGGGCCAGGUUAGUACUUGGAUGGGUGACCGCCUGGGAAUACCUGGUGCUGUAGACUU', 60, 0.0)
Segmentation fault (core dumped)

Modifying the mfe_window_wrappers.c file to include a call to vrna_zsc_filter_init, prior to calling vrna_mfe_window_zscore fixes this.  With this fix in place, I get the following

bash-5.2$ python3
Python 3.11.1 (main, Dec 16 2022, 23:18:04) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import RNA
>>> RNA.Lfoldz('GUCUACGGCCAUACCACCGGGAAAAAACCGGUUCUCGUCCGAUCACCGAAGUCAAGCCCGGUAGGGCCAGGUUAGUACUUGGAUGGGUGACCGCCUGGGAAUACCUGGUGCUGUAGACUU', 60, 0.0)
.((((((((((.....(((((.((.....))..)))))))))))...)))). (-12.10)   69 z= -0.092
.(..(((.(((((((.....((.((.(((....))))).))....))))))).)))..). (-22.70)   58 z= -2.101
.(((((((((...((((((...(((((....)))))...))))))...)))).)).))). (-24.80)   54 z= -2.485
.(((((((((..((..((.((..((((....))))..)))).))..))))))))). (-18.80)   33 z= -1.279
-37.70000076293945

The diff is below

bash-5.2$ diff -p mfe_window_wrappers.c.orig mfe_window_wrappers.c
*** mfe_window_wrappers.c.orig	2022-12-17 07:53:21.749762033 +0530
--- mfe_window_wrappers.c	2022-12-17 07:54:19.042220456 +0530
*************** vrna_Lfoldz(const char  *string,
*** 84,90 ****
    md.max_bp_span  = window_size;
  
    vc = vrna_fold_compound(string, &md, VRNA_OPTION_WINDOW);
! 
    energy = vrna_mfe_window_zscore(vc, min_z, file);
  
    vrna_fold_compound_free(vc);
--- 84,90 ----
    md.max_bp_span  = window_size;
  
    vc = vrna_fold_compound(string, &md, VRNA_OPTION_WINDOW);
!   vrna_zsc_filter_init(vc, min_z, VRNA_ZSCORE_FILTER_ON);
    energy = vrna_mfe_window_zscore(vc, min_z, file);
  
    vrna_fold_compound_free(vc);

**Comment by RaumZeit** [comment]
Thank you for the detailed bug report! We've already adapted our code for the next release (v2.6.0) accordingly. Initialization of the z-score container will then always be done automatically, if not already present within the vrna_fold_compound_t data structure.

**Comment by RaumZeit** [comment]
version 2.6.0 is on its way for release. So, I'm closing this issue now...
