### ISSUE TITLE
Installation failure on windows

### ISSUE THREAD

**Issue by Nikita-dalal** [ViennaRNA/ViennaRNA#178]
I have installed binary of viennaRNA on windows.
But this is not showing installation.I have to use this in R studio as third party dependency of OpenprimeR. But their it shows that viennaRNA is not installed.

**Comment by RaumZeit** [comment]
As far as I understand OpenprimeR ships its own executables of the ViennaRNA Package for Windows. Please try contacting the authors of OpenprimeR for support.
As a hint, you may want to look whether RNAfold.exe and alike are installed somewhere on your machine. If so, maybe you only need to adjust the PATH variable in REGEX.
