### ISSUE TITLE
Compile problem with python 3.6.3

### ISSUE THREAD

**Issue by shevegen** [ViennaRNA/ViennaRNA#18]
Hello Ronny and everyone else,

I have just been trying the latest release of ViennaRNA aka:

**ViennaRNA-2.4.3**

I got a problem with it during compilation time, so next, I will just
copy/paste the error(s) I got:

make  install-data-hook  
make[5]: Entering directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python' 
 /Programs/Viennarna/2.4.3/lib/python2.7/site-packages/_RNA.la  
make[5]: Leaving directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python'  
make[4]: Leaving directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python'  
make[3]: Leaving directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python'  
make[2]: Leaving directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python'  
Making install in Python3
make[2]: Entering directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3'   
make  install-am
make[3]: Entering directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3'   
  GEN   RNA/__pycache__/__init__.cpython-36.opt-1.pyc
Traceback (most recent call last):   
  File "<string>", line 1, in <module>  
ImportError: /Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3/_RNA.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyInstance_Type  
Traceback (most recent call last):   
  File "/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3/RNA/__init__.py", line 14, in swig_import_helper   
 return importlib.import_module(mname)  
  File "/Programs/Python/3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module  
 return _bootstrap._gcd_import(name[level:], package, level) 
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import   
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load   
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked   
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked   
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec 
  File "<frozen importlib._bootstrap_external>", line 922, in create_module 
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed 
ImportError: /Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3/_RNA.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyInstance_Type  

During handling of the above exception, another exception occurred:   

Traceback (most recent call last):   
  File "<string>", line 1, in <module>  
  File "/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3/RNA/__init__.py", line 17, in <module> 
 _RNA = swig_import_helper()   
  File "/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3/RNA/__init__.py", line 16, in swig_import_helper   
 return importlib.import_module('_RNA') 
  File "/Programs/Python/3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
 return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3/_RNA.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyInstance_Type
make[3]: *** [Makefile:988: RNA/__pycache__/__init__.cpython-36.opt-1.pyc] Error 1
make[3]: Leaving directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3'
make[2]: *** [Makefile:835: install] Error 2
make[2]: Leaving directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces/Python3'
make[1]: *** [Makefile:582: install-recursive] Error 1
make[1]: Leaving directory '/Depot/Temp/ViennaRNA-2.4.3/interfaces'
make: *** [Makefile:656: install-recursive] Error 1

So the **error** I get is:

  _RNA.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyInstance_Type

My python-fu is way too limited to be of any big help.

My host system is slackware with mostly source-compiled programs
and gcc version 7.2.0 (GCC). The python 3 was compiled with gcc
version 6.2.0 some time ago. I am not sure if it helps if I add which
commandline switches I used for python 3, but just in case, I used either
the "--enable-ipv6 --enable-profiling --enable-shared --enable-unicode=ucs4
--with-ensurepip=yes --with-ssl --with-system-ffi --with-system-expat
--without-ensurepip " or I followed the BLFS instructions at:
http://www.linuxfromscratch.org/blfs/view/svn/general/python3.html
--enable-shared --with-system-expat --with-system-ffi --with-ensurepip=yes
(I don't remember offhand ... may probably recompile python 3 again 
just to make sure, before re-compiling ViennaRNA)

I assume that the error may be somehow related to encoding, UTF type
or what not. I do not know how easy it would be to modify the compile 
script, but if possible it would be nice if the code could check whether 
the python version on the target computer may have this problem above
such as PyInstance_Type, and if so, perhaps notify the user at
configure-time. But again, I am just mostly guessing here really, I have
no real idea about the error. :)

Please do feel free to close this issue at any moment in time! I'll try
the next ViennaRNA version (or just disable python3 for the time
being; I am mostly defaulting to python2 still for other programs that
need a working python version).

**Comment by RaumZeit** [comment]
Hi Robert,
the python import error looks strange. There might be several reasons for why you see such an error. First, it might be that the some ABI changed during the upgrade from gcc 6.2 to 7.2, breaking correct linkage. You might want to reinstall python 3.6 in that case.
Second, your python config might be strange. You could paste you `config.log` and the output of `make V=1` so we can see if everything is set up correctly at configure time. Our autoconf script tries to determine the correct compile and linker flags from `python3-config` or similar, maybe that's what is failing on your end?

**Comment by RaumZeit** [comment]
P.S.:
I've added a configure-time check to see if linking against python3 library works. This will be included in the next release, and should prevent the problem with your systems configuration...

**Comment by poikilos** [comment]
@RaumZeit, Please provide a commit related to the fix, as PyInstance_Type is not present in Python 3 and seeing the fix will benefit other projects as this issue is one of the few results for `undefined symbol: PyInstance_Type` on Google. Thanks.
