### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by shl129** [ViennaRNA/ViennaRNA#182]
Hi,
I installed v2.5.1 in my MacBook from the source code. When I run the code :

gcc-12 -fopenmp -Wall -g -std=gnu99  .//include/DNA_manipulation.o .//include/Check_functions.o .//main.o -o PLA_lib_generate -L/Users/shenglin/ViennaRNA/lib -lRNA -lm

it reported a lot of undefined symbols. Does anyone has the same problem?

Undefined symbols for architecture x86_64:
  "__ZTVN10__cxxabiv117__class_type_infoE", referenced from:
      __ZTI7QMatrix in libRNA.a(svm.o)
      __ZTI6Solver in libRNA.a(svm.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "__ZTVN10__cxxabiv120__si_class_type_infoE", referenced from:
      __ZTI6Kernel in libRNA.a(svm.o)
      __ZTI9Solver_NU in libRNA.a(svm.o)
      __ZTI5SVC_Q in libRNA.a(svm.o)
      __ZTI11ONE_CLASS_Q in libRNA.a(svm.o)
      __ZTI5SVR_Q in libRNA.a(svm.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "__ZdaPv", referenced from:
      __ZN6KernelD2Ev in libRNA.a(svm.o)
      __ZN6Solver5SolveEiRK7QMatrixPKdPKaPddddPNS_12SolutionInfoEi in libRNA.a(svm.o)
      __ZL13svm_train_onePK11svm_problemPK13svm_parameterdd in libRNA.a(svm.o)
      __ZN5SVC_QC2ERK11svm_problemRK13svm_parameterPKa in libRNA.a(svm.o)
      __ZN5SVC_QD2Ev in libRNA.a(svm.o)
      __ZN11ONE_CLASS_QC2ERK11svm_problemRK13svm_parameter in libRNA.a(svm.o)
      __ZN11ONE_CLASS_QD2Ev in libRNA.a(svm.o)
      ...
  "__ZdlPv", referenced from:
      __ZN6SolverD0Ev in libRNA.a(svm.o)
      __ZN9Solver_NUD0Ev in libRNA.a(svm.o)
      __ZN5SVC_QD0Ev in libRNA.a(svm.o)
      __ZN5SVC_QD2Ev in libRNA.a(svm.o)
      __ZN11ONE_CLASS_QD0Ev in libRNA.a(svm.o)
      __ZN11ONE_CLASS_QD2Ev in libRNA.a(svm.o)
      __ZN5SVR_QD0Ev in libRNA.a(svm.o)
      ...
  "__Znam", referenced from:
      __ZN6KernelC2EiPKP8svm_nodeRK13svm_parameter in libRNA.a(svm.o)
      __ZN6Solver5SolveEiRK7QMatrixPKdPKaPddddPNS_12SolutionInfoEi in libRNA.a(svm.o)
      __ZL13svm_train_onePK11svm_problemPK13svm_parameterdd in libRNA.a(svm.o)
      __ZN5SVC_QC2ERK11svm_problemRK13svm_parameterPKa in libRNA.a(svm.o)
      __ZN11ONE_CLASS_QC2ERK11svm_problemRK13svm_parameter in libRNA.a(svm.o)
      __ZN5SVR_QC2ERK11svm_problemRK13svm_parameter in libRNA.a(svm.o)
  "__Znwm", referenced from:
      __ZN5SVC_QC2ERK11svm_problemRK13svm_parameterPKa in libRNA.a(svm.o)
      __ZN11ONE_CLASS_QC2ERK11svm_problemRK13svm_parameter in libRNA.a(svm.o)
      __ZN5SVR_QC2ERK11svm_problemRK13svm_parameter in libRNA.a(svm.o)
  "___cxa_pure_virtual", referenced from:
      __ZTV6Kernel in libRNA.a(svm.o)
  "___gxx_personality_v0", referenced from:
      __ZL13svm_train_onePK11svm_problemPK13svm_parameterdd in libRNA.a(svm.o)
      __ZN5SVC_QC2ERK11svm_problemRK13svm_parameterPKa in libRNA.a(svm.o)
      __ZN11ONE_CLASS_QC2ERK11svm_problemRK13svm_parameter in libRNA.a(svm.o)
      __ZN5SVR_QC2ERK11svm_problemRK13svm_parameter in libRNA.a(svm.o)
      Dwarf Exception Unwind Info (__eh_frame) in libRNA.a(svm.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [main] Error 1

**Comment by RaumZeit** [comment]
Seems like you are missing some additional libraries to link your code to, e.g. `-lstdc++`.
If you have `pkg-config` installed, simply run
```
pkg-config --libs RNAlib2
```
to find out the linker flags for your installation. My installation reports:
```
$ pkg-config --libs RNAlib2
-fno-lto -Wl,-fno-lto -lRNA -fopenmp -lgsl -lgslcblas -lpthread -lmpfr -lgmp -lstdc++
```

**Comment by RaumZeit** [comment]
closing this issue now since no updates have been provided for 3 months.
Feel free to re-open if your problem persists even after using the suggestion above...
