### ISSUE TITLE
DOC: mention yacc in build requirements

### ISSUE THREAD

**Issue by daz10000** [ViennaRNA/ViennaRNA#183]
Tiny thing, but trying to get through a first time build from the git repo and found that yacc was required for RNAForester.  Would be nice to have it on the tool list in the README

```
make[4]: Entering directory '/home/daz/src/ViennaRNA/src/RNAforester/src'
  YACC     anchors/shape.cpp
../ylwrap: line 176: yacc: command not found
```

**Comment by RaumZeit** [comment]
This will be included in the README.md with the next release.
