### ISSUE TITLE
Install ViennaRNA erro

### ISSUE THREAD

**Issue by fanyucai1** [ViennaRNA/ViennaRNA#19]
when I  install ViennaRNA from source, the erro following:
sorry - this program has been built without plugin support
make[3]: *** [libRNA_constraints.la] Error 1
make[3]: *** Waiting for unfinished jobs....
sorry - this program has been built without plugin support
make[3]: *** [libRNA_utils.la] Error 1
sorry - this program has been built without plugin support
make[3]: *** [libRNA_plotting.la] Error 1
make[3]: Leaving directory `/home/fanyucai/software/ViennaRNA/ViennaRNA-2.4.3/src/ViennaRNA'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/fanyucai/software/ViennaRNA/ViennaRNA-2.4.3/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/fanyucai/software/ViennaRNA/ViennaRNA-2.4.3'
make: *** [all] Error 2

**Comment by RaumZeit** [comment]
It seems you might be using a compiler for which linking with LTO support fails. In case you use GCC, please consider using a version >= 5.1. Alternatively, you may switch-off Link Time Optimization (LTO) support at configure time using the `--disable-lto` switch, e.g.:
```
./configure --disable-lto
```
