### ISSUE TITLE
AttributeError: 'list' object has no attribute 'mfe'

### ISSUE THREAD

**Issue by Turningl** [ViennaRNA/ViennaRNA#191]
### Contact Details

zl16035056@163.com

### What happened?

I have these code:
def get_fold(seq):
    for i in range(33 - len(seq)):
        seq = seq + 'N'
    fc = RNA.fold(seq)
    # compute MFE and MFE structure
    (mfe_struct, mfe) = fc.mfe()
    return mfe_struct

But the bug is :
    (mfe_struct, mfe) = fc.mfe()
AttributeError: 'list' object has no attribute 'mfe'

### Version

2.4.x

### Which operating system are you using?

Linux (Default), Windows

### Does the problem occur with one of our executable program or the C-library?

Python 3 interface

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
This part of your code is obviously wrong:
```
fc = RNA.fold(seq)
```
Here, you seem to request an object of type `fold_compound` but called the `fold()` function instead of the `fold_compound()` constructor. This object then has the `mfe()` method attached. Replacing this line by
```
fc = RNA.fold_compound(seq)
```
should work...
