### ISSUE TITLE
[Bug]: Build breaks due to the use of the deprecated feature std::binary_function

### ISSUE THREAD

**Issue by yurivict** [ViennaRNA/ViennaRNA#193]
### What happened?

```std::binary_function``` was removed in C++17. You don't specify the C++ standard level. clang-16 defaults to C++20. This breaks the compilation because ```std::binary_function``` doesn't exist in C++20.

Please:
* remove the use of deprecated C++ features
* add compiler options setting the C++ standard level

Version: 2.6.3
FreeBSD 13.2

### Version

2.6.x (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
Thanks for the bug report!
Indeed, the `RNAforester` and `kinwalker` programs still use deprecated C++ features.
We've already addressed this issue in our development branch and the fixes will be made public with the next release of the `ViennaRNA` Package. Until then, I'd suggest to deactivate building `kinwalker` and/or `RNAforester` to avoid this issue.

Best

**Comment by RaumZeit** [comment]
Fixed with v2.6.4
