### ISSUE TITLE
RSS Image out of bounds

### ISSUE THREAD

**Issue by bretonics** [ViennaRNA/ViennaRNA#2]
When creating the RNA structure image adding the reliability information, `relplot.pl rna.ps dot.ps > rss.ps`, the structure image goes out-of-bounds in the canvas at the ends. I know we can rotate, but is there a way to size the actual image?

<img width="548" alt="screen shot 2016-11-10 at 11 00 20 am" src="https://cloud.githubusercontent.com/assets/3980538/20183905/eea3345c-a734-11e6-9814-74ff239115a9.png">

**Comment by RaumZeit** [comment]
You can adapt the bounding box of the EPS image manually. Just open the EPS file with a simple text editor and replace the line
```%%BoundingBox: 66 210 518 662```
with coordinates that actually fit the entire plot. To find out what the correct dimensions would be you can use the `gs` command, e.g.:
```gs -dNOPAUSE -dBATCH -q -sDEVICE=bbox rna.ps```

I've already changed the EPS output in our development branch such that the plot is automatically rescaled and translated within the static bounding box. Thus, with the next release manual intervention won't be required.
