### ISSUE TITLE
RNALfold output of a common region (exactly the same sequence) in two sequences are different

### ISSUE THREAD

**Issue by mt1022** [ViennaRNA/ViennaRNA#20]
I have two sequences `test_50` and `test_100`, where `test_50` is the first 3920 bp of `test_100`. I folded the two sequences seperately with the following commands:

```bash
NALfold -z 0 <test_100.fa >test_100.lfold
RNALfold -z 0 <test_50.fa >test_50.lfold
```
I am expecting the output for secondary structures in first 3920 bp from the two files should be the same and have the same z-score  because they have exactly the same sequence.

However, when I examined the output `test_100.lfold` and `test_50.lfold`, I found results from the two files are exactly the same except for three ones near the 3' end of the 3920bp sequence:

```r
library(data.table)
library(Biostrings)
test_50 <- readDNAStringSet('test_50.fa')
test_100 <- readDNAStringSet('test_100.fa')

width(test_50)
# [1] 3920  # length of first seq

# seq name and sequence were manually removed from RNALfold results
dt1 <- fread('test_50.lfold')
dt2 <- fread('test_100.lfold')


# set V1 to end position of secondary structure span
dt1[, V1 := nchar(V1) - 1 + V3]
dt2[, V1 := nchar(V1) - 1 + V3]

# keep structures that are fully included in first 3920 bp; 
dt3 <- dt2[V1 <= 3920]

# compare results for test_50 and test_100
dt4 <- merge(dt3, dt1, by = 'V3', all = TRUE)

tail(dt4)
# > tail(dt4)
#      V3 V1.x     V2.x V4.x   V5.x V1.y     V2.y V4.y   V5.y
# 1: 3480 3544 (-20.50)   z= -5.161 3544 (-20.50)   z= -5.161
# 2: 3528 3643 (-39.10)   z= -4.238 3643 (-39.10)   z= -4.238
# 3: 3536 3635 (-28.00)   z= -2.652 3635 (-28.00)   z= -2.652
# 4: 3704 3813 (-31.80)   z= -2.483   NA       NA   NA     NA
# 5: 3770 3891 (-27.30)   z= -2.468   NA       NA   NA     NA
# 6: 3771   NA       NA   NA     NA 3890 (-26.00)   z= -2.129
```

As shown in above code chunk (row 4-6 of `tail(dt4)`), the three structures are not consitent between `RNALfold` results of `test_50` and `test_100`, although they have exactly the same sequence at this region.

Why this happens? Is this a bug or normal behavior?  

The sequence files required to reproduce the issue and RNALfold output on my machine can be found here:
[test_RNALfold.tar.gz](https://github.com/ViennaRNA/ViennaRNA/files/1531419/test_RNALfold.tar.gz)

other information that might be helpful:
```bash
$ RNALfold --version
RNALfold 2.1.9

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```
The test_50 and test_100 were first 50 lines and 100 lines of chrom 2L of fly, respectively.

**Comment by mt1022** [comment]
The same issue is reproducible with newest version of RNALfold (2.4.3).

**Comment by RaumZeit** [comment]
This behavior is expected.
RNALfold processes the sequence from 3' to 5' end, so when it enters the 'overlap' region between the two files, the output of the larger file (the one that has another 4000nt that were processed earlier) determines which of the first hits (most 3') in the smaller file will actually be printed to output. In the overlap region, there might be structures you only see in the smaller of both files as well as structures only present in the larger file.
The reason for this is, that due to the implementation of the sliding window approach RNALfold only prints out locally optimal structures that are not part of a larger structure located more 3'.
