### ISSUE TITLE
Please provide linux+arm64 pypi wheel

### ISSUE THREAD

**Issue by anayden** [ViennaRNA/ViennaRNA#207]
Hello,

Firstly, I'd like to express my gratitude for the work you've done on ViennaRNA; it has been tremendously helpful. Currently, I am using ViennaRNA from pypi on an Apple Silicon device. I'm pleased to note that the macOS+arm64 wheel operates seamlessly on my Mac.

However, I have encountered a challenge when trying to install the wheel in a native Docker container. Although there is a workaround involving running Docker with x86 via Rosetta, this approach introduces some latency due to the translation layer. If it's possible to provide a native Docker wheel, it would significantly enhance the user experience for those like me working on Apple Silicon devices via Docker.

Understanding the complexities and demands of maintaining an open-source project, I genuinely appreciate any assistance or insights you might offer on this matter.

Warm regards,
Alexey

**Comment by AntonPetrov** [comment]
Hi folks,

Just to provide more context, Vienna RNA is the last dependency for the [R2DT project](https://docs.r2dt.bio) that requires the translation layer, so we would greatly appreciate it if you could help enable full support for Apple silicon in R2DT. 🚀

Please let us know if you need more information and many thanks in advance for looking into this!

Can't wait to see everyone at the next Benasque! ⛰️⛰️⛰️

**Comment by RaumZeit** [comment]
Hi @anayden and @AntonPetrov ,
so, i just tested our CI builds to produce linux aarch64 wheels and it seems to at least partially work. The thing is that the github actions use `qemu` to emulate the ARM architecture while building and testing the Python wheels. And here, the build process seems to work but the tests do not run through. Actually, the tests do not run at all but crash right from the beginning. So I don't know whether the wheels are actually functional. It might be that the tests only fail due to the emulation, but I have no physical arm64 machine at hand to actually test this.

For now, I deactivated testing for the aarch64 builds and downloaded the wheels. If you want to give it a try, just email me and I'm happy to share them to see whether they actually work on a native arm64 machine and within your docker environment.

We will be releasing v2.6.4 soon, so it would be nice to have these builds available at PyPI as well. But as I said, I can not guarantee they they actually work.

**Comment by anayden** [comment]
Hi @RaumZeit 

Thank you for your prompt response, much appreciated. I downloaded the wheel from the `artifacts` section [here](https://github.com/ViennaRNA/ViennaRNA/actions/runs/6232454312) and installed it in a local docker container. Even though I'm able to install the wheel, it seems to be broken:

```
# uname -a
Linux 52a945651127 6.4.16-orbstack-00103-g02b40eb69695 #1 SMP Wed Sep 13 10:13:30 UTC 2023 aarch64 GNU/Linux

# python -V
Python 3.11.5

# pip install ./ViennaRNA-2.6.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
Processing ./ViennaRNA-2.6.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
Installing collected packages: ViennaRNA
Successfully installed ViennaRNA-2.6.3

# python
Python 3.11.5 (main, Sep  7 2023, 18:53:16) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import RNA
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/RNA/__init__.py", line 45, in <module>
    from RNA.RNA import *
  File "/usr/local/lib/python3.11/site-packages/RNA/RNA.py", line 11, in <module>
    from . import _RNA
ImportError: /usr/local/lib/python3.11/site-packages/RNA/_RNA.cpython-311-aarch64-linux-gnu.so: undefined symbol: vrna_fun_zip_add_min_avx512

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/RNA/__init__.py", line 47, in <module>
    raise ImportError('Failed to load ViennaRNA RNAlib Python wrapper')
ImportError: Failed to load ViennaRNA RNAlib Python wrapper
```

So I'd guess the tests were failing for a reason :) I'm not very knowledgeable in this area, but it seems to me, it's related to ARM not supporting Intel's SSE instructions, which is kind of a bummer.

I found 2 header-only cross-platform implementations of SIMD for both Intel and ARM:

* https://github.com/DLTcollab/sse2neon
* https://github.com/simd-everywhere/simde

I genuinely don't know how much effort it would require to adopt one of these solutions and not sure if it's going to help at all, to be honest :) 

I'd be happy to help with that, but sadly my C++ skills are too rusty for such a close-to-hardware pull request.

Anyway, thanks a lot for your efforts!

**Comment by RaumZeit** [comment]
Thank you very much! This is really helpful!

So, the thing is that SIMD should be deactivated while compiling for ARM and I was under the impression that I actually set up everything correctly. After all, it works for the MacOS X arm64 builds.
I already have a suspect in mind that needs to be looked at, so I'll try some changes to the code later today to see whether this can be fixed easily.

Cheers,
Ronny

**Comment by RaumZeit** [comment]
So, it seems that the problems are fixed now and the github actions happily build linux `aarch64 wheels` that also pass the unit tests! I've adapted the setup.py script and still don't know exactly why the previous version might have worked for Mac OS X arm64 but not for Linux aarch64. Anyhow, now it should all work as expected...

These fixes will be part of the upcoming release of version 2.6.4 which is scheduled for next week. Our CI will build and upload the wheels to PyPI as soon as we pushed the new release to github. I hope this then integrates well with your plans for the R2DT project.

Cheers,
Ronny

**Comment by RaumZeit** [comment]
> Hi @RaumZeit
> ...
> I found 2 header-only cross-platform implementations of SIMD for both Intel and ARM:
> 
> * https://github.com/DLTcollab/sse2neon
> * https://github.com/simd-everywhere/simde
> 
Thanks for these hints! I'll have a look at them to see whether they can be easily integrated into our sources to also support the ARM NEON SIMD instructions.

**Comment by AntonPetrov** [comment]
Thank you so much Ronny, I really appreciate it and look forward to trying it next week! I will update this issue once we've tested the wheels 🎡🐍

**Comment by anayden** [comment]
Ronny, thanks a lot for your help. Joining Anton in our waiting for the next release!

**Comment by RaumZeit** [comment]
Sure thing!
So, it's done... ViennaRNA v2.6.4 has been released yesterday. Please give it a try and see whether the Python bindings work for you now in a universal way.

Cheers!

**Comment by AntonPetrov** [comment]
@RaumZeit Thank you so much, it works! 👏👏👏

Using this new version R2DT now supports Apple silicon and runs so much faster. Thanks again - please consider this issue resolved.

**Comment by RaumZeit** [comment]
Great! It was a pleasure to help ;)
...and at the same time it also helped to push the availability of our Python API to more architectures...

hopefully see you soonish in Benasque
