### ISSUE TITLE
WARNING: pf_scale too large

### ISSUE THREAD

**Issue by ArthurGasparindo** [ViennaRNA/ViennaRNA#210]
I working with lncrna, and this warning keeps appearing, and it's only with my down regulated sequences, in the up regulated this isn't an issue. I tried to adjust the pf_scale to a lower value (1.00) but the issue keeps happening, but with a lower number of sequences.

How low is too low for this parameter? Because in the manual I read that it's recommended to be used from 1.00 to 1.2. Should I lower even further or this could be an inherit problem of the sequences?

**Comment by SreeniEadara** [comment]
I recall noticing this on sequences that are entirely GA, where the free energy returned by fc.pf() becomes INF and I see the WARNING: pf_scale too large printed.

**Comment by RaumZeit** [comment]
Almost a year after this issue has been reported, but here is a potential solution:

The default pf_scale parameter is 1.03. For unusually unstructured RNA sequences, you might want to try something closer to 1.0, e.g. 1.01. If that doesn't help, then maybe the sequences are too long and you should consider a local folding strategy, such as implemented in `RNAplfold`?

Closing this issue for now....
Feel free to re-open!
