### ISSUE TITLE
[question] Can I implement a soft constraint with the Python interface?

### ISSUE THREAD

**Issue by ErikPoppleton** [ViennaRNA/ViennaRNA#211]
Hi!  I've been exploring what I can do with ViennaRNA and it's a very impressive set of tools.  What I would like to do is implement a soft constraint to use with `mfe` which penalizes (but does not forbid) bases which are different from a partial reference structure.    Looking at [the documentation](https://www.tbi.univie.ac.at/RNA/ViennaRNA/refman/grammar/constraints/soft.html#c.vrna_sc_add_f), there is a function for adding constraints, but I can't figure out what a 'constraints definition file' is.  In the [C API](https://www.tbi.univie.ac.at/RNA/ViennaRNA/refman/grammar/constraints/soft.html#c.vrna_sc_add_f), I see this which lets you define a function which provides a constraint.  Do I need to write my constraint in C and somehow pass that to my Python code, or is there a way to define a Python function which calculates a constraint? Also, how would I have this function take an argument (the reference structure)?  Thanks!

**Comment by RaumZeit** [comment]
Dear Erik,

the constraints framework is fully exposed from within the Python interface, so each C function has an equivalent in the Python world.

For your particular task, I believe that using a constraints file may be the wrong choice and you should, as you already suggested, indeed go for the soft constraints callback functions. This can all be done by implementing pure Python functions and passing them to the RNAlib Python interface. No additional C-code is required, although for performance reasons this might be worth additional considerations.

Anyhow, the soft constraints callback function prototype in Python is the same as in C:
```.py
def callback(i, j, k, l, d, data):
    return 0
```
So, the callback always receives 6 parameters `i, j, k, l, d`, and `data` and returns an energy correction in units of deka-calories per mol, i.e. 10cal/mol. The parameters `i, j, k`, and `l` correspond to the nucleotide coordinates that are evaluated, where `i` and `j` usually apply to the full segment, and `k` and `l` denote the sub-segment boundaries. The parameter `d` denotes the decomposition step that is being evaluated and may take on the values `RNA.DECOMP_PAIR_HP`, `RNA.DECOMP_PAIR_IL`, etc. as shown in https://viennarna.readthedocs.io/en/latest/grammar/constraints.html (Note, that in the Python interface these constants do not have the `VRNA_` prefix (see also https://viennarna.readthedocs.io/en/latest/wrappers.html and https://viennarna.readthedocs.io/en/latest/api_python.html).
The final parameter, `data` is some data structure that is defined in user-space which can hold any data required to evaluate the callback. It will not be processed by anything in RNAlib and simply passed through to the callback whenever  the constraint callback is evaluated. A more-or-less fun example that reverts the Nearest Neighbor energy model to a Nussinov maximum matching algorithm can be found at https://viennarna.readthedocs.io/en/latest/examples/python.html#fun-with-soft-constraints.

Here, the 
```.py
def MaximumMatching(i, j, k, l, d, data):
    return revert_NN[d](i, j, k, l, data['dummy'], data['params'])
```
returns the negative of the energy contributions that the actual Zuker algorithm would apply for MFE prediction. So the total contribution becomes 0 for each loop, and only base pairs receive a value of -1kcal/mol = 100dekacal/mol.

To give you a skeleton to work with, suppose you want to only treat base pairs from a particular list of pairs, e.g. the pairs (2,17), (3,19), (25,42), differently, and penalize them with 1kcal/mol = 100 dekacal/mol pseudo energy. What you could implement to realize that is as follows:
```.py
import RNA
s = RNA.random_string(50, "ACGU")
cb_data = { \
    'bp_list': [ (2,17), (3,19), (25,42) ], \
    'bp_penalty': 100, \
    'default': 0\
}

def penalize_cb(i, j, k, l, d, data):
    if d in [RNA.DECOMP_PAIR_HP, RNA.DECOMP_PAIR_IL, RNA.DECOMP_PAIR_ML]:
        if (i, j) in data['bp_list']:
             return data['bp_penalty']
    return data['default']

fc = RNA.fold_compound(s)
fc.sc_add_f(penalize_cb)
fc.sc_add_data(cb_data, None)

print(fc.mfe())
```
You see, that the callback function `penalize_cb()` can run arbitrary python code and the `cb_data` dictionary is bound to the `fc` and always passed through to the callback. You could then either pass this dictionary further to any other functions in your Python code, or pre-process everything such that `cb_data` already contains everything required to evaluate the soft constraint before the predictions are actually performed.

I hope the above examples are of help. Let me know if you need more advice.
Best!

**Comment by ErikPoppleton** [comment]
This is exactly what I needed!  Thank you so much.

**Comment by RaumZeit** [comment]
I just noticed, that some of the images for the loop decomposition flags passed to the constraint callback are missing in the documentation at readthedocs. So, please consider using the manual at our institutes homepage instead, e.g.:

https://www.tbi.univie.ac.at/RNA/ViennaRNA/refman/grammar/constraints.html#c.VRNA_DECOMP_PAIR_HP

etc...
