### ISSUE TITLE
[Bug]: Missing `-lgomp` in RNAlib2.pc

### ISSUE THREAD

**Issue by dodomorandi** [ViennaRNA/ViennaRNA#215]
### Contact Details

morandidodo@gmail.com

### What happened?

In version 2.6 an error occurs when linking against libRNA2, because libgomp is not included in RNAlib2.pc. The symbols in the library are used by the libsvm, which is used internally by libRNA2.

If libsvm is always used, it should be sufficient to add `-lgomp` to the linking params.

Unfortunately, I have not been able to create a simple test case, because with trivial programs I am not able to reproduce the error. In any case, the same code did not have any issue with the 2.5 version.

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Does the problem occur with one of our executable program or the C-library?

C-Library

### Relevant log output

This is the last part of the output, related to the linking error:
```
  = note: ld.lld: error: undefined symbol: GOMP_loop_nonmonotonic_guided_start
          >>> referenced by svm.cpp:2610 (../libsvm-3.31/svm.cpp:2610)
          >>>               svm.o:(svm_predict_values._omp_fn.0) in archive /usr/lib/libRNA.a
          >>> referenced by svm.cpp:2629 (../libsvm-3.31/svm.cpp:2629)
          >>>               svm.o:(svm_predict_values._omp_fn.1) in archive /usr/lib/libRNA.a
          >>> referenced by svm.cpp:1408 (../libsvm-3.31/svm.cpp:1408)
          >>>               svm.o:(SVR_Q::get_Q(int, int) const (._omp_fn.0)) in archive /usr/lib/libRNA.a
          >>> referenced 1 more times

          ld.lld: error: undefined symbol: GOMP_loop_end_nowait
          >>> referenced by svm.cpp:2610 (../libsvm-3.31/svm.cpp:2610)
          >>>               svm.o:(svm_predict_values._omp_fn.0) in archive /usr/lib/libRNA.a
          >>> referenced by svm.cpp:2629 (../libsvm-3.31/svm.cpp:2629)
          >>>               svm.o:(svm_predict_values._omp_fn.1) in archive /usr/lib/libRNA.a
          >>> referenced by svm.cpp:1408 (../libsvm-3.31/svm.cpp:1408)
          >>>               svm.o:(SVR_Q::get_Q(int, int) const (._omp_fn.0)) in archive /usr/lib/libRNA.a
          >>> referenced 1 more times

          ld.lld: error: undefined symbol: GOMP_loop_nonmonotonic_guided_next
          >>> referenced by svm.cpp:2610 (../libsvm-3.31/svm.cpp:2610)
          >>>               svm.o:(svm_predict_values._omp_fn.0) in archive /usr/lib/libRNA.a
          >>> referenced by svm.cpp:2629 (../libsvm-3.31/svm.cpp:2629)
          >>>               svm.o:(svm_predict_values._omp_fn.1) in archive /usr/lib/libRNA.a
          >>> referenced by svm.cpp:1408 (../libsvm-3.31/svm.cpp:1408)
          >>>               svm.o:(SVR_Q::get_Q(int, int) const (._omp_fn.0)) in archive /usr/lib/libRNA.a
          >>> referenced 1 more times

          ld.lld: error: undefined symbol: GOMP_parallel
          >>> referenced by svm.cpp:2610 (../libsvm-3.31/svm.cpp:2610)
          >>>               svm.o:(svm_predict_values) in archive /usr/lib/libRNA.a
          >>> referenced by svm.cpp:2629 (../libsvm-3.31/svm.cpp:2629)
          >>>               svm.o:(svm_predict_values) in archive /usr/lib/libRNA.a
          >>> referenced by svm.cpp:1408 (../libsvm-3.31/svm.cpp:1408)
          >>>               svm.o:(SVR_Q::get_Q(int, int) const) in archive /usr/lib/libRNA.a
          >>> referenced 1 more times
          collect2: error: ld returned 1 exit status
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
It's been a while since this issue has been filed, but I believe that adding `-lgomp` to the `RNAlib2.pc` file is not the correct way to solve this issue here.

Correct me if I'm wrong, but the reason is that each compiler comes with its own adjustments whenever OpenMP code has to be compiled and/or linked. For that, one usually passes a special flag to the compiler, e.g. `-fopenmp`, and it will include the required headers and link against the required libraries. So, the `-lgomp` linking is not stated explicitly anywhere but implicitly done by `gcc` or `g++`. One even has to add a different library if one deviates from GNU compilers. 

So, in the end, the proper way is to add the `-fopenmp` or whatever option to the linker flags. This is what is currently been done in the `RNAlib2.pc` file anyway. When compiling/linking with gcc or clang, it should then automatically add the required libraries to link against.

**Comment by dodomorandi** [comment]
I agree that the behavior of `-fopenmp` potentially implies linking different openmp libraries (for instance, with GCC it's `libgomp`, with clang it's `libomp`), but this also means that the content of the `libs` section of the `.pc` file should reflect the _linking intent_ of the library, `libRNA2` in this case.

When compiling with other than C compilers (like Rust for instance), it is not possible to use `-fopenmp` (which is a GCC/Clang parameter), and at the same time it is not possible to know which openmp library was the one detected during `RNAlib2` configuration. At that point every project that does not use a C/C++ compiler at linking phase should just "guess" which omp library should be used.

You can see that other projects like [ImageMagick](https://github.com/ImageMagick/ImageMagick/blob/main/configure.ac#L1266-L1316) or [igraph](https://github.com/igraph/igraph/blob/863aa2a34e62c75a62723836b6e7460e2c72637b/etc/cmake/pkgconfig_helpers.cmake#L65) puts the openmp libs in the pkg-config as I suggested (even if my proposal is wrong because it's not right to put `-lgomp`, as you also said).

It is totally not trivial as I asserted beforehand, but I still think that this should be dealt from the library that actively uses OpenMP and not from the downstream binaries/dependencies. To support this, I made a test:

- I hardcoded a `-lgomp` linking parameter in a Rust project that links to `RNAlib2`. Everything compiles fine.
- I recompiled ViennaRNA using Clang. In this way `libomp` is used instead.
- I try to recompile the Rust project, which now fails because the `libomp` symbols are not found.

This obviously happens just because I am unable to use `-fopenmp` because I am not using a C/C++ compiler and I _just_ need the correct list of libraries to link with.

**Comment by RaumZeit** [comment]
After thinking a lot about this issue, I agree that is makes sense to put the compile-time OpenMP libs of RNAlib into the .pc file!

The required changes have already been implemented in our development branch and will be made public with the next release (v2.7.0) which is about to come soon...

I believe that I can close this issue for now. If the new version doesn't solve the problem, please feel free to re-open!
