### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by onkarnath89** [ViennaRNA/ViennaRNA#22]
I tried installing the software on my local system as I need to generate secondary structure of many RNAs. I am installing from source code provided on developers webpage because this github repository do not contain configuration file.
I am working on a centos6 system. The program compiled successfully but make command produces an error
"make: *** No targets specified and no makefile found.  Stop."
Kindly Suggest

**Comment by RaumZeit** [comment]
Hi,
please follow the installation steps provided at https://www.tbi.univie.ac.at/RNA/documentation.html#install or https://github.com/ViennaRNA/ViennaRNA/blob/master/INSTALL
This should resolve your problems!
