### ISSUE TITLE
Disable warnings

### ISSUE THREAD

**Issue by wholtz** [ViennaRNA/ViennaRNA#220]
I'd like to disable some (or all) of the warning messages.  I tried this:

```python
import warnings
warnings.filterwarnings("ignore")
```

But it doesn't work, likely because this package wraps C code that doesn't make use of python's warnings.

**Comment by RaumZeit** [comment]
That's correct! All warnings are generated from within C code and usually printed to the `stderr` stream. Currently, there is no way to disable warnings.

**Comment by RaumZeit** [comment]
The next release (v2.7.0) implements a C logging mechanism, so warnings, errors, etc. can then be re-routed to whatever output you require or even be disabled.

**Comment by RaumZeit** [comment]
Fixed with v2.7.0!
See also: https://viennarna.readthedocs.io/en/latest/examples/python.html#logging

**Comment by wholtz** [comment]
Thanks for adding the example as well -- very helpful!
