### ISSUE TITLE
[Bug]: Python installation documented incorrectly

### ISSUE THREAD

**Issue by olive004** [ViennaRNA/ViennaRNA#221]
### What happened?

[Ubuntu 22.04 Python 3.10 install]

According to the README on setting up ViennaRNA with python, it should be possible to clone the repo and then run the `./configure` to set up sdist / wheels, but the files that are indicated in the instructions are missing from the repo? For example setup.py and pyproject.toml, which are only in the repo in the `.in` format. 

I tried converting those files by removing the `.in`, but upon running `python -m build`, this resulted in a file not found error, saying that `config.h` is missing. Running the `./configure.ac` file also returns errors.

Nothing too fancy going on here, just following the first steps to installing the package seems misleading. Not sure if I am perhaps missing a step on the way. Below are the instructions from the README that I am referring to:

# Python interface only
The Python 3 interface for the ViennaRNA Package library is [available at PyPI](https://pypi.org/project/ViennaRNA) and can be installed independently using Python's pip:

python -m pip install viennarna
Building a Python 3 sdist or wheel package
Our source tree allows for building/installing the Python 3 interface separately. For that, we provide the necessary packaging files pyproject.toml, setup.cfg, setup.py and MANIFEST.in.

These files are created by our autoconf toolchain after a run of ./configure. Particular default compile-time features may be (de-)activated by setting the corresponding boolean flags in setup.cfg. See below for additional steps when building the Python interface from a clean git clone.

Running

python -m build
will then create a source distribution (sdist) and a binary package (wheel) in the dist/ directory. These files can be easily installed via Python's pip.

Howto prepare the Python 3 sdist/wheel build from git repository
If you are about to create the Python interface from a fresh clone of our git repository, you require additional steps after running ./configure as described above. In particular, some autogenerated static files that are compiled into RNAlib must be generated. To do so, run

cd src/ViennaRNA/static
make
cd ../../..
Additionally, if building the reference manual is not explicitly turned off, the Python interface requires docstrings to be generated. They are taken from the doxygen xml output which can be created by

cd doc
make refman-html
cd ..
Finally, the swig wrapper must be build using

cd interfaces/Python
make RNA/RNA.py
cd ../..

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Does the problem occur with one of our executable program or the C-library?

Python 3 interface

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
Dear @olive004 ,

there is an important step in the documentation you have been missing to follow. Since you cloned the git repo and did not use the official source tarball, you need to prepare the entire autoconf/automake toolchain first:

https://github.com/ViennaRNA/ViennaRNA?tab=readme-ov-file#install-from-git-repository

After that, everything you already tried should run as expected.

**Comment by marcom** [comment]
I think you need libtool installed for it to work, on Ubuntu it's `sudo apt install libtool`.

**Comment by RaumZeit** [comment]
the note by @marcom is correct, it seems you are missing some further build tools that are not mentioned in the install instructions. Since you are using Ubuntu, they should be easy to install. Just run:
```
sudo apt-get install build-essential autoconf automake libtool pkg-config
```
I hope this will solve your problems.

Best,
Ronny

**Comment by RaumZeit** [comment]
closing the issue now. Updates have been made for the install section of the reference manual
