### ISSUE TITLE
[Help]: unable to install on WSL (Ubuntu & Debian) due to missing (?) laplack

### ISSUE THREAD

**Issue by baerbeli** [ViennaRNA/ViennaRNA#222]
### What happened?

I tried installing ViennaRNA on my Windows 10 (10.0.19045) WSL1 Ubuntu 22.04 but without success. I'm not very familiar with Linux so I might be doing something completely wrong, but I thought I'd ask here anyways.

What I did:

1. Install Ubuntu 22.04 in WSL
2. `sudo apt update`
3. `sudo apt upgrade`
4. `wget https://www.tbi.univie.ac.at/RNA/download/ubuntu/ubuntu_22_04/viennarna_2.6.4-1_amd64.deb`
5. `sudo dpkg -i viennarna_2.6.4-1_amd64.deb`
output:
`Selecting previously unselected package viennarna.
(Reading database ... 24210 files and directories currently installed.)
Preparing to unpack viennarna_2.6.4-1_amd64.deb ...
Unpacking viennarna (2.6.4-1) ...
dpkg: dependency problems prevent configuration of viennarna:
 viennarna depends on libgomp1 (>= 6); however:
  Package libgomp1 is not installed.
 viennarna depends on libgsl27 (>= 2.7.1); however:
  Package libgsl27 is not installed.
 viennarna depends on liblapack; however:
  Package liblapack is not installed.
 viennarna depends on liblapacke; however:
  Package liblapacke is not installed.
 viennarna depends on liblapack3 | liblapack.so.3; however:
  Package liblapack3 is not installed.
  Package liblapack.so.3 is not installed.

dpkg: error processing package viennarna (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.10.2-1) ...
Errors were encountered while processing:
 viennarna`

6. `sudo apt --fix-broken install` -> remove viennarna because not fully installed

7. `sudo apt install libgomp1`

8. `sudo apt install libgsl27` -> actually installs libgsl27, libgslcblas0

9. `sudo apt install liblapack` -> fails with output:
`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package liblapack`

10. `sudo apt install liblapacke` -> actually installs libblas3, libgfortran5, liblapack3, liblapacke, libquadmath0, libtmglib3

11. `sudo apt install liblapack.so.3` fails with output:
`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package liblapack.so.3 is a virtual package provided by:
  libopenblas0-serial 0.3.20+ds-1
  libopenblas0-pthread 0.3.20+ds-1
  libopenblas0-openmp 0.3.20+ds-1
  libatlas3-base 3.10.3-12ubuntu1
  liblapack3 3.10.0-2ubuntu1
You should explicitly select one to install.

E: Package 'liblapack.so.3' has no installation candidate`

12. as liblapack3 is already installed, I don't do anything further

13. `sudo dpkg -i viennarna_2.6.4-1_amd64.deb` (just to try if it works now) -> same error as before ("Package liblapack is not installed").

I actually also tried this in Debian on WSL but with the exact same problem that it can't seem to find liblapack.

I hope this isn't a super stupid question and would be very happy if someone can help!

Cheers

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
Hi,

that's strange, since you mentioned that `liblapack3` is already installed. So, the dependency should be resolved, as `liblapack3` should also provide `liblapack`...

Have you already tried using `apt` to install the package to automatically resolve all dependencies?:

```
sudo apt install ./viennarna_2.6.4-1_amd64.deb
```

**Comment by RaumZeit** [comment]
closing this issue for now, due to lack of correspondence since April. Please feel free to re-open if the problem persists...
