### ISSUE TITLE
Modified Bases not work

### ISSUE THREAD

**Issue by oldliyoungli** [ViennaRNA/ViennaRNA#227]
### Contact Details

956299168@qq.com

### What happened?

"I have installed ViennaRNA on Linux, and I have some custom energy parameters. I created a JSON file and put it into the misc folder. However, even after I changed the values in the JSON file, the free energy numbers of the sequences remain unchanged. What could be the reason?"

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Does the problem occur with one of our executable program or the C-library?

Executable Programs (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joh16** [comment]
Did you run `make` command ([install from git repository](https://github.com/ViennaRNA/ViennaRNA?tab=readme-ov-file#install-from-git-repository) in readme) after creating your json file?

I might be wrong but it seems like the json file or the type of modified bases are somehow hardcoded into executable program, so if you just downloaded the tarball then it won't include it. You might also have to modify below and possibly a couple more files as well.
- `misc/Makefile.am`
- `src/ViennaRNA/constraints/sc_cb_mod_wrappers.c`
- `src/ViennaRNA/constraints/soft_special.h`
- `src/bin/modified_bases_helpers.c`

I'm planning to contribute to support modified RNA base N1-methylpseudouridine via [this branch](https://github.com/joh16/ViennaRNA/tree/m1psi-parameters) of my fork and successfully ran the test on my local MacOS environment. I searched for pseudouridine within repository and tried best to follow it, so some of the changes I made on this branch may not be required to make it work.

**Comment by RaumZeit** [comment]
Hi,

generally, you don't need to compile the parameters into the programs. Just creating the JSON input file is sufficient. However, then the programs won't support the additional modified bases without providing the corresponding JSON file at each function call.

So, in essence, if you have the JSON file at hand, just use the `--mod-file` and `--modifications` parameters to the executable calls, e.g.

```
RNAfold --mod-file=myparams.json --modifications=B
```

if your parameters are in file `myparams.json` and the one-letter code for the modifications is `B`.

On the other hand, @joh16 is correct, that you need to adjust several other files within the source code directory to get the parameters compiled in to the programs. A good starting point might be to look at the recent PR of @joh16 (https://github.com/ViennaRNA/ViennaRNA/pull/229). However, I don't guarantee that this will work, need to check the PR more thorougly first...

I hope this gets you proceed with your parameter file!
