### ISSUE TITLE
[Bug]: blas and gfortran have to be linked manually to lapack during compilation (problem solved)

### ISSUE THREAD

**Issue by ArnaudStigliani** [ViennaRNA/ViennaRNA#230]
### What happened?

Dear developers,

I have encountered an error during the compilation of the source. Here, I share the problem and how to resolve it as maybe it can help the development of the library.
   
The program had to be compiled from source as It had to be  installed locally (on a Redhat 8.9 server)
On my system, the lapack library is installed outside of the "normal" library locations (which may be the reason of the issue ?)  

So I added the flags:  
`LDFLAGS="-L/home/fzh976/fzh976/programs/lapack/build/lapack/lib64/ -llapack`.  
when running the configure script.

When compiling (running make), I got this error:  
```
/path/to/lapack/liblapack.a(dlalsd.f.o): In function `dlalsd_':
dlalsd.f:(.text+0x721): undefined reference to `idamax_'
```
 
And dozens of other lines about undefined reference functions from the BLAS library (located in /usr/lib64).   
The program was successfully compiled after running the configure file with the right ldflags:  
`LDFLAGS="-L/path/to/lapack/ -llapack -L/usr/lib64 -lblas -lgfortran" ./configure --prefix=$PWD/build`  

(I also had to add the -lgfortran flag because of some other undefined references from the gfortran library)

I hope it helps.

Best,
Arnaud

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Does the problem occur with one of our executable program or the C-library?

C-Library

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
Thank you for the solution in this setup. I'm closing this issue now, since it seems resolved...
I'll also check, whether your solution can be added to the FAQ section of the reference manual.
