### ISSUE TITLE
RNAalifold feature request

### ISSUE THREAD

**Issue by dincarnato** [ViennaRNA/ViennaRNA#232]
Hello ViennaRNA team,

I would like to ask for the addition of a feature to RNAalifold.
Particularly, when passing SHAPE reactivity data for different sequences in the alignment, it is possible that these might have been generated using different SHAPE compounds. As a result, the slope/intercept parameters needed might differ for each sequence.

Would it be possible to pass RNAalifold different slope/intercept pairs for each sequence?

Many thanks.
All the best,
Danny

**Comment by RaumZeit** [comment]
Dear Danny,

thanks for this feature request! In fact, this feature is something that is already worked on in our development branch. If everything goes well, it will be included in the next release.
