### ISSUE TITLE
[Help] Can Perl API access PF pair probabilities after pseudouridine corrections?

### ISSUE THREAD

**Issue by ericb888** [ViennaRNA/ViennaRNA#235]
### Contact Details

eric.bennett@pfizer.com

### What happened?

First, thanks very much for all the new modified base parameters in v2.6.

To apply pseudouridine corrections in perl, I can do the following successfully and see a different MFE than if not applying the corrections:
```
my $seq="CAAGAAGCCCGCTTTTTTACTGCGCATAGCCCCGATTAAA"; # example dummy sequence
my $md = new RNA::md();
my $fc = new RNA::fold_compound($seq,$md);

my @modification_sites= (13,14,15,16,17,18,21,27,36,37);
$fc->sc_mod_pseudouridine(\@modification_sites);

(my $ss, my $mfe) = $fc->mfe();
$fc->pf;
```

However, with the above method of computing the partition function ($fc->pf) it is not obvious how to access the individual pair probabilities.  To access those, the Perl interface provides the get_pr function.  However, that function doesn't work (it seg faults) when the only partition function calculation that is called is $fc->pf.  I believe that for get_pr to work, it is necessary to call:

```
my $G = RNA::pf_fold($seq);
my $pair_prob=RNA::get_pr($i,$j);

```
Written this way, get_pr returns valid numbers, but from what I can tell, the pseudouridine corrections are not applied as the probabilities are always the same regardless of calling $fc->sc_mod_pseudouridine or not.

Is it possible to get both the partition function probabilities **_and_** the pseudouridine correction simultaneously from the Perl API?  (Or, maybe more simply, is there a way to get the probabilities from a fold_compound object and not use get_pr?)  

There is $fc->plist_from_probs but in Perl this seems to return an array of hashes that are all empty.

Thanks,
Eric

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Does the problem occur with one of our executable program or the C-library?

Perl 5 Interface

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
After applying modified base energy corrections, and subsequent partition function computations, the base pair probabilities are already those observed for the ensemble with modified bases.
After calling
```.pl
($pp, $dG) = $fc->pf()
```
You should be able to call the `$fc->bpp()` method, which yields a reference to a 1-based array of arrays with the actual base pair probabilities. Here is a small example that might be of help:
```.pl
use RNA;

my $seq1 = "CGCAGGGAUACCCGCG";

# create new fold_compound object
my $fc = new RNA::fold_compound($seq1);

# compute minimum free energy (mfe) and corresponding structure
my ($ss, $mfe) = $fc->mfe();

# print output
printf "%s [ %6.2f ]\n", $ss, $mfe;

$fc->exp_params_rescale($mfe);
my ($pp, $dG) = $fc->pf();

my $bpp = $fc->bpp();

my $n = length($seq1);

for (my $i = 1; $i < $n; $i++) {
  for (my $j = $i + 1; $j <= $n; $j++) {
    printf("bpp[%d,%d] = %g\n", $i, $j, $bpp->[$i][$j]) if ($bpp->[$i][$j] > 0);
  }
}
```

**Comment by RaumZeit** [comment]
yet another note: your call to `RNA::pf_fold()` will not include any model settings than the default, which doesn't include any modified bases. Modified base support is only supported for the object oriented API use, i.e. the methods bound to `RNA::fold_compound`. In the above example, all changes from the default in the `$md` data structure will be included during the predictions. Also, modified base support or constraints applied to the `$fc` object will be incorporated during the predictions, as long as they have been applied before the call of the `->mfe()` or `->pf()` methods.

I hope this is of help!

**Comment by RaumZeit** [comment]
closing this issue now, feel free to re-open if needed!
