### ISSUE TITLE
The installation of viennarna via conda bioconda was successful, but the error ViennaRNA / RNAlib not found was reported.[Bug]: 

### ISSUE THREAD

**Issue by 404-xianjin** [ViennaRNA/ViennaRNA#236]
### Contact Details

********************

### What happened?

I have successfully installed viennarna via conda bioconda and I can see the installed packages via conda list viennarna, but when I run the programme I get the error ViennaRNA / RNAlib not found

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Does the problem occur with one of our executable program or the C-library?

Python 3 interface

### Relevant log output

![image](https://github.com/ViennaRNA/ViennaRNA/assets/47860060/e72c04aa-4d24-46e0-8806-7309ddb48f9b)
![image](https://github.com/ViennaRNA/ViennaRNA/assets/47860060/b4d36112-11f4-49ce-8344-163ee132580f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 404-xianjin** [comment]
I am very sorry to say that I have resolved the issue.
My environment:
Operating system: Linux Centos7 2009
Virtual Environment: Conda
python version: 3.12
The solution is as follows:
```
(DnaChisel) [user@localhost DNAScheduler.Quartz]$ RNAfold --version
RNAfold 2.6.4
(DnaChisel) [user@localhost DNAScheduler.Quartz]$ echo $PYTHONPATH

(DnaChisel) [user@localhost DNAScheduler.Quartz]$ echo $LD_LIBRARY_PATH

(DnaChisel) [user@localhost DNAScheduler.Quartz]$ export PYTHONPATH=/home/user/anaconda3/envs/DnaChisel/lib/python3.12:/home/user/ anaconda3/envs/DnaChisel/lib/python3. 12/lib-dynload:/home/user/anaconda3/envs/DnaChisel/lib/python3.12/site-packages:/home/user/. local/lib/python3.12/site-packages
(DnaChisel) [user@localhost DNAScheduler.Quartz]$ echo $PYTHONPATH
/home/user/anaconda3/envs/DnaChisel/lib/python3.12:/home/user/anaconda3/envs/DnaChisel/lib/python3.12/lib-dynload:/home/user/anaconda3/envs/DnaChisel/lib/python3.12/site-packages [user@localhost DNAScheduler.Quartz]$ echo $PYTHONPATH anaconda3/envs/DnaChisel/lib/python3.12/site-packages:/home/user/.local/lib/python3.12/site-packages
(DnaChisel) [user@localhost DNAScheduler.Quartz]$ export LD_LIBRARY_PATH=/home/user/anaconda3/envs/DnaChisel/lib
(DnaChisel) [user@localhost DNAScheduler.Quartz]$ echo $LD_LIBRARY_PATH
/home/user/anaconda3/envs/DnaChisel/lib
```
thanks~

**Comment by RaumZeit** [comment]
seems resolved! closing the issue now....
