### ISSUE TITLE
[Bug]: Calling modifications (`sc_mod`) multiple times in Python

### ISSUE THREAD

**Issue by Cauch-BS** [ViennaRNA/ViennaRNA#240]
### Contact Details

cauchybs@snu.ac.kr

### What happened?

Calling `pseudouridine` modifications (by `sc_mod_pseudouridine`) within the Python 3 Interface multiple times seem to result in adding the energy difference multiple times in the same location. That is if the `.sc_mod_pseudouridine(1)` method was called on an instance of `RNA.fold_compound(seq)` two times, it appears that the difference betwen the `P(Ψ)` and the `U` base energy parameter would be added two times. 

The expected behavior when calling a modification at the same location more than once would be for the difference in parameters to be added `1` time, regardless of how many times the modification is called. 

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Does the problem occur with one of our executable program or the C-library?

Python 3 interface

### Relevant log output

Input
```
new_seq = 'AGAUUCACAGCAUCU'
fc = RNA.fold_compound(new_seq)
for i in range(10):
    print(f"Running for the {i}th time...")
    fc.sc_mod_pseudouridine([i + 1 for i, c in enumerate(new_seq) if c == 'U'])
    print(fc.pf()[1])
```
Expected Output:

```
Running for the 0th time...
-0.8373912572860718
Running for the 1th time...
-0.8373912572860718
Running for the 2th time...
-0.8373912572860718
Running for the 3th time...
-0.8373912572860718
Running for the 4th time...
-0.8373912572860718
Running for the 5th time...
-0.8373912572860718
Running for the 6th time...
-0.8373912572860718
Running for the 7th time...
-0.8373912572860718
Running for the 8th time...
-0.8373912572860718
Running for the 9th time...
-0.8373912572860718
```
Actual Output
```
Running for the 0th time...
-0.8373912572860718
Running for the 1th time...
-1.7871496677398682
Running for the 2th time...
-2.895747423171997
Running for the 3th time...
-4.046694278717041
Running for the 4th time...
-5.219062805175781
Running for the 5th time...
-6.417247295379639
Running for the 6th time...
-7.652768611907959
Running for the 7th time...
-8.938056945800781
Running for the 8th time...
-10.280405044555664
Running for the 9th time...
-11.677642822265625
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
Hi,
thanks for your bug report!

We are aware of the fact that adding base modification energy corrections multiple time will add the corrections multiple times as well. Each call to the `sc_mod_*()` methods will introduce an additional layer of energy corrections as requested by the parameters of the modified base. To properly correct for multiple occurrences of the same modified base, a 1-based list of positions of the modified bases has to be passed to the `sc_mod_*()` methods! I'm sorry if the documentation doesn't clarify this enough!

However, the internal system that actually performs the correction can currently not be changed to identify whether a particular modified base has already been corrected for.
While I can imagine that for the modifications we directly support through the API we could in principle introduce such a sanity check, I fear it won't be possible for any data the user loads from files or text strings.

But I'll see that the documentation will be updated to include this limitation.

Best regards!
