### ISSUE TITLE
[Bug]: use of register in hash_utils.h is disallowed in C++17

### ISSUE THREAD

**Issue by s-will** [ViennaRNA/ViennaRNA#241]
### Contact Details

sebastian.will@polytechnique.edu

### What happened?

The use of storage class "register" in RNAlocmin/hash_util.h causes recent Clang compilers to fail (in gcc we get tons of warnings). "register" is disallowed in ISO C++17 and anyway should not have any positive effects. The issue can be fixed by removing all 'register' qualifiers in the header file.

I include a patch on bioconda-recipes for building the osx Conda packages.

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Does the problem occur with one of our executable program or the C-library?

Other

### Relevant log output

In file included from globals.h:10,
                 from globals.cpp:15:
hash_util.h: In member function ‘size_t hash_fncts::operator()(const Structure&) const’:
hash_util.h:82:19: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
   82 |   register short *k;        /* the key */
      |                   ^
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
Hi Sebastian,
thanks for the bug report!
In fact, we are aware of this issue and the patch that removes the `register` storage class specifier has already been applied to our development branch in December last year. However, it hasn't been released so far.

The next release is already in preparation and will include the fix as attached to this message...
[0001-Remove-register-storage-class-from-hash_utils.h.txt](https://github.com/user-attachments/files/16309032/0001-Remove-register-storage-class-from-hash_utils.h.txt)

I'll close the issue for now, but please feel free to re-open if required.
Cheers!
