### ISSUE TITLE
[Bug]: compiling against swig 4.2.0

### ISSUE THREAD

**Issue by pgrt** [ViennaRNA/ViennaRNA#243]
### What happened?

Hello,

I am one of the maintainers of ViennaRNA in Debian.

I tries to build your latest release against swig 4.2.0 (which is in Debian) and I met an error, which I would fix with the attached patch.

[swig_4.2.0.txt](https://github.com/user-attachments/files/16388601/swig_4.2.0.txt)

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Does the problem occur with one of our executable program or the C-library?

Other

### Relevant log output

/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -std=c++17 -DHAVE_CONFIG_H -I. -I../..  -I/usr/include/python3.12 -DVRNA_WITH_NAVIEW_LAYOUT  -I../../src  -Wdate-time -D_FORTIF     Y_SOURCE=2 -fno-strict-aliasing -fopenmp -pthread -Wno-unused-label -Wno-unused-variable -I/usr/include/json-c/ -I/usr/include/libsvm/ -c -o _RNA_la-RNA_wrap.lo `test -f 'RNA_wrap.cpp     ' || echo './'`RNA_wrap.cpp
cp `test -f RNA.py || echo './'`RNA.py RNA/RNA.py
libtool: compile:  g++ -std=c++17 -DHAVE_CONFIG_H -I. -I../.. -I/usr/include/python3.12 -DVRNA_WITH_NAVIEW_LAYOUT -I../../src -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -fop     enmp -pthread -Wno-unused-label -Wno-unused-variable -I/usr/include/json-c/ -I/usr/include/libsvm/ -c RNA_wrap.cpp  -fPIC -DPIC -o .libs/_RNA_la-RNA_wrap.o
RNA_wrap.cpp: In function ‘int Swig_var_symbolset_set(PyObject*)’:
RNA_wrap.cpp:72257:24: error: ‘SWIG_Python_str_AsChar’ was not declared in this scope; did you mean ‘SWIG_Python_str_FromChar’?
72257 |     symbolset = strdup(SWIG_Python_str_AsChar(_val));
            |                                         ^~~~~~~~~~~~~~~~~~~~~~ 
            |                                         SWIG_Python_str_FromChar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
Hi,
we are aware of this issue! Unfortunately, the fix has not found its way to the official release just yet.
For archlinux you can also already find a similar patch (https://aur.archlinux.org/packages/viennarna)

We'll see that we release the next version with this fix as soon as possible.

Best,
Ronny

**Comment by RaumZeit** [comment]
Fixed with version 2.7.0
