### ISSUE TITLE
[Bug]: STRMEME has no arguments notrim

### ISSUE THREAD

**Issue by wangyb97** [ViennaRNA/ViennaRNA#245]
### Contact Details

liye466493@gmail.com

### What happened?

A bug happened!
When I used: streme -notrim -verbosity 1 -oc . -p pos.fa -n neg.fa -pvt 0.01 -minw 6 -maxw 7
I got the error: streme: unrecognized option '-notrim'
But I found the option in the tutorial of [MEME suite](https://meme-suite.org/meme/meme_5.5.3/doc/streme.html?man_type=web):
--notrim  Do not trim the control sequences even if their average length exceeds that of the primary sequences.

### Version

2.6.x (Default)

### Which operating system are you using?

Linux (Default)

### Relevant log output

streme: unrecognized option '-notrim'

Usage: streme [options] --p <primary sequences>

   Options:
     --p <filename>            primary (positive) sequence file name (required)
     --n <filename>            control (negative) sequence file name;
                               default: if --n is not given, then STREME
                               creates control sequences by shuffling each of
                               the primary sequences preserving the positions
                               of non-core characters and k-mer frequencies
                               (see --order, below; ignored if --objfun cd given)
     --order <m>               estimates an m-order background model for scoring
                               sites and uses an m-order shuffle if creating
                               control sequences from primary sequences;
                               default: 2 (DNA), 2 (RNA), 0 (Protein), 0 (custom)
     --kmer <m>                [deprecated: use --order instead]
     --bfile <bfile>           use the background model contained in bfile instead
                               of creating it from the control sequences;
                               default: see --order
     --objfun de|cd            objective function to optimize in motif discovery
                                 de : Differential Enrichment
                                 cd : Central Distance
                               default: de
     --o <output_dir>          output directory; default: 'streme_out'
     --oc <output_dir>         allow overwriting; default: 'streme_out'
     --text                    output text only; overrides --o and --oc;
                               default: create text, HTML, TSV and XML files in <output_dir>
     --dna                     sequences use standard DNA alphabet (default)
     --rna                     sequences use standard RNA alphabet
     --protein                 sequences use standard protein alphabet
     --alph <alph_file>        sequences use alphabet defined in <alph_file>;
                               converts to uppercase unless both cases in core
     --minw <minwidth>         minimum width for motifs (must be >= 3); 
                               default: 8
     --maxw <maxwidth>         maximum width for motifs (must be <= 30);
                               default: 15
     --w <w>                   sets <minwidth> and <maxwidth> to <w> (must be <= 30);
                               default: see --minw and --maxw
     --neval <neval>           evaluate <neval> seeds of each width;
                               default: 25
     --nref <nref>             refine <nref> evaluated seeds of each width;
                               nref==0 means just evaluate single best seed;
                               default: 4
     --niter <niter>           iterate refinement at most <niter> times per seed;
                               default: 20
     --thresh <thresh>         significance threshold for reporting enriched motifs;
                               default: p-value= 0.05 (0.05 if --evalue given)
     --evalue                  use p-value significance threshold; default: p-value
     --patience <patience>     quit after <patience> consecutive motifs exceed <thresh>;
                               default: 3
     --nmotifs <nmotifs>       stop if <nmotifs> motifs have been output;
                               overrides --thresh if > 0;
                               default: quit when new motif significance exceeds <thresh>
     --time <t>                quit before <t> CPU seconds consumed;
                               default: no time limit
     --totallength <len>       truncate each sequence set to length <len>;
                               default: 0 (do not truncate)
     --hofract <hofract>       fraction of sequences in hold-out set;
                               default: 0.1
     --seed <seed>             random seed for shuffling sequences;
                               default: 0
     --align left|center|right align sequences left/center/right for site
                               positional distribution plots; default: center
     --desc <desc>             include this description text in HTML
     --dfile <dfile>           include contents of this description file in HTML,
                               overrides --desc
     --help                    print this message and exit
     --version                 print the program version and exit
     --verbosity 1|2|3|4|5     level of diagnostic output (default: 2)
                               1: none 2: helpful 3: debug 4: tons 5: ludicrous

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyhtyao** [comment]
Hi, it doesn't seem to be related to ViennaRNA

**Comment by RaumZeit** [comment]
This is not a ViennaRNA but a [MEME](https://github.com/cinquin/MEME/issues) related error
