### ISSUE TITLE
[Bug]: ~/Software/RNAFramework/rf-fold -m 1 -g -md 50 -w -pk  -ko 10 -pw 160 -po 37 -wt 30 -fw 300 -fo 30 rf-norm/FSE.xml -o rf-fold2 -ow

### ISSUE THREAD

**Issue by wangguiqian** [ViennaRNA/ViennaRNA#246]
### Contact Details

122049372@qq.vom

### What happened?

**this my command:**
~/Software/RNAFramework/rf-fold -m 1 -g -md 50 -w -pk  -ko 10 -pw 160 -po 37 -wt 30 -fw 300 -fo 30 rf-norm/FSE.xml -o rf-fold2 -ow

**The rf-norm/FSE.xml file to show:**
<?xml version="1.0" encoding="UTF-8"?>
<data combined="FALSE" maxmutrate="0.2" maxumut="0.05" norm="90% Winsorizing" offset="20" reactive="ACGT" remap="0" scoring="Siegfried" tool="rf-norm" win="20">
	<transcript id="FSE" length="178">
		<sequence>
			GGTTGTTGGCTGGCTAATGGCTGCACTTGTGACAGATCCATTATGCAAAGCACTGATATG
			GCTTATTTAAACGAGTACGGGGCTCTAGTGCAGCTCGACTAGAGCCCTGTAACGGTACTG
			ATACACAACATGTGTATCGTGCTTTTGACATCTACAACAAGGATGTTGCTTGTCTAGG
		</sequence>
		<reactivity>
			NaN,NaN,NaN,NaN,0.675,1.000,0.710,0.677,0.440,0.458,0.023,0.345,0.404,0.295,0.132,0.480,0.414,0.366,0.335,0.031,0.125,0.102,0.024,0.140,0.281,0.283,0.786,0.647,0.955,0.395,0.830,1.000,0.038,0.008,0.083,0.311,0.126,0.000,0.000,0.000,0.000,0.000,0.105,0.254,0.019,0.171,0.382,0.453,1.000,0.043,0.050,0.110,0.282,0.199,0.375,0.487,0.134,0.516,0.978,0.198,
			0.352,0.241,0.380,0.486,0.429,0.612,1.000,0.987,0.635,0.547,0.597,0.160,0.136,0.268,0.785,0.072,0.024,0.012,0.011,0.012,0.007,0.019,0.000,0.062,0.000,0.000,0.051,0.055,0.325,0.858,0.416,1.000,0.629,0.992,0.175,0.246,0.010,0.009,0.001,0.001,0.000,0.000,0.097,0.000,0.000,0.056,0.000,0.000,0.000,0.067,0.021,0.000,0.124,0.014,0.036,0.429,0.889,0.937,1.000,0.100,
			0.015,0.119,0.028,0.004,0.005,0.016,0.428,1.000,0.676,0.966,0.261,0.006,0.000,0.004,0.003,0.000,0.000,0.000,0.000,0.010,0.102,0.210,NaN,0.268,0.037,0.525,0.202,1.000,0.114,0.093,0.000,0.000,0.093,0.285,0.152,0.987,0.115,0.068,NaN,NaN,0.116,0.000,NaN,0.000,0.000,1.000,0.046,0.239,0.391,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
		</reactivity>
	</transcript>
</data>

But I used the comand to run ,then get the basic result:
![QQ_1724186060062](https://github.com/user-attachments/assets/41d8c409-e2d1-4f40-ae99-143470a103d2)

I thank the result is error .Please help for me .

### Version

2.6.x (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyhtyao** [comment]
Hi, It seems to be an issue of [RNAFramework](https://github.com/dincarnato/RNAFramework/issues) instead of ViennaRNA.

**Comment by RaumZeit** [comment]
> Hi, It seems to be an issue of [RNAFramework](https://github.com/dincarnato/RNAFramework/issues) instead of ViennaRNA.

I second that! This seems not related to ViennaRNA but to RNAFramework...
