### ISSUE TITLE
[Bug]: How can I predict the specific location of RNA virus pseudojunction (FSE) based on the known sequence?

### ISSUE THREAD

**Issue by wangguiqian** [ViennaRNA/ViennaRNA#247]
### Contact Details

122049372@qq.com

### What happened?

How can I predict the specific location of the pseudo junction (FSE) of RNA viruses based on known sequences?
I want to accurately determine the RNA structure of a RNA virus, PEDV, at the specific location of the pseudo junction (FSE). Can I predict it by only providing the RNA sequence of the specific region?
GGTTGTTGGCTGTCTAATGGCTGCACTTGTGACAGATCCATTATGCAAAGCACTGATATGGCTTATTTAAACGAGTACGGGGCTCTAGTGCAGCTCGACTAGAGCCCTGTAATGGTACTGATACACAACATGTGTATCGTGCTTTTGACATCTACAACAAGGATGTTGCTTGTCTAGG

### Version

2.6.x (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
Hi,
I don't believe that I or the ViennaRNA Package can answer this specific question (easily)! 
First of all, the majority of structure prediction algorithms in the ViennaRNA Package do not support pseudoknots! Ypou should probably aim for a pseudoknot-aware prediction software instead.
Second, you should decide on the structure prediction strategy, in particular whether you want to predict local or global structures.
Third, the problem you stated above is in addition a research question that you might want to answer yourself?!

This issue board is actually a platform to ask specific questions about the use of our tools and library...

I'm closing this issue for now, feel free to re-open if there are any more specific questions on your side!
