### ISSUE TITLE
Install error - bash: ./configure: No such file or directory

### ISSUE THREAD

**Issue by JosielFaleiros** [ViennaRNA/ViennaRNA#26]
I've git clonned this repository, and I'm trying to install it,
However, when I execute the `./configure` command on my terminal, inside the project folder, the following error appear:
```
$ ./configure

bash: ./configure: No such file or directory
```
I think that there should be a configure file that I am calling with this command, or am I wrong?
because I don't see such a configure file in the root directory of the project
I am using a Debian based Linux distribution
thanks in advance

**Comment by martin-mann** [comment]
When cloning the repo, you first have to run `autogen.sh` or eg in bash `source autogen.sh`, which will create the configure script from scratch...

**Comment by martin-mann** [comment]
@RaumZeit you might want to add respective information to README.md

**Comment by JosielFaleiros** [comment]
awesome!!! `source autogen.sh` did the work to generate the "missing" configure file.
@martin-mann 

Thanxs
