### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by JosielFaleiros** [ViennaRNA/ViennaRNA#27]
I see that there's listed in the readme all the available 'tools'/commands, but, I think that this software working would be better understand if an use example for each command was provided in the readme too, with input and output examples there, not just in the RNA-tutorial-2.4.4.pdf

just a suggestion.

**Comment by RaumZeit** [comment]
Examples and usage instructions are both contained in the man pages of the respective executable programs. Please have a look there. The README file merely describes what this source code package actually contains, not how the programs are supposed to be used.
