### ISSUE TITLE
RNAalifold --aln-stk output file append strategy

### ISSUE THREAD

**Issue by mmiladi** [ViennaRNA/ViennaRNA#28]
This is not a bug report, rather a subsidiary suggestion. RNAalifold with option `--aln-stk=prefix` appends the stockholm file into the currently available filename if exist. I find the appending strategy, instead of overwriting, a bit unique in the Vienna tools and a source of confusion (user fault for not reading the help details :-) ). Specially It's probably unnecessary, when a prefix is provided by the user. Overwriting strategy, once the prefix is provided, would alleviate the need for taking care of a manual removal of the results before rerunning RNAalifold.

**Comment by RaumZeit** [comment]
This strategy may seem odd, but was merely a fail-safe mechanism to prevent `RNAalifold` from brutally overwriting existing files. Also, `RNAalifold` itself appends output to the stockholm file with each record it 
processes.

Sure, we could change that behavior and truncate the file before actually starting to write any output into it, but that might break already existing applications where people rely on the append strategy.

For instance, calling `RNAalifold --aln-stk=prefix` multiple times with different input creates one single output file `prefix.stk`. On the other hand, starting with the next release, `RNAalifold` receives unlimited input file number capabilities, as `RNAfold` already has.

So, getting rid of the append strategy might be a good choice in one of the next releases that change the minor version number.

**Comment by mmiladi** [comment]
True. 
Muiltiple input alignments support would be nice!
Thanks for the info.
