### ISSUE TITLE
no support for python3 in bioconda package for Mac OS

### ISSUE THREAD

**Issue by ihwang** [ViennaRNA/ViennaRNA#29]
I downloaded ViennaRNA on a Linux machine through bioconda (since anaconda3 makes life impossibly easy) and have enjoyed using it very much. I'm now trying to use it on my Mac machine, and I also manage all my Python packages on my Mac using anaconda3. It seems that the bioconda [packages](https://anaconda.org/bioconda/viennarna/files) for Mac **contain only the Python bindings for Python 2.7, and not Python 3.6**, unlike the Linux packages which contain both under `viennarna-2.4.5/lib`. Is there a reason for this? I know that I could compile from source on my Mac, but it's much nicer to have all of my Python packages organized and managed through Anaconda.

**Comment by RaumZeit** [comment]
@ihwang The issue should be resolved now. The bioconda packages have been updated and are available for Python2 and Python3 now.
