### ISSUE TITLE
Issues with C++ compilation linking libRNA2

### ISSUE THREAD

**Issue by tt6746690** [ViennaRNA/ViennaRNA#32]
It seems that it is possible to link `libRNA2` properly with C/C++ program. However I could not get it working and keeps getting `undefined reference` erros

- installed with `/configure --prefix=$HOME/ViennaRNA --disable-lto --disable-openmp`
- `test.cpp` containing one of [helloworld](https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/helloworld.html) example
- `Makefile` as follows
```Makefile
CC = gcc
CCFLAGS = -g -Wall -pthread \
        -I$(HOME)/ViennaRNA/include
LDFLAGS = -L$(HOME)/ViennaRNA/lib -lRNA -fopenmp \
        -Wl,--verbose

all: test

test: test.o
        $(CC) $(CCFLAGS) $^ $(LDFLAGS) -o $@
%.o: %.cpp
        $(CC) -c $< $(CCFLAGS) -o $@
```
- `make all` yield following error
```sh
test.c:14: undefined reference to `vrna_init_rand'
test.c:16: undefined reference to `vrna_random_string'
test.c:18: undefined reference to `vrna_alloc'
...
collect2: error: ld returned 1 exit status
Makefile:10: recipe for target 'test' failed
```
- `symbol` seem to be inside `libRNA.a` 
```sh 
readelf -Ws libRNA.a | grep vrna_init_rand
60: 0000000000000590   166 FUNC    GLOBAL DEFAULT    1 vrna_init_rand
```
- linker seems to be able to find `libRNA.a` with `-Wl,--verbose` flag
```sh 
attempt to open ~/ViennaRNA/lib/libRNA.so failed
attempt to open ~/ViennaRNA/lib/libRNA.a succeeded
```

I just cannot get `helloworld` compiled. Would really appreciate the help

**Comment by RaumZeit** [comment]
That's strange! I just tried to reproduce your issue, but it seems to compile without problems using your Makefile and the `helloworld_mfe.c` example.
Can you confirm that `$(HOME)/ViennaRNA/include` and `$(HOME)/ViennaRNA/lib` contain the headers and `libRNA.a`, respectively?

**Comment by tt6746690** [comment]
```
# ls ~/ViennaRNA/include
drwxrwxr-x 3 mark mark 4096 Jun 15 15:50 .
drwxrwxr-x 6 mark mark 4096 Jun 15 15:49 ..
-rw-r--r-- 1 mark mark 1523 Jun 15 15:50 g2_FIG.h
-rw-r--r-- 1 mark mark 5910 Jun 15 15:50 g2.h
-rw-r--r-- 1 mark mark 4127 Jun 15 15:50 g2_PS.h
-rw-r--r-- 1 mark mark 1370 Jun 15 15:50 g2_X11.h
drwxrwxr-x 2 mark mark 4096 Jun 15 15:49 ViennaRNA
```

```
# ls ~/ViennaRNA/lib
drwxrwxr-x 4 mark mark     4096 Jun 15 15:51 .
drwxrwxr-x 6 mark mark     4096 Jun 15 15:49 ..
-rw-r--r-- 1 mark mark   634788 Jun 15 15:50 libg2.a
-rw-r--r-- 1 mark mark 10950688 Jun 15 15:49 libRNA.a
-rwxr-xr-x 1 mark mark      880 Jun 15 15:49 libRNA.la
drwxrwxr-x 2 mark mark     4096 Jun 15 15:51 pkgconfig
drwxrwxr-x 3 mark mark     4096 Jun 15 15:50 python2.7
```

**Comment by HWaymentSteele** [comment]
I have this same issue, any insights would be much appreciated!

**Comment by RaumZeit** [comment]
Sorry, I still can't reproduce your problem. Is your helloworld program C or C++ code? If it is the latter, might it be that you forgot to wrap the header file inclusion into
```c++
extern "C" {
#include <ViennaRNA/mfe.h
}
```
?

**Comment by s-will** [comment]
Hi @tt6746690,
@RaumZeit had the right intuition. This is a C vs. C++ issue, even if the problem is quite subtle: since your file ending is .cpp, gcc compiles your file as C++ code, which causes the linking problem. Linking works, if you rename the program to test.c (or follow Ronny's advice if you want c++ code)

Note that you also need to link the math lib, so add -lm to the linker options.

**Comment by tt6746690** [comment]
@RaumZeit  Thanks for the tip. Everything worked now after wrapping includes in `extern "C"`
