### ISSUE TITLE
bioconda not working in python 3.5 virtual environment

### ISSUE THREAD

**Issue by ihwang** [ViennaRNA/ViennaRNA#33]
Hi, thanks for the latest release on bioconda! It works perfectly on my Mac running python 3.6. However, I'm trying to debug something else and now I need to run python 3.5. I activated my virtual environment which runs python 3.5:
```
>> source activate py35
>> which python
/Users/ihwang/anaconda3/envs/py35/bin/python
```
and in that environment downloaded the viennarna bioconda package:
```
(py35) >> conda install -c bioconda viennarna
Solving environment: done

## Package Plan ##

  environment location: /Users/ihwang/anaconda3/envs/py35

  added / updated specs: 
    - viennarna


The following NEW packages will be INSTALLED:

    viennarna: 2.4.7-h470a237_4 bioconda

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
but now in the virtual environment when I try to import the ViennaRNA package using `import RNA` I get an `ImportError: No module named 'RNA'`. It still works perfectly in python 3.6 (after deactivating the virtual environment).

Any ideas why ViennaRNA isn't working in a python 3.5 virtual environment? Also, I'm running all this on my Mac.

**Comment by s-will** [comment]
Hi,
bioconda has upgraded to a new build process, which broke a lot of recipes.
It looks like, for the viennarna recipe, this also broke the new
functionality (to adapt to different python versions) .
I will try to fix this again.

In the meantime: it should work to install the previous build of the
viennarna conda package like
conda install viennarna=2.4.7=py35_3

**Comment by s-will** [comment]
Hi again @ihwang, I have build new conda packages. Chances are that this is plainly working again.

**Comment by ihwang** [comment]
Thank you! It works perfectly :)
