### ISSUE TITLE
RNAplfold couldn't generate _openen_bin

### ISSUE THREAD

**Issue by lcscs12345** [ViennaRNA/ViennaRNA#37]
Hi,

Thank you for maintaining ViennaRNA packages. RNAplfold v2.4.x seems to have problems generating _openen_bin. Not an issue for v.2.3.x

**Comment by RaumZeit** [comment]
Hi,
it seems that with version 2.4.x the output filename for binary opening energy data is not changed correctly. The data should be written properly into the file `plfold_lunp`, though.
I've just fixed this issue in our development source tree, and the `old` behavior will be restored with the next version.

Sorry for the inconvenience.

**Comment by RaumZeit** [comment]
Fixed with version `2.4.10`
