### ISSUE TITLE
Matching duplexfold structure to sequence

### ISSUE THREAD

**Issue by ihwang** [ViennaRNA/ViennaRNA#38]
I'm using ViennaRNA through Python to predict the structure from two sequences when only allowing inter-molecular base pairs, and I'm trying to understand the `RNA.duplexfold` function. I found the [test page](https://github.com/ViennaRNA/ViennaRNA/blob/master/tests/python/test-RNA.py) which showed the basics of how to use the function, e.g.

```
>> RNA.duplexfold('AGAGGGAGCTGACGGATGACGCCCCCGCGCCACGCCGC', 'TATGCACGTGGC').structure
>> '.((((((..((&.)).))))))'
```
as well as a lucky guess to get the energy of the structure

```
>>> RNA.duplexfold('AGAGGGAGCTGACGGATGACGCCCCCGCGCCACGCCGC', 'TATGCACGTGGC').energy
>> -11.300000190734863
```
This is great! But how do I match up bases in the sequence to the basepairs in the structure?

Thanks!

**Comment by RaumZeit** [comment]
Dear Irena,
sorry for the poor documentation of the Python interface.
The data structure returned by the `RNA.duplexfold()` call has four attributes:
```python
d = RNA.duplexfold('AGAGGGAGCTGACGGATGACGCCCCCGCGCCACGCCGC', 'TATGCACGTGGC')
d.structure
d.energy
d.i
d.j
```
where the latter two are the the last nucleotide of the first (`d.i`), and the first nucleotide of the second (`d.j`) strand. Unfortunately, there is no other output from this function yet, so one has to compute the actual subsequences of both strands from these two numbers and the dot-bracket structure.

**Comment by ihwang** [comment]
Got it, thanks!
