### ISSUE TITLE
[question] v2.4.9 bugfix changes PU computation ?

### ISSUE THREAD

**Issue by martin-mann** [ViennaRNA/ViennaRNA#39]
Hi @RaumZeit 
does the bugfix
```
Fix wrong application of base pair soft constraints in partition function computations
```
concern the (window-based) unpaired probability computation in the presence of SHAPE constraints? 

I guess so and hope I am wrong.. :pray:

**Comment by RaumZeit** [comment]
Hi @martin-mann 
This bugfix only relates to soft constraints for individual base pairs. Internally, the RNAlib provides separate soft-constraint storage containers for unpaired nucleotides, base pairs, and stacked pairs. SHAPE reactivities are usually incorporated according to the Deigan et al. 2009 method, thus the stacked pair storage is used. As for SHAPE data, only the Zarringhalam et al. 2012 method makes use of the base pair soft constraint container. So the answer to your question (and hopes and prayers) depends on the way SHAPE reactivities are converted to constraints in your application :)

**Comment by martin-mann** [comment]
Zarringhalam of course... since it explicitely incorporates unpairedness, which is useful for unpaired probabilities..  :see_no_evil: 

thanks for the quick answer!

**Comment by martin-mann** [comment]
btw: do you expect a big impact?

**Comment by RaumZeit** [comment]
too bad, sorry for that! The bugfix can be expected to severely change the predictions compared to those with the bug! After all, base pair constraints had been stored in the wrong order, thus contributions from SHAPE reactivity data applied with the Zarringhalam method were placed at bogus base pairs :(

**Comment by martin-mann** [comment]
huuhh... thanks for the details!

**Comment by mmiladi** [comment]
Hi @RaumZeit , Fixing bugs should always be appreciated, thanks for that :smiley: 

I have created a branch for tracking the versionings. 
https://github.com/BackofenLab/IntaRNA-benchmark-SHAPE/blob/sniff-vrna-changes/src/analysis_IntaSHAPE-U1-interaction-vRNA-2_4_8.ipynb
https://github.com/BackofenLab/IntaRNA-benchmark-SHAPE/blob/sniff-vrna-changes/src/analysis_IntaSHAPE-U1-interaction-vRNA-2_4_9.ipynb

It seem we have consistent results. Either our luck that the changes do not influence U1 case or they do not overall influence IntaRNA-SHAPE application with Z option :eyes: :smiley_cat:
