### ISSUE TITLE
MacOS Compiling Issues - Different sourced source code results

### ISSUE THREAD

**Issue by bretonics** [ViennaRNA/ViennaRNA#4]
The following results in two different scenarios for each source dependent on where the source code was obtained for Vienna 2.3.2: [TBI](http://www.tbi.univie.ac.at/RNA/#) or [GitHub](https://github.com/ViennaRNA/ViennaRNA).

I followed, and combined, the different installation instructions for compiling from source code on [GitHub](https://github.com/ViennaRNA/ViennaRNA/blob/master/INSTALL) and/or [TBI](http://www.tbi.univie.ac.at/RNA/documentation.html#install) and entered the **same command** below for both sources:

`./configure --disable-openmp --disable-dependency-tracking CFLAGS="-arch i386 -arch x86_64 -O2" CXXFLAGS="-arch i386 -arch x86_64 -O2" --enable-universal-binary`

Why? Cause notes for MacOS X users in the [INSTALL](https://github.com/ViennaRNA/ViennaRNA/blob/master/INSTALL) file in this repo reflects all parameters, except `--enable-universal-binary` which is reflected in the [TBI installation instructions](http://www.tbi.univie.ac.at/RNA/documentation.html#install). Also tried multiple combinations of this, and even without, and results are the same.

Below are some outputs that differ when doing the exact same things on the same macOS Sierra 10.12.2 computer. The only thing different is where the source code came from.

----

### Source Code Directly from TBI
1.  Get everything configured properly with the command above (note the interfaces ✔︎) and results in:

```
##############################################
# Files will be installed in the following  ##
# directories:                              ##
##############################################

  Executables:        /usr/local/bin
  Libraries:          /usr/local/lib
  Header files:       /usr/local/include
  Extra Data:         /usr/local/share
  Man pages:          /usr/local/share/man
  Documentation:      /usr/local/share/doc/ViennaRNA
    (HTML):           /usr/local/share/doc/ViennaRNA/html
    (PDF):            /usr/local/share/doc/ViennaRNA
  Perl5 Interface:    
    (binaries):       /usr/local/Library/Perl/5.18/darwin-thread-multi-2level
    (scripts):        /usr/local/Library/Perl/5.18
  Python2 Interface:  
    (binaries):       /usr/local/lib/python2.7/site-packages
    (scripts):        /usr/local/lib/python2.7/site-packages
  Python3 Interface:  
    (binaries):       /usr/local/lib/python3.5/site-packages
    (scripts):        /usr/local/lib/python3.5/site-packages
```
2. Followed with `make`, it breaks when making the Perl interfaces
```
Making all in Perl
....
...
..
1 warning and 8 errors generated.
make[3]: *** [_RNA_la-RNA_wrap.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Clearly it attempts to build the Perl interfaces, since it was configured properly to do so, but fails.

### Source Code Directly Cloned from GitHub
1. Have to do `sh autogen.sh` because there is no `./configure` file
2. Also configured with the command above but note the **missing** ❌ interfaces this time
```
##############################################
# Files will be installed in the following  ##
# directories:                              ##
##############################################

  Executables:        /usr/local/bin
  Libraries:          /usr/local/lib
  Header files:       /usr/local/include
  Extra Data:         /usr/local/share
  Man pages:          /usr/local/share/man
  Documentation:      Not to be installed
    (HTML):           
    (PDF):            
  Perl5 Interface:    Not to be installed
    (binaries):       
    (scripts):        
  Python2 Interface:  Not to be installed
    (binaries):       
    (scripts):        
  Python3 Interface:  Not to be installed
    (binaries):       
    (scripts):  
```
Must assume interfaces wouldn't be installed, but why? Shouldn't they be configured to be installed, just as they were using the TBI source code? Nothing was typed differently in `./configure ...`.

3. Followed with `make`, it breaks when making all in bin
```
Making all in bin
  GEN      RNAfold_cmdl.c
/bin/sh: gengetopt: command not found
make[3]: *** [RNAfold_cmdl.c] Error 127
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Another point where installs differ: It fails where source code from TBI succeeded. 

---
**I wonder what is the best `./configure` option to pass is then?** However, noticing that compiling errors differ between the two sources, makes me wonder if there is something different between these. Are they not the same source code? 

The only way I have been able to install this on a Mac is using the precompiled MacOS X installer.

What I would like is to use this GitHub repo as the source code for compiling, since I can just pull any changes and re-compile on all my machines.

**Comment by RaumZeit** [comment]
Sorry for the inconsistency between the install instructions at our official website and those in the INSTALL file. The recommended way is to use the ones we provide on our [website](http://www.tbi.univie.ac.at/RNA/documentation.html#macosx).
Have you tried this, i.e. just passing:
```
./configure --enable-universal-binary
```
without any additional options? I added this particular flag a while ago to replace the confusing build process in order to ease building from source on OS X. We use this flag for building the binary OS X packages on a MacBook Pro without experiencing any troubles.
However, I don't know the reason for why the configure process between the source we provide on our official website and those available here at github is different. I'll investigate this issue in the next week.

**Comment by bretonics** [comment]
Yes. When trying just:

    ./configure --enable-universal-binary

The results still differ between the sources. Maybe the full warnings and errors will help.



[github.txt](https://github.com/ViennaRNA/ViennaRNA/files/730375/github.txt)
[TBI.txt](https://github.com/ViennaRNA/ViennaRNA/files/730374/TBI.txt)

**Comment by RaumZeit** [comment]
Ok, thanks for the output. I immediately saw the differences:
1. You are missing some of of the developer programs that are required to build/create the sources
2. You need to extract the libsvm sources to actually build-in libsvm support.

The following programs are required for building from git-repo sources:

- `swig` - (for the scripting language wrappers) - _optional_
- `doxygen` - (to build the reference manual) - _optional_
- `latex` - (to build the PDF version of the reference manual) - _optional_
- `gengetopt` - (to create the command line parameter parsers) - _required_
- `yacc/bison` and possibly more for RNAforester source code - _optional_
- `help2man` for creating the manpages - _required_

The tarballs that we distribute through the official website already contain pre-build sources to allow users missing some of the tools they probably never use for themselves, for instance `help2man` or `gengetopt`.

Second, to obtain SVM support in RNALfold, you need to unpack src/libsvm-x.y.z.tar.gz and reconfigure.

**Comment by bretonics** [comment]
Ok, great, sorry I missed those dependencies. I didn't realize the tarball distributions included pre-built sources but git-repo didn't.

So I installed all the missing developer programs and unpacked the src/libsvm-x.y.z.tar.gz in the git-repo case. However, it still does not build on either. 

It did however change a few things
1. Interfaces configuration in git-repo case now show up
2. New errors in TBI source
```
Making all in doc
  DOC      dox
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./_formulas.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.

sh: dot: command not found
```
[TBI.txt](https://github.com/ViennaRNA/ViennaRNA/files/730816/TBI.txt)

3. Errors in git-repo source are in Python3 (using Python 3.6.0)

[github.txt](https://github.com/ViennaRNA/ViennaRNA/files/730819/github.txt)


Hope this helps, and thanks for helping.

**Comment by RaumZeit** [comment]
I see the problem is the last line in your output:
```
sh: dot: command not found
```
I think you are missing the dot program which should be part of the `graphviz` package. You can deactivate a rebuild of the reference manual by adding the `--without-doc` configure switch, although this should not be necessary. I'll see what needs to be changed in our Makefiles to take the corresponding actions if the `dot` program is missing.
Regarding your compilation problems of the Python2/3 module, I can only tell you that I am aware of this problem. For some reason this only happens on Mac OS X which includes <termios.h> that defines a symbol also present in our library. But I do not yet have any idea how to fix this issue other than changing the symbol in our library. Interestingly, I do not experience this issue when building the binary Mac OS X package on our MacBook Pro.

**Comment by bretonics** [comment]
I do have `dot`, not sure why that time I got that, but re-running it several times I don't get that error again. 

What I do keep getting is the same error at `make`:
```
Making all in Python3
  SWIG     RNA_wrap.cpp
../../src/ViennaRNA/data_structures.h:615: Warning 312: Nested union not currently supported (ignored).
../../src/ViennaRNA/dp_matrices.h:196: Warning 312: Nested union not currently supported (ignored).
../../src/ViennaRNA/dp_matrices.h:331: Warning 312: Nested union not currently supported (ignored).
./../RNA.i:217: Warning 302: Identifier 'duplexT' redefined (ignored),
../../src/ViennaRNA/data_structures.h:290: Warning 302: previous definition of 'duplexT'.
./../RNA.i:214: Warning 303: %extend defined for an undeclared class bondT.
../../src/ViennaRNA/fold_vars.h:73: Warning 454: Setting a pointer/reference variable may leak memory.
../../src/ViennaRNA/fold_vars.h:80: Warning 454: Setting a pointer/reference variable may leak memory.
../../src/ViennaRNA/fold_vars.h:88: Warning 454: Setting a pointer/reference variable may leak memory.
  CXX      _RNA_la-RNA_wrap.lo
In file included from RNA_wrap.cpp:3201:
In file included from ../../src/ViennaRNA/data_structures.h:161:
../../src/ViennaRNA/structured_domains.h:26:1: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
struct vrna_structured_domains_s {
^
In file included from RNA_wrap.cpp:3228:
../../src/ViennaRNA/part_func_co.h:113:10: error: expected member name or ';' after declaration specifiers
  double B0;    /**< @brief start concentration B */
  ~~~~~~ ^
/usr/include/sys/termios.h:291:12: note: expanded from macro 'B0'
#define B0      0
                ^
RNA_wrap.cpp:7493:110: error: expected ')'
 void my_get_concentrations(double FcAB, double FcAA, double FcBB, double FEA, double FEB, double A0, double B0, double *AB, double *AA, double *BB, double *A, double *B) {
                                                                                                             ^
/usr/include/sys/termios.h:291:12: note: expanded from macro 'B0'
#define B0      0
                ^
RNA_wrap.cpp:7493:28: note: to match this '('
 void my_get_concentrations(double FcAB, double FcAA, double FcBB, double FEA, double FEB, double A0, double B0, double *AB, double *AA, double *BB, double *A, double *B) {
                           ^
RNA_wrap.cpp:7501:6: error: use of undeclared identifier 'AB'
    *AB=temp->ABc;
     ^
RNA_wrap.cpp:7502:6: error: use of undeclared identifier 'AA'
    *AA=temp->AAc;
     ^
RNA_wrap.cpp:7503:6: error: use of undeclared identifier 'BB'
    *BB=temp->BBc;
     ^
RNA_wrap.cpp:7504:6: error: use of undeclared identifier 'A'
    *A=temp->Ac;
     ^
RNA_wrap.cpp:7505:5: error: indirection requires pointer operand ('int' invalid)
    *B=temp->Bc;
    ^~
RNA_wrap.cpp:45217:7: error: no matching function for call to 'my_get_concentrations'
      my_get_concentrations(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12);
      ^~~~~~~~~~~~~~~~~~~~~
RNA_wrap.cpp:7493:7: note: candidate function not viable: requires 7 arguments, but 12 were provided
 void my_get_concentrations(double FcAB, double FcAA, double FcBB, double FEA, double FEB, double A0, double B0, double *AB, double *AA, double *BB, double *A, double *B) {
      ^
1 warning and 8 errors generated.
make[3]: *** [_RNA_la-RNA_wrap.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I have confirmed that I have all dependencies installed: `swig`, `doxygen`, `latex`, `gengetopt`, `yacc/bison`, `help2man`, and` graphviz`. `src/libsvm-x.y.z.tar.gz` has also been unpacked.

**Comment by RaumZeit** [comment]
I am aware of the problem you described in your earlier post. This is an issue of the python includes in Mac OS X which for some reason depend on `termios.h`. This header file in turn defines a macro which clashes with a symbol in our library. There is no easy way to fix this for the current ViennaRNA Package but we have renamed the symbol in our library for the next release. Thus, compilation should work fine starting with ViennaRNA Package 2.3.4.
For now, the only fix is to deactivate the Python 3 wrapper at configure time.

**Comment by RaumZeit** [comment]
Version 2.3.4 is out which should fix your issue...

**Comment by bretonics** [comment]
Form GitHub repo: Now fails at `make`

```
....
....
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[4]: Nothing to be done for `all-am'.
Making all in bin
  GEN      RNAfold_cmdl.c
  CC       RNAfold_cmdl.o
  CC       RNAfold.o
  CCLD     RNAfold
Undefined symbols for architecture i386:
  "_json_append_member", referenced from:
      _vrna_file_json in libRNA_conv.a(file_formats.o)
  "_json_mknumber", referenced from:
      _vrna_file_json in libRNA_conv.a(file_formats.o)
  "_json_mkobject", referenced from:
      _vrna_file_json in libRNA_conv.a(file_formats.o)
  "_json_mkstring", referenced from:
      _vrna_file_json in libRNA_conv.a(file_formats.o)
  "_json_stringify", referenced from:
      _vrna_file_json in libRNA_conv.a(file_formats.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [RNAfold] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
