### ISSUE TITLE
Terminal Mismatch Internal Loop 

### ISSUE THREAD

**Issue by Jogala** [ViennaRNA/ViennaRNA#42]
Hi, 

rnaEval yields -0.8 for GCGAGAC&GUGCGGC and ((...((&))...))

But if I apply the rules of the turner library 2004 I get -1.2.

The difference stems from the symmetric 3x3 internal loop:
    
--------3 x 3-----
3' CG|GCG|UG
5' GC|GAG|AC

I calculate
dG = dG_terminal_mm_interiro_loop(GG)+dG_terminal_mm_interiro_loop(GG)+dG_AU_closure+dG_initiation_loop(3x3, n = 6)

= -1.2-1.2+0.7+2 = -0.3

The values can be found here:
https://rna.urmc.rochester.edu/NNDB/turner04/internal-parameters.html

But rnaEval estimates the costs for the 3x3 interior loop to be just 0.7, hence the difference of 0.4

Could you confirm that this as a bug or did I get something wrong in reading the values?

Best,

Joachim

**Comment by Jogala** [comment]
Thanks a lot. 

Ja it is really strange, tstacki.dat contains energy values for all kind of combinations for terminal mismatches, whereas the turner Homepage lists only 4 different values for "other size terminal mismatch". Also the .zip file that can be downloaded from the NNDB website does not contain the tstacki.dat. 

So it looks like the homepage is obsolete?

The correct tstacki.dat can be found [here](https://github.com/clotelab/RNAiFold/blob/master/RNAstructure/data_tables/tstacki.dh
), or?

They are the right people to contact regarding the discrepancy?

Thanks a lot for your help!

**Comment by RaumZeit** [comment]
The correct link to the RNAstructure Package is this: https://rna.urmc.rochester.edu/RNAstructure.html
An overview of the parameter files can be found here:  http://rna.urmc.rochester.edu/GUI/html/Appendix_of_Thermodynamic_File_Details.html

The Clote Lab is __not__ repsonsible for the energy parameters, but David Mathews Lab at Rochester (https://rna.urmc.rochester.edu/). His lab is using UV melting data from the Turner group to compile a complete set of nearest neighbor parameters for RNA secondary structure prediction.

Whether the NNDB or the energy parameter files are obsolete I can't tell. But this discrepancy surely needs some explanation.

Best,
Ronny

Btw.: In the latest version of RNAstructure (6.0.1) the parameter file in question was renamed to `rna.tstacki.dg`

**Comment by Jogala** [comment]
Thanks a lot again!

**Comment by Jogala** [comment]
@RaumZeit Hi Ronny, [the page](http://rna.urmc.rochester.edu/GUI/html/Appendix_of_Thermodynamic_File_Details.html) providing an overview over the parameters is outdated. Do you know where I can find a newer version? I did not find anything on the Mathews Lab Homepage.
