### ISSUE TITLE
[compiling v2.4.9] linking of RNAplex fails on cygwin

### ISSUE THREAD

**Issue by martin-mann** [ViennaRNA/ViennaRNA#43]
Hi @RaumZeit 

I just tried to compile v2.4.9 on my Cygwin system using the following configuration

```
./configure --without-doc --without-python --without-python3 \
--without-check --without-cluster --without-forester --without-json \
--without-svm --disable-unittests --without-kinwalker --without-tutorial \
--without-tutorial-pdf --without-rnalocmin --without-perl
```

which is working fine for v2.4.8. When compiling v2.4.9 I get this

```
  CCLD     RNAplex.exe
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
/cygdrive/c/cygwin64/bin/ld: ../../src/ViennaRNA/.libs/libRNA_conv.a(plex.o) (plex.o/ ): Section flag STYP_DSECT (0x1) ignored
/cygdrive/c/cygwin64/bin/ld: ../../src/ViennaRNA/.libs/libRNA_conv.a(plex.o) (plex.o/ ): Section flag STYP_COPY (0x10) ignored
make[3]: *** [Makefile:869: RNAplex.exe] Error 1
```

When [comparing 2.4.9 with 2.4.8](https://github.com/ViennaRNA/ViennaRNA/compare/v2.4.8...v2.4.9) I dont see any directly *plex* related changes... 

Any idea or how to find out what is wrong?

Thanks for help,
Martin

**Comment by martin-mann** [comment]
btw. I also get this warning (also for v2.4.8):
```
  CXXLD    libRNA.la
libtool: link: warning: undefined symbols not allowed in x86_64-unknown-cygwin shared libraries
```

**Comment by martin-mann** [comment]
setup
```
 --> gcc --version
gcc (GCC) 7.3.0

 --> ld --version
GNU ld (GNU Binutils) 2.29.1.20171006
```

**Comment by RaumZeit** [comment]
Hi,
the only time when I saw the linker crashing with core-dump before was with a 4.8.x/4.9.x GCC and LTO enabled.

It might be worth a try to compile with the `--disable-lto` option... Maybe GCC 7.3.0 has a similar problem in cygwin?

**Comment by martin-mann** [comment]
:+1:  did the trick... when thinking about it: disabled it in the past due to some problems for older version.

many thanks for the reminder and help!

best,
Martin
