### ISSUE TITLE
Matrice distance using ViennaRNA in Python

### ISSUE THREAD

**Issue by lemerleau** [ViennaRNA/ViennaRNA#44]
Hi, 
I am actually using ViennaRNA package in my RNA Evolution project in Python. I would like to know what is the corresponding python function of the ViennaRNA command: RNAdistance -Xm. Otherwise I would like to know if there is any python function of RNAlib that computes the matrice distance of RNA structure for a given list of RNA structures. 

Thank you in advance, I will be glad if you could help me.

**Comment by RaumZeit** [comment]
Hi,
there is no such library function available, neither in C nor in the Perl or Python interface.
However, you may construct your own function and use the low-level base pair distance function, e.g.:
```.py
s1="(((...)))"
s2="((..))..."
RNA.bp_distance(s1, s2)
```
I hope this is helping you to achieve your goal!
