### ISSUE TITLE
Calculate base pair probabilities in python

### ISSUE THREAD

**Issue by Giulio-Q** [ViennaRNA/ViennaRNA#46]
Hello,
I would like to perform a base pair probability computation on RNA according the helloworld example but I am having difficulty in finding the functions relevant to Python for this calculation.
Specifically, how do I retrieve the BP probabilities in python using a similar approach as C below.
  vrna_ep_t *ptr, *pair_probabilities = NULL;
  float     en = vrna_pf_fold(seq, propensity, &pair_probabilities);
So far, I am able to call pf_fold such as:
RNA.pf_fold(seq)
['((((....))))', -5.507421970367432]
But I am unable to obtain the BP probabilities.
Any suggestions would be appreciated!

**Comment by RaumZeit** [comment]
Hi,
unfortunately, there is no dedicated Python reference manual for RNAlib available yet. But many of the C-functions that are available in the scripting language interfaces have an additional description in the C reference manual to explain how they behave in Perl or Python. Anyway, you can obtain the base pair probabilities in two different ways, similar to a corresponding C-code.
**1. Make use of the global variable that contains the base pair probability**
```{python}
(propensity,ensemble_energy) = RNA.pf_fold(seq)
for i in range(1, len(seq)):
    for j in range(i + 1, len(seq) + 1):
        print "pr(%d,%d) = %g" % (i, j, RNA.get_pr(i, j))
```
Note, that this approach is not threadsafe since it uses a single global array where entries can be obtained via `RNA.get_pr(i, j)`.

**2. Make use of the object-oriented interface and the corresponding methods**
```{python}
fc = RNA.fold_compound(seq)
(propensity, ensemble_energy) = fc.pf()
basepair_probs = fc.bpp()
for i in range(1, len(basepair_probs)):
    for j in range(i+1,len(basepair_probs[i])+1):
        print "pr(%d,%d) = %g" % (i, j, basepair_probs[i][j])
```

**Comment by Giulio-Q** [comment]
Thank you. The second method works.

**Comment by huzaifahassan** [comment]
Hi,

I am trying to get the colors of 'color by base-pairing probability'  from [RNAfold webserver](http://rna.tbi.univie.ac.at//cgi-bin/RNAWebSuite/RNAfold.cgi?PAGE=3&ID=fsIGfRybZr&r=6) in the command-line version of RNAfold as a text file or something similar. I could not find anything in the [ViennaRNA Tutorial](https://www.tbi.univie.ac.at/RNA/tutorial/#sec1)

![image](https://user-images.githubusercontent.com/25290167/61964210-f3b01500-af92-11e9-9788-3c08fcd7d968.png)

I want something like:
G Red
G Red
G Red
C Red
U Red
A Red
U Orange.

I saw that it's possible to get [base pair probability matrix in python](https://github.com/ViennaRNA/ViennaRNA/issues/46)

Is there any way I can get something similar to 'color by base-pairing probability' from [RNAfold web server](http://rna.tbi.univie.ac.at//cgi-bin/RNAWebSuite/RNAfold.cgi?PAGE=3&ID=fsIGfRybZr&r=6) in the command line or python.

Thanks.

**Comment by RaumZeit** [comment]
There is no such implementation available in the RNA library. However, once you have the base pair probabilities, you can apply your own color scheme. After all, the probabilities are values between 0 and 1 which makes interpolation of any color palette very easy.
Note, however, that in our webserver we color paired nucleotides by their corresponding base pair probability and unpaired bases by their probability to be unpaired, i.e. q(i) = 1 - sum_j p_ij.

Also, please open a new issue next time.

**Comment by hzuzu** [comment]
Thank you for your response.
I am sorry about replying to this thread, I will open a new issue next time.

I just wanted to know one more thing, how do you get the vector of values for the colors from the base pair probability matrix.

I have this vector
eg:
pr(1,2) = 0
pr(1,3) = 0
pr(1,4) = 0
pr(1,5) = 0
pr(1,6) = 0.000254751
pr(2,3) = 0
pr(2,4) = 0
pr(2,5) = 0
pr(2,6) = 5.91458e-05
pr(3,4) = 0
pr(3,5) = 0
pr(3,6) = 0
pr(4,5) = 0
pr(4,6) = 0
pr(5,6) = 0

How do I get one value for each base? Is this formula ( **q(i) = 1 - sum_j p_ij** ) applicable to the above probability matrix?

**Comment by RaumZeit** [comment]
The `p_ij` or `p(i, j)` values are the equilibrium probabilities for a base pair `(i,j)`. So to obtain the probability that nucleotide `i` is paired, one simply sums over all potential pairing partners `j`, thus
```
p(i) = sum_j p_ij
```
Then, `q(i) = 1 - p(i)` is simply the probability that nucleotide `i` is unpaired.

**Comment by syrinej** [comment]
hello @RaumZeit

i have an issue when trying to generate the colored graphical output of the secondary strcuture on my own. 
in fact, i'm parsing the dot.ps file for probability values but each nucleotide as mentioned has many base pair probabilities so when i try to sum them , they sometimes exceed 1. i thought maybe if im generating the mfe strcture plot i would need to only consider the base pairs that do appear in that structure( from the dot bracket notation) but i'm not sure about that ..and i would have to find a solution if i'm generating the other possible structures too..
do you have any recommendations please

thank you
