### ISSUE TITLE
Is a development version required for installation?

### ISSUE THREAD

**Issue by wrshoemaker** [ViennaRNA/ViennaRNA#5]
Hello,

I am trying to install ViennaRNA and am getting an error when I'm running the following configure command: 

`./configure --enable-macosx-installer --enable-universal-binary --without-perl --disable-openmp`

where the output says:

checking for Python2 libs... -lpython2.7 -ldl -framework CoreFoundation

checking for Python2 ldflags... -bundle -undefined dynamic_lookup

checking for directory to install Python2 scripts in... ${prefix}/lib/python2.7/site-packages

checking for directory to install architecture dependent python2 things in... 

${exec_prefix}/lib/python2.7/site-packages

checking for Python2 module extension... .so

checking consistency of all components of python development environment... no

configure: error: in `/Users/WRShoemaker/ViennaRNA-2.3.3':

configure: error:

  Could not link test program to Python2. Maybe the main Python2 library has been

  installed in some non-standard library path. If so, pass it to configure,

  via the LIBS environment variable.

  
Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
  

============================================================================
  
 ERROR!
  
 You probably have to install the development version of the Python package
  
 
for your distribution.  The exact name of this package varies among them.
  

============================================================================

I re-ran the code by specifying the Python library. That seemed reasonable since I use conda to manage packages, but that didn't work. Is there some development version of a Python package I need to get ViennaRNA to install?

**Comment by RaumZeit** [comment]
Hi,
indeed development versions for python, python3, and perl are required in order to successfully compile and link the corresponding scripting language wrappers!

Since you are using `conda`, I assume that your python installations reside somewhere in a special dedicated environment directory. Have you tried setting the `PYTHON2_CONFIG` environment variable directly such that it points to the `python-config` tool of your conda environment?
E.g.:
```
./configure PYTHON2_CONFIG=/path/to/conda/environment/python-config
```
