### ISSUE TITLE
Discrepancy Flush Coaxial Stacking Energy

### ISSUE THREAD

**Issue by Jogala** [ViennaRNA/ViennaRNA#50]
Hi, 

I have a question regarding the flush coaxial stacking energy you are assigning. The result I get by using RNAeval differs from what I would expect according to the NNDB. I also went through the values provides by RNAstructure 6.0.1 (Feb 12, 2018) and could not find one that would explain the behavior.

Here is the example:

```
GGGGGGGGAAAAAACCCC        
....((((......))))           
```
yields dG(37) = -5.6

If I now place a second strand, just a monomer,
```
C&GGGGGGGGAAAAAACCCC
((&..))((((......))))
```
the result is dG(37) = -2.8

Now as a second strand is involved the penalty of 4.1 is payed, hence the difference in energy assigned to the flush coaxial stack is -2.8 -4.1 + 5.6 = -1.3

According to the NNDB:
https://rna.urmc.rochester.edu/NNDB/turner04/coax.html

> In flush coaxial stacking, the free energy and enthalpy changes of the coaxial stack are approximated using the helical nearest neighbor parameters (Watson-Crick or GU) as though there was no break in the backbone.

Hence I wonder why you are assigning -1.3kcal/mol. 

I checked out the energy values in the **data_tables** folder of the[ RNAstructure Source Code](http://rna.urmc.rochester.edu/RNAstructureDownload.html) using

grep -r "\-1\.3" ./rna.*dg

But going through those files did not yield any energy value that would fit he sequence context.

Best

Joachim

**Comment by RaumZeit** [comment]
Hi,
as far as I understand, the ViennaRNA Package doesn't exactly implement the coaxial stacking rules as outlined in the NNDB.
It only adds coaxial stacking contribution (with the `-d3` option) between adjacent helices in multibranch loops. I'll re-check this again, but am almost certain that this is why you couldn't relate the contributions from RNAeval to those taken from NNDB.

**Comment by Jogala** [comment]
Hm... Ok I understand that it is not using thr same values as the NNDB then. But why are you assigning  -1.3kcal/mol? What is the rule behind?

Best

Joachim

**Comment by RaumZeit** [comment]
The -1.3kcal/mol stem from the dangling end contribution of the 'G' (3rd nt in 2nd sequence) on top of the inter-molecular base pair 'CG' (1st nt of 1st sequence and 4th nt of 2nd sequence) at the beginning of your sequence/structure pair.
```
C&GGGGGGGGAAAAAACCCC
(&...)((((......))))
```
