### ISSUE TITLE
Output positional entropy only

### ISSUE THREAD

**Issue by Roleren** [ViennaRNA/ViennaRNA#51]
Hey, thanks for a nice package. I want to find the most structured region per transcript. So I want the raw positional entropy values as output, but I can't find a way to get them. Only as input for colouring plots etc, but that's not what I want. Is there a way to get the raw entropy values as one number per position ?

**Comment by RaumZeit** [comment]
Unfortunately, there is no implementation for the positional entropies in our offically released library so far.
However, I've just implemented it in our development branch, so it will become available in the next release. Until then, you might consider computing them yourself as

S(i) = - Sum_j p_ij log(p_ij) - q_i log(q_i)

where p_ij is the probability for base pair (i,j), and q_i = 1 - Sum_j p_ij is the probability that nucleotide i remains unpaired. (logarithms are at base 2)
Just on another note, the positional entropies themselves do not tell you something about the structuredness of a nucleotide (or region). They simply reflect the diversity of a nucleotides pairing behavior. That means a low entropy close to 0 tells you that the nucleotide is always unpaired, or paired with more or less the same partner. (You might already know that, I just wanted to be sure about that) ;)

**Comment by Roleren** [comment]
Okay, thanks. Yes, I know it's not the perfect marker for structure, my idea was that pairing should be correlated with structure. I already have another way, which is very slow. I run a sliding window of 39 bases and pick the window with the highest free energy as max structure in that transcript. But this takes forever for 100K transcripts. Therefore I would like a score, that tells for each position, what is likelihood of structure. how would you do this ?

**Comment by RaumZeit** [comment]
Thats a tough question and I assume that there are many ways to do that. You could also compute the pairing probabilties and simply compute the probability of a single nucleotide being paired

    p_i = Sum_j p_ij

While you would get a profile over your sequence, it would be quite difficult to actually extract a structured region from that, since you loose the information of the (most likely) paring partner of `i`.
Why don't you simply use `RNALfold` or `RNAplfold` for that. The first computes locally optimal structures within a sliding window, while the other does the same with base pair probabilities. Furthermore, `RNAplfold` provides a second algorithm that, in a sliding-window manner, computes the probability of a consecutive subsequence of length `u` to be unpaired. Both programs allow you to specify the sliding-window size `L` and run quite fast, even if you have 100k transcripts. We regularly run those programs on entire genomes or transcriptomes

**Comment by Roleren** [comment]
Okey, good to know, I have not found all the treats in this package. Is there a sliding window function that gives free energy  ?

**Comment by RaumZeit** [comment]
You can find something similar with our implementation of the `RNALfold` algorithm. However, the algorithm will output the most stable secondary structure that is not fully included in a previously obtained structure of an overlapping window. Also, the algorithm performs the sliding-window approach from the 3' to the 5' side, and the obtained structures do not necessarily span an entire window length.
You may have a look at the [man page of the `RNALfold` program](https://www.tbi.univie.ac.at/RNA/RNALfold.1.html) and the corresponding publication [Prediction of locally stable RNA secondary structures for genome-wide surveys](https://academic.oup.com/bioinformatics/article/20/2/186/204808) and [RNALfoldz: efficient prediction of thermodynamically stable, local secondary structures](https://www.tbi.univie.ac.at/newpapers/pdfs/TBI-p-2010-4.pdf).
The RNAlib and the corresponding Python interface provide the
```.py
RNA.Lfold()
RNA.Lfoldz()
RNA.Lfold_cb()
RNA.Lfoldz_cb()
```
functions, and the `fold_compound` methods
```.py
fc = RNA.fold_compound(seq, None, RNA.OPTION_MFE | RNA.OPTION_WINDOW)

fc.mfe_window_cb()
fc.mfe_window_score_cb()
```
I realize that the above Python interface is poorly documented at the moment, but the reference manual of the C-library should provide some insight. You may also want to have a look at the file `test-RNA-mfe-window.py` in the `tests/python/` directory of the ViennaRNA Package source code tarball.

**Comment by Roleren** [comment]
Thank you very much, I will check if we can use this function, but I fear it will not do the same thing.  Since I want all the values for all transcripts. 1 value per position-window per leader. I will see if I have time to maybe code it myself :)

**Comment by RaumZeit** [comment]
OK, happy coding then! :)
You may also want to have a look at the `RNAplfold` program and the corresponding library functions
to compute sliding-window based base pair probabilities and probabilties for segment of length `ulength` to be unpaired. In Python, this is
```.py
RNA.pfl_fold(sequence, window_size, max_bp_span, cutoff)
RNA.pfl_fold_cb(sequence, window_size, max_bp_span, callback, data)
RNA.pfl_fold_up(sequence, ulength, window_size, max_bp_span)
RNA.pfl_fold_up_cb(sequence, ulength, window_size, max_bp_span, callback, data)
```
which correspond to the C-functions `vrna_pfl_fold()`, `vrna_pfl_fold_cb()`, `vrna_pfl_fold_up()`, and `vrna_pfl_fold_up_cb()` respectively (see also https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/group__part__func__window.html)

Also, the fold_compound objects in python have an associated method:
```.py
fc.probs_window()
```
that corresponds to `vrna_probs_window()`

I'll close the issue for now, feel free to open a new one or re-open this if required.
Cheers,
Ronny
