### ISSUE TITLE
can not install th package

### ISSUE THREAD

**Issue by jhonbgjmch** [ViennaRNA/ViennaRNA#53]
ubuntu@ubuntu-VirtualBox:~/Desktop/ViennaRNA-2.4.12$ make install
Making install in src
make[1]: Entering directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src'
Making install in ViennaRNA
make[2]: Entering directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA'
Making install in static
make[3]: Entering directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA/static'
make  install-am
make[4]: Entering directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA/static'
make[5]: Entering directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA/static'
make[5]: Nothing to be done for 'install-exec-am'.
make[5]: Nothing to be done for 'install-data-am'.
make[5]: Leaving directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA/static'
make[4]: Leaving directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA/static'
make[3]: Leaving directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA/static'
make[3]: Entering directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA'
make[4]: Entering directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   libRNA.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libRNA.lai /usr/local/lib/libRNA.la
/usr/bin/install: cannot remove '/usr/local/lib/libRNA.la': Permission denied
Makefile:1177: recipe for target 'install-libLTLIBRARIES' failed
make[4]: *** [install-libLTLIBRARIES] Error 1
make[4]: Leaving directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA'
Makefile:2087: recipe for target 'install-am' failed
make[3]: *** [install-am] Error 2
make[3]: Leaving directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA'
Makefile:1926: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src/ViennaRNA'
Makefile:522: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/Desktop/ViennaRNA-2.4.12/src'
Makefile:667: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by RaumZeit** [comment]
Apparently, your user has no permissions to install to `/usr/local/`. Either install into the users home directory, or use
```
sudo make install
```
instead.
See also https://github.com/ViennaRNA/ViennaRNA#installation
