### ISSUE TITLE
Python3 bridge not compiled with swig-4

### ISSUE THREAD

**Issue by brobr** [ViennaRNA/ViennaRNA#54]
Hi,

When testing ViennaRNA build scripts for Slackware linux (published at [https://slackbuilds.org/repository/14.2/academic/ViennaRNA](url)) to upgrade to 2.4.12 from 2.4.11, compiling halts at the stage of building the bridge to python 3. The crash only happens on the development version (Slackware-current) with, since earlier this month, gcc-9.1 and swig-4.0.0. It does not happens with the python 2 module, nor with python 3 when -current was still at swig version 3.0.12 or on the stable version, Slackware-14.2 with swig-3.0.7; gcc-5.5.

The error (see [compile-error.txt](https://github.com/ViennaRNA/ViennaRNA/files/3169570/compile-error.txt)) is this:
 >File "/tmp/SBo/ViennaRNA-2.4.12/interfaces/Python3/RNA/\_\_init\_\_.py", line 13, in <module>
    from . import _RNA
ImportError: cannot import name '\_RNA' from 'RNA' (/tmp/SBo/ViennaRNA-2.4.12/interfaces/Python3/RNA/\_\_init\_\_.py

The major difference seems to be the differently named .so file in case of python-3 (`_RNA.cpython-37m-x86_64-linux-gnu.so`) vs python 2 (_RNA.so)? (see attached interfaces files, generated by `$ ls /tmp/SBo/ViennaRNA-2.4.11/interfaces/Python[3]/*RNA*`
[interfaces-py2.txt](https://github.com/ViennaRNA/ViennaRNA/files/3169571/interfaces-py2.txt)
[interfaces-py3.txt](https://github.com/ViennaRNA/ViennaRNA/files/3169572/interfaces-py3.txt)

The produced \_\_init\_\_.py files for swig-3 or -4 are identical for both python 2 and 3 but very different from each other
[__init__py-swig3.txt](https://github.com/ViennaRNA/ViennaRNA/files/3169584/__init__py-swig3.txt)
[__init__py-swig4.txt](https://github.com/ViennaRNA/ViennaRNA/files/3169585/__init__py-swig4.txt)

I wonder whether this relates to this issue raised on the swig-github:https://github.com/swig/swig/issues/1486?  If so, could you make a change in the code (or tell me how I can patch which source file) to allow compilation on swig4 to finish? (Slackware-current is heavily used by people with more modern hardware and comes standard with python3 to which we all have to migrate soon).

Thanks,

Rob

EDIT:

Downgrading to swig-3.0.12 from swig-4.0.0 results in building the python3 bridge without a problem on Slackware-current

**Comment by RaumZeit** [comment]
Hi Rob,

I've just reproduced the problem with SWIG 4.0 on ArchLinux.

After various attempts I think I've found the solution that works both with SWIG 3.0 and 4.0. Apparently, the update from version 3 to 4 in swig changed a lot in the way the python interfaces is loaded...

Until we've release the next version that fixes this bug, you may want to try the following patch:
```
diff --git a/interfaces/Python/Makefile.am b/interfaces/Python/Makefile.am
index df279501..41be4c08 100644
--- a/interfaces/Python/Makefile.am
+++ b/interfaces/Python/Makefile.am
@@ -16,9 +16,8 @@ INTERFACE_FILES = $(SWIG_src) \
                   $(LANG_SPECIFIC_INTERFACE_FILES)
 
 pkgpy2execdir = $(py2execdir)/RNA
-pkgpy2cmoddir = $(py2execdir)
 
-pkgpy2cmod_LTLIBRARIES = _RNA.la
+pkgpy2exec_LTLIBRARIES = _RNA.la
 pkgpy2exec_DATA = RNA/__init__.py
 
 _RNA_la_SOURCES = $(INTERFACE_FILES) \
@@ -87,27 +86,33 @@ RNA/__init__.py: $(SWIG_module_name).py
 	$(AM_V_GEN)( test -d RNA || $(MKDIR_P) RNA ) && \
   cp `test -f RNA.py || echo '$(srcdir)/'`RNA.py RNA/__init__.py
 
-_RNA$(PYTHON2_SO): _RNA.la
-	$(AM_V_GEN)( $(LIBTOOL) --config > libtoolconfig.tmp ) && \
-  ( . ./libtoolconfig.tmp; cp $$objdir/_RNA$(PYTHON2_SO) . ) && \
+RNA/_RNA$(PYTHON2_SO): _RNA.la
+	$(AM_V_GEN)( test -d RNA || $(MKDIR_P) RNA ) && \
+  ( $(LIBTOOL) --config > libtoolconfig.tmp ) && \
+  ( . ./libtoolconfig.tmp; cp $$objdir/_RNA$(PYTHON2_SO) RNA ) && \
   rm -f libtoolconfig.tmp
 
-all-local:  _RNA$(PYTHON2_SO)
+CLEANFILES = \
+    RNA/_RNA$(PYTHON2_SO) \
+    RNA/__init__.py \
+    RNA/__init__.pyc
+
+all-local:  RNA/_RNA$(PYTHON2_SO)
 
 clean-local:
-	-rm -rf RNA _RNA$(PYTHON2_SO)
+	-rm -rf RNA
 
 # Remove the .la file - RNA.la is never linked against (it's a module)
 # and Python doesn't use libltdl.  Note that the library gets installed by
 # install-data, so that's where we need to hook.
 install-data-hook:
-	rm -f $(DESTDIR)$(pkgpy2cmoddir)/_RNA.la
+	rm -f $(DESTDIR)$(pkgpy2execdir)/_RNA.la
 
 # Because we don't install the .la file, "make uninstall" doesn't work and
 # we need to remove the file ourselves.
 uninstall-local:
-	eval `grep '^dlname=' $(pkgpy2cmod_LTLIBRARIES)` ; \
-	rm -f $(DESTDIR)$(pkgpy2cmoddir)/"$$dlname"
+	eval `grep '^dlname=' $(pkgpy2exec_LTLIBRARIES)` ; \
+	rm -f $(DESTDIR)$(pkgpy2execdir)/"$$dlname"
 
 ## remove all generated content
 maintainer-clean-local:
diff --git a/interfaces/Python3/Makefile.am b/interfaces/Python3/Makefile.am
index de9b049e..67824a99 100644
--- a/interfaces/Python3/Makefile.am
+++ b/interfaces/Python3/Makefile.am
@@ -17,10 +17,9 @@ INTERFACE_FILES = $(SWIG_src) \
                   $(LANG_SPECIFIC_INTERFACE_FILES)
 
 pkgpyexecdir = $(py3execdir)/RNA
-pkgpycmoddir = $(py3execdir)
 pkgpycachedir = $(pkgpyexecdir)/__pycache__
 
-pkgpycmod_LTLIBRARIES = _RNA.la
+pkgpyexec_LTLIBRARIES = _RNA.la
 pkgpyexec_DATA =  RNA/__init__.py
 pkgpycache_DATA = RNA/__pycache__/__init__.@PYTHON3_CACHE_TAG@.pyc \
                   RNA/__pycache__/__init__.@PYTHON3_CACHE_OPT1_EXT@
@@ -91,42 +90,43 @@ RNA/__init__.py: $(SWIG_module_name).py
 
 # We "import _RNA" first so that if we fail to import the glue library
 # we don't generate a broken .pyc or .pyo.
-RNA/__pycache__/__init__.@PYTHON3_CACHE_TAG@.pyc: RNA/__init__.py _RNA$(PYTHON3_SO)
+RNA/__pycache__/__init__.@PYTHON3_CACHE_TAG@.pyc: RNA/__init__.py RNA/_RNA$(PYTHON3_SO)
 	$(AM_V_GEN)( PYTHONPATH="RNA:$$PYTHONPATH" $(PYTHON3) -c "import _RNA" ; \
   PYTHONPATH=".:$$PYTHONPATH" $(PYTHON3) -c "import RNA" )
 
-RNA/__pycache__/__init__.@PYTHON3_CACHE_OPT1_EXT@: RNA/__init__.py _RNA$(PYTHON3_SO)
+RNA/__pycache__/__init__.@PYTHON3_CACHE_OPT1_EXT@: RNA/__init__.py RNA/_RNA$(PYTHON3_SO)
 	$(AM_V_GEN)( PYTHONPATH="RNA:$$PYTHONPATH" $(PYTHON3) -O -c "import _RNA" ; \
   PYTHONPATH=".:$$PYTHONPATH" $(PYTHON3) -O -c "import RNA" )
 
-_RNA$(PYTHON3_SO): _RNA.la
-	$(AM_V_GEN)( $(LIBTOOL) --config > libtoolconfig.tmp ) && \
-  ( . ./libtoolconfig.tmp; cp $$objdir/_RNA$(PYTHON3_SO) . ) && \
+RNA/_RNA$(PYTHON3_SO): _RNA.la
+	$(AM_V_GEN)( test -d RNA || $(MKDIR_P) RNA ) && \
+  ( $(LIBTOOL) --config > libtoolconfig.tmp ) && \
+  ( . ./libtoolconfig.tmp; cp $$objdir/_RNA$(PYTHON3_SO) RNA ) && \
   rm -f libtoolconfig.tmp
 
 CLEANFILES = \
-    _RNA$(PYTHON3_SO) \
+    RNA/_RNA$(PYTHON3_SO) \
     RNA/__init__.py \
     RNA/__pycache__/__init__.@PYTHON3_CACHE_TAG@.pyc \
     RNA/__pycache__/__init__.@PYTHON3_CACHE_OPT1_EXT@\
     $(srcdir)/*.pyc
 
-all-local:  _RNA$(PYTHON3_SO)
+all-local:  RNA/_RNA$(PYTHON3_SO)
 
 clean-local:
-	-rm -rf RNA _RNA$(PYTHON3_SO)
+	-rm -rf RNA
 
 # Remove the .la file - RNA.la is never linked against (it's a module)
 # and Python doesn't use libltdl.  Note that the library gets installed by
 # install-data, so that's where we need to hook.
 install-data-hook:
-	rm -f $(DESTDIR)$(pkgpycmoddir)/_RNA.la
+	rm -f $(DESTDIR)$(pkgpyexecdir)/_RNA.la
 
 # Because we don't install the .la file, "make uninstall" doesn't work and
 # we need to remove the file ourselves.
 uninstall-local:
-	eval `grep '^dlname=' $(pkgpycmod_LTLIBRARIES)` ; \
-	rm -f $(DESTDIR)$(pkgpycmoddir)/"$$dlname"
+	eval `grep '^dlname=' $(pkgpyexec_LTLIBRARIES)` ; \
+	rm -f $(DESTDIR)$(pkgpyexecdir)/"$$dlname"
 
 ## remove all generated content
 maintainer-clean-local:
diff --git a/interfaces/RNA.i b/interfaces/RNA.i
index fb2260d6..6ae86641 100644
--- a/interfaces/RNA.i
+++ b/interfaces/RNA.i
@@ -1,4 +1,9 @@
+#ifdef SWIGPYTHON
+%module(moduleimport="from . import _RNA") RNA
+#else
 %module RNA
+#endif
+
 //%pragma(perl5)  modulecode="@EXPORT=qw(fold);"
 %pragma(perl5)  include="RNA.pod"
 
```

**Comment by brobr** [comment]
Fab; Thanks for the quick response, Ronny.

The patch works fine! Both on the stable version of Slackware with swig-3 and on current with swig-4, the program compiles now without a problem.

It only needed `autoreconf` after patching to get the local version of aclocal found.

Cheers,

Rob

**Comment by RaumZeit** [comment]
Perfect!
We are already in the process to prepare the next release which will have this patch applied...

I'm closing this issue for now.
