### ISSUE TITLE
Redirect RNAplfold output to different file or stdout?

### ISSUE THREAD

**Issue by budach** [ViennaRNA/ViennaRNA#59]
Hi,

I can't seem to figure out a way to save RNAplfold output to a specific file of choice or to redirect its output to stdout. Is this functionality not implemented?

By default, RNAplfold creates a postscript file that always has the same name. If I use the -o parameter it always creates a file called "plfold_basepairs" whose name I can't influence. This makes using RNAplfold in a parallel fashion not feasible.

Any tips are appreciated in case I overlooked something.

**Comment by RaumZeit** [comment]
Hi,
indeed, if the input is not in FASTA format, RNAplfold in default mode will always overwrite previous output files. However, if you provide input in FASTA format, i.e. a FASTA header plus sequence, RNAplfold will generate an ID from the first word of the FASTA header and use it as output file prefix.
For an input like instance
```
>nice_sequence
GAGUAGUGGAACCAGGCUAUGUUUGUGACUCGCAGACUAACAGUGGUGCCGUAGGGAAUCACGGGGCUGGCCGCCUGUUGUGAAAAAUUUUUACACUCGA
```
with the call
```
RNAplfold -o
```
will create output files `nice_sequence_basepairs`.
In case you have a lot of input sequences without FASTA headers, you might also want to check out the `--auto-id` option. This will instruct RNAplfold to automatically generate seuqence ids from a prefix and an increasing integer number. By default, the prefix is `sequence` and the numbers start at 1. (See also the `--id-prefix`, `--id-digits`, `--id-start`, and `--id-delim` parameters as described in the RNAplfold manpage: https://www.tbi.univie.ac.at/RNA/RNAplfold.1.html)

Thus, calling
```
RNAplfold --auto-id -o
```
with multiple sequence input will create output files `sequence_0001_basepairs`, `sequence_0002_basepairs`, etc...

I hope this solves you problem.

Best,
Ronny
