### ISSUE TITLE
trying to reproduce IDTDNA UNAfold Hairpin calculations

### ISSUE THREAD

**Issue by avilella** [ViennaRNA/ViennaRNA#62]
Hi all,

I've used Vienna RNA RNAfold in the past to try to calculate the hairpin formation of ssDNA, and I have another project where this is relevant now.

In this project, we are manually designing oligos via the IDTDNA OligoCalculator online tool, which has a 'Hairpin' option that is using UNAFold: https://eu.idtdna.com/calc/analyzer

I am trying to reproduce the values obtained in this manner with Vienna RNA, but I am failing to get anything remotely close between one and the other. For example, for a ssDNA molecule such as the one below, I get disparagingly different free energy values from -12 or -13 kcal/mol in RNAfold that are only around -5 or -5.8 in the IDT DNA Hairpin table.

Any ideas on how to reproduce the IDT DNA values in Vienna RNA? Should I be using RNAfold? Should I be using some other command? Should I be using the Matthews 1999 table? Should I be using the Matthews 2004 table?

See some values below:

Full Vienna RNAfold output at T=37:

$ RNAfold --MEA -d2 -p --noconv

Input string (upper or lower case); @ to quit
....,....1....,....2....,....3....,....4....,....5....,....6....,....7....,....8
CCACATGCAGAAGAATGCAGTTGAATCCTGATTTCATACCATATGCAAAATTCAACTGGA
length = 60

CCACATGCAGAAGAATGCAGTTGAATCCTGATTTCATACCATATGCAAAATTCAACTGGA
...(((........)))(((((((((..((....((((...))))))..)))))))))..
 minimum free energy = -10.40 kcal/mol
...,,,.,......,}}(((((((((..((..,.{{{,...,)}}))..)))))))))..
 free energy of ensemble = -11.93 kcal/mol
.................(((((((((..((....(((.....)))))..))))))))).. { -9.30 d=6.13}
.................(((((((((..((....(((.....)))))..))))))))).. { -9.30 MEA=48.97}
 frequency of mfe structure in ensemble 0.0841079; ensemble diversity 8.67  

$ RNAfold --MEA -d2 -p --noconv -T 25

Input string (upper or lower case); @ to quit
....,....1....,....2....,....3....,....4....,....5....,....6....,....7....,....8
CCACATGCAGAAGAATGCAGTTGAATCCTGATTTCATACCATATGCAAAATTCAACTGGA
length = 60

CCACATGCAGAAGAATGCAGTTGAATCCTGATTTCATACCATATGCAAAATTCAACTGGA
...(((........)))(((((((((..((....((((...))))))..)))))))))..
 minimum free energy = -15.28 kcal/mol
...{{(.,......}))(((((((((..((..,.{{{{...}))}))..)))))))))..
 free energy of ensemble = -16.24 kcal/mol
...(((........)))(((((((((..((....((((...))))))..))))))))).. {-15.28 d=5.39}
...(((........)))(((((((((..((....((((...))))))..))))))))).. {-15.28 MEA=50.86}
 frequency of mfe structure in ensemble 0.197978; ensemble diversity 7.96  

$ RNAfold --MEA -d2 -p --noconv -T 25 -P /usr/share/ViennaRNA/dna_mathews2004.par
WARNING: stacking enthalpies not symmetric
WARNING: stacking enthalpies not symmetric
WARNING: stacking enthalpies not symmetric
WARNING: stacking enthalpies not symmetric

Input string (upper or lower case); @ to quit
....,....1....,....2....,....3....,....4....,....5....,....6....,....7....,....8
CCACATGCAGAAGAATGCAGTTGAATCCTGATTTCATACCATATGCAAAATTCAACTGGA
length = 60

CCACATGCAGAAGAATGCAGTTGAATCCTGATTTCATACCATATGCAAAATTCAACTGGA
...(((.(....).)))(((((((((.....(((((((...)))).))))))))))))..
 minimum free energy = -12.45 kcal/mol
...(((.,....,.)))(((((((((.....(((((({...}))).))))))))))))..
 free energy of ensemble = -13.82 kcal/mol
...(((........)))(((((((((.....(((((((...)))).)))))))))))).. {-12.39 d=4.63}
...(((........)))(((((((((.....(((((((...)))).)))))))))))).. {-12.39 MEA=52.13}
 frequency of mfe structure in ensemble 0.0988196; ensemble diversity 6.65  

$ RNAfold --MEA -d2 -p --noconv -T 25 -P /usr/share/ViennaRNA/dna_mathews1999.par

Input string (upper or lower case); @ to quit
....,....1....,....2....,....3....,....4....,....5....,....6....,....7....,....8
CCACATGCAGAAGAATGCAGTTGAATCCTGATTTCATACCATATGCAAAATTCAACTGGA
length = 60

CCACATGCAGAAGAATGCAGTTGAATCCTGATTTCATACCATATGCAAAATTCAACTGGA
...(((.(....).)))(((((((((.....((((((.....))).))))))))))))..
 minimum free energy = -10.98 kcal/mol
...({{.{....,.}))(((((((((.....{{{(((,...,))).)}})))))))))..
 free energy of ensemble = -12.52 kcal/mol
...(((........)))(((((((((.....((((((.....))).)))))))))))).. {-10.67 d=5.54}
...(((........)))(((((((((.....((((((.....))).)))))))))))).. {-10.67 MEA=50.38}
 frequency of mfe structure in ensemble 0.0739069; ensemble diversity 7.42  

IDT DNA Hairpin at 25C
structure | Image | ΔG (kcal.mole-1)
-- | -- | --
1 |   | -5.81
2 |   | -5.35
3 |   | -4.86
4 |   | -4.8
5 |   | -4.73
6 |   | -2.96
7 |   | -2.94

IDT DNA Hairpin at 37C
structure | Image | ΔG (kcal.mole-1)
-- | -- | --
1 |   | -2.99
2 |   | -1.97

**Comment by avilella** [comment]
Partially answering myself: I tried the comparison for a few hundred molecules around 50-60bp, and it seems like the Vienna RNA RNAfold mfe value that correlates the most with the deltaG value in IDTDNA Unafold hairpin calculation is the one with the dna_mathews2004.par parameter file. Second best is dna_mathews1999.par, and almost uncorrelated is the default parameters in RNAfold.

**Comment by RaumZeit** [comment]
Unfortunately, I don't know which set of DNA parameters `UNAFold` is using nowadays.

However, I also just compared our predictions against those of the `RNAstructure` Webserver (https://rna.urmc.rochester.edu/RNAstructureWeb/Servers/efn2/efn2.html) and they match our predictions:
```
$ echo -en "CCACATGCAGAAGAATGCAGTTGAATCCTGATTTCATACCATATGCAAAATTCAACTGGA\n.................(((((((((.....(((((((...)))).))))))))))))..\n" | RNAeval -P ../../misc/dna_mathews2004.par -v
WARNING: stacking enthalpies not symmetric
WARNING: stacking enthalpies not symmetric
WARNING: stacking enthalpies not symmetric
WARNING: stacking enthalpies not symmetric
External loop                           :  -100
Interior loop ( 18, 58) CG; ( 19, 57) AU:  -150
Interior loop ( 19, 57) AU; ( 20, 56) GC:  -130
Interior loop ( 20, 56) GC; ( 21, 55) UA:  -140
Interior loop ( 21, 55) UA; ( 22, 54) UA:  -100
Interior loop ( 22, 54) UA; ( 23, 53) GC:  -150
Interior loop ( 23, 53) GC; ( 24, 52) AU:  -130
Interior loop ( 24, 52) AU; ( 25, 51) AU:  -100
Interior loop ( 25, 51) AU; ( 26, 50) UA:   -90
Interior loop ( 26, 50) UA; ( 32, 49) UA:   300
Interior loop ( 32, 49) UA; ( 33, 48) UA:  -100
Interior loop ( 33, 48) UA; ( 34, 47) UA:  -100
Interior loop ( 34, 47) UA; ( 35, 45) CG:   160
Interior loop ( 35, 45) CG; ( 36, 44) AU:  -150
Interior loop ( 36, 44) AU; ( 37, 43) UA:   -90
Interior loop ( 37, 43) UA; ( 38, 42) AU:   -60
Hairpin  loop ( 38, 42) AU              :   340
CCACAUGCAGAAGAAUGCAGUUGAAUCCUGAUUUCAUACCAUAUGCAAAAUUCAACUGGA
.................(((((((((.....(((((((...)))).)))))))))))).. ( -7.90)
```
vs. `efn2` of the `RNAstructure` Package:
```
$ efn2 dnatest.ct dnatest.txt --DNA -w
$ cat dnatest.txt
Thermodynamic details for structure # 1
	Exterior loop = -1.0
		Stack = -1.5  for stack of 18-58
		Stack = -1.3  for stack of 19-57
		Stack = -1.4  for stack of 20-56
		Stack = -1.0  for stack of 21-55
		Stack = -1.5  for stack of 22-54
		Stack = -1.3  for stack of 23-53
		Stack = -1.0  for stack of 24-52
		Stack = -0.9  for stack of 25-51
	Helix total = -9.9
	Internal/bulge = 3.0  for closure of 26-50	Size = 5
		Stack = -1.0  for stack of 32-49
		Stack = -1.0  for stack of 33-48
	Helix total = -2.0
	Internal/bulge = 1.6  for closure of 34-47	Size = 1 BP stack across bulge = -1.3
		Stack = -1.5  for stack of 35-45
		Stack = -0.9  for stack of 36-44
		Stack = -0.6  for stack of 37-43
	Helix total = -3.0
	Hairpin = 3.4  for closure of 38-42


	Total energy = -7.9
```
We use the RNA and DNA parameter files that are distributed along with `RNAstructure`. So the above results are no surprise. The only major difference is in slight simplifications of our Nearest Neighbor model implementation. For instance, we currently do not support full coaxial-stacking, asymmetry-penalties for multi-branch loops, or distinction of all-C loops. Also, our default dangling-end model (`-d 2`) may yield slightly reduced free energy values compared to the default settings in programs of the `RNAstructure` Package. Here, using the `-d 1` option may produce results closer to those obtained from `RNAstructure`...

**Comment by avilella** [comment]
This makes sense and it matches my observations as well. Thanks for your
detailed reply.

**Comment by AbeerMM** [comment]
> 



> We use the RNA and DNA parameter files that are distributed along with `RNAstructure`. So the above results are no surprise. The only major difference is in slight simplifications of our Nearest Neighbor model implementation. For instance, we currently do not support full coaxial-stacking, asymmetry-penalties for multi-branch loops, or distinction of all-C loops. Also, our default dangling-end model (`-d 2`) may yield slightly reduced free energy values compared to the default settings in programs of the `RNAstructure` Package. Here, using the `-d 1` option may produce results closer to those obtained from `RNAstructure`...

@RaumZeit I'm wondering if any of these are implemented in the recent releases?

`full coaxial-stacking, asymmetry-penalties for multi-branch loops, or distinction of all-C loops`

**Comment by RaumZeit** [comment]
nope, those are not implemented yet and we do not have these additions scheduled yet.
