### ISSUE TITLE
how to resolve WARNING: Newton did not converge after 10001 steps!!

### ISSUE THREAD

**Issue by avilella** [ViennaRNA/ViennaRNA#63]
Every once in a while, one of the cofold calculations I am performing with Vienna RNA gives me the warning:

WARNING: Newton did not converge after 10001 steps!!

What's the best way to deal with these when occurring? Is there a parameter that I can change to avoid this issue?

Thanks in advance

**Comment by RaumZeit** [comment]
Hi,

I'm afraid, there is currently nothing one can do against this warning. We use the iterative Newton method to compute the concentrations for nucleic acid dimers, and it appears that for some reason the Newton method doesn't converge.

If you could provide me with a set of sequences that produce this error, I can have a look at what is actually causing the numeric instability here...
