### ISSUE TITLE
How to use CUDA RNAfold in Google Colaboratory

### ISSUE THREAD

**Issue by Shunsuke-1994** [ViennaRNA/ViennaRNA#67]
Hi! 

I'm facing installing problems to use viennaRNA package in Google Colaboratory.

I tried following codes, but `import RNA` failed. Could you teach me how to use?
Initially, I installed CUDA RNAfold. 
```
!wget https://www.tbi.univie.ac.at/RNA/packages/source/ViennaRNA-2.3.0cuda.tar.gz
!tar xzvf ViennaRNA-2.3.0cuda.tar.gz
!cd ViennaRNA-2.3.0cuda
!./configure --with-swig --disable-check-python3 NVCC_PATH=/path/to/cuda/bin NVCC_SAMPLES=/path/to/cuda/samples CUDA_SMS="35 50 61"
!make 
!make install
```
Then, I tried
`import RNA`
but, the following error returned.....
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-54-8029f37864dc> in <module>()
----> 1 import RNA

ModuleNotFoundError: No module named 'RNA'
```

Thanks,
Shunsuke

**Comment by RaumZeit** [comment]
Dear Shunsuke,
unfortunately, we do not provide SWIG interfaces for the CUDA version of ViennaRNA-2.3.0. The entire CUDA implementation has been hard-coded for the RNAfold executable only. To actually use the CUDA version, you probably need to perform system calls to the corresponding RNAfold program from within Python.

Also, please note that currently we do not have any resources or personnel to change the state of the CUDA version. That's also the reason why the CUDA implementation is still at version 2.3.0 while the official mainline release already reached 2.4.14.

**Comment by Lan-h** [comment]
Hi ! 
I would like to do the same, not with the Cuda version.
I am also running into the "No module named 'RNA' error message. 
So far I tried : 
os.chdir('/content/gdrive/My_Path')
!tar xzvf ViennaRNA-2.3.2.tar.gz
!cd ViennaRNA-2.3.2
! ./ViennaRNA-2.3.2/configure --with-python3 
! make
! sudo make install
