### ISSUE TITLE
Python interface : deprecated API call?

### ISSUE THREAD

**Issue by martin-raden** [ViennaRNA/ViennaRNA#69]
Hi @RaumZeit 

is it possible that the python interface calls a deprecated function:

https://github.com/ViennaRNA/ViennaRNA/blob/0b8ca4c6604e7a8bea366af62d82f8f40cea49bf/interfaces/part_func.i#L196

shouldnt it call ` vrna_pf_dimer_concentrations()`?

furthermore: how to initialize such that the `vrna_exp_param_t *` pointer is set appropriately?

Thanks for insights,
Martin

**Comment by RaumZeit** [comment]
There are still many occurrences of deprecated API calls within our library and especially in the SWIG wrapped scripting language interfaces. However, this should not pose any problem, as we ship both and as soon as the deprecated call vanishes, the SWIG wrappers will be updated accordingly

**Comment by RaumZeit** [comment]
What do you mean by 'appropriately set the `vrna_exp_param_t *` pointer? You need an energy parameter set in Boltzmann factor form, such as obtained from `vrna_exp_params()`, if this is what you were referring to...
