### ISSUE TITLE
Predict conserved RNA-DNA interactions?

### ISSUE THREAD

**Issue by fengchuiguo1994** [ViennaRNA/ViennaRNA#71]
can I use RNAaliduplex to Predict conserved RNA-DNA interactions

**Comment by RaumZeit** [comment]
Unfortunately, it can't. The `2.1.9h` version only supports RNA/DNA interactions in `RNAcofold`, `RNAup`, and `RNAduplex`.

**Comment by fengchuiguo1994** [comment]
do you know some software can do this ? thanks

**Comment by RaumZeit** [comment]
nope, I'm not aware of any program that supports RNA-DNA interaction prediction for multiple sequence alignments...
