### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ichxxx** [ViennaRNA/ViennaRNA#75]
Hello, during a make from the last version of ViennaRNA on Ubuntu, I get the following error :
```
lto1: fatal error: bytecode stream in file '../../src/ViennaRNA/.libs/libRNA_conv.a' generated with LTO version 2.2 instead of the expected 6.0
compilation terminated.
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
Makefile:968: recipe for target 'RNALfold' failed
make[3]: *** [RNALfold] Error 1
make[3]: Leaving directory '/home/ichx/Documents/biosoft/ViennaRNA-2.4.14/src/bin'
Makefile:524: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/ichx/Documents/biosoft/ViennaRNA-2.4.14/src'
Makefile:668: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ichx/Documents/biosoft/ViennaRNA-2.4.14'
Makefile:561: recipe for target 'all' failed
make: *** [all] Error 2
```
Any hints would be greatly appreciated!

**Comment by martynakgajos** [comment]
@ichxxx have you found any solution? I am experiencing the same problem.

**Comment by joshuap2613** [comment]
@ichxxx @martynakgajos any update on whether or not you were able to resolve the issue?

**Comment by RaumZeit** [comment]
Which version of Ubuntu are you using, and more importantly, which compiler? It seems this is related to Link Time Optimization (LTO), so you might want to try adding the `--disable-lto` option to the `./configure` call to compile ViennaRNA without LTO support...

**Comment by RaumZeit** [comment]
On another note, the error you are experiencing stems from using different compilers for compiling our source code. It seems you should run a `make clean` first to get rid of the old `libRNA.a`. Alternativley, download the source tarball or clone the repository again.
