### ISSUE TITLE
viennarna in pipy

### ISSUE THREAD

**Issue by lbugnon** [ViennaRNA/ViennaRNA#79]
Please, add the repo to PyPi

**Comment by ayaanhossain** [comment]
The job's been done! Please try `pip install ViennaRNA --upgrade` on your shell. You can also specify ViennaRNA now as a dependency for your project using `install_requires` inside your `setup.py:setup`.

**Comment by GabLoyer** [comment]
It would be great if it was natively support by the ViennaRNA team tho, with versionning 🙏, instead of relying on a third party repo.
It would be great for users (like me) that don't want to integrate conda into their projects.

**Comment by RaumZeit** [comment]
https://pypi.org/project/ViennaRNA/
