### ISSUE TITLE
[Compile Bug with GCC 10.1.0] In Kinfold

### ISSUE THREAD

**Issue by rubyFeedback** [ViennaRNA/ViennaRNA#84]
The error shows up when trying to compile Kinfold:

    CCLD     Kinfold
    /usr/bin/ld: globals.o:(.bss+0x40): multiple definition of `GAV'; baum.o:(.bss+0x40): first defined here
    /usr/bin/ld: globals.o:(.bss+0x0): multiple definition of `GTV'; baum.o:(.bss+0x0): first defined here
    /usr/bin/ld: globals.o:(.bss+0x8a0): multiple definition of `GSV'; baum.o:(.bss+0x8a0): first defined here
    /usr/bin/ld: main.o:(.bss+0x40): multiple definition of `GAV'; baum.o:(.bss+0x40): first defined here
    /usr/bin/ld: main.o:(.bss+0x0): multiple definition of `GTV'; baum.o:(.bss+0x0): first defined here
    /usr/bin/ld: main.o:(.bss+0x8a0): multiple definition of `GSV'; baum.o:(.bss+0x8a0): first defined here
    /usr/bin/ld: nachbar.o:(.bss+0x40): multiple definition of `GAV'; baum.o:(.bss+0x40): first defined here
    /usr/bin/ld: nachbar.o:(.bss+0x8a0): multiple definition of `GSV'; baum.o:(.bss+0x8a0): first defined here
    /usr/bin/ld: nachbar.o:(.bss+0x0): multiple definition of `GTV'; baum.o:(.bss+0x0): first defined here
    collect2: error: ld returned 1 exit status

I tested and verified the same code with gcc 9.3.0 and it worked fine (compiled without problem
and from what I can tell viennarna works fine, with 9.3.0).

Not sure about the differences but I assume that something may have changed in GCC 10.1.0. At
any rate I just report this here, in the event that someone may want to have a look. My system is
using glibc version 2.23 and binutils version 2.34 (but I don't think this is the culprit; more gcc 10.1.0;
configure flags for the compilation of GCC 10.1.0 were --enable-languages=c,c++,objc,go,fortran
--disable-libstdcxx-pch --disable-multilib --disable-libgomp --enable-bootstrap, in the event that it
may matter).

**Comment by RaumZeit** [comment]
We are aware of that problem. The source files in the `Kinfold` subpackage need some adjustment to make the strict GCC 10 happy.

For now, you can either deactivate building of the `Kinfold` program using the `--without-kinfold` option for the `./configure` script, or you may apply this [patch](https://github.com/ViennaRNA/ViennaRNA/files/4918493/kinfold_gcc10_patch.txt). This will solve the compilation issues in `Kinfold`.

The next release of the `ViennaRNA Package` will include the required changes to comply with the strictness of GCC 10

**Comment by RaumZeit** [comment]
Fixed with version `2.4.15`
