### ISSUE TITLE
Missing source file (RNAfold_cmdl.c)

### ISSUE THREAD

**Issue by ekg** [ViennaRNA/ViennaRNA#85]
I've just attempted to build from the git repository's master HEAD, and I get this error:

    No rule to make target 'RNAfold_cmdl.c', needed by 'RNAfold_cmdl.o'.  Stop.

**Comment by RaumZeit** [comment]
This usually means that you don't have all required maintainer tools installed. In particular, it seems that you need to install `gengetopt` to generate the command line parser files.
Please verify that you have the program `gengetopt` available and re-run the `./configure` script.
This should solve your problem.
