### ISSUE TITLE
RNA2Dfold gets stuck with longer sequence

### ISSUE THREAD

**Issue by AbeerMM** [ViennaRNA/ViennaRNA#86]
Hello,

I'm trying to run RNA2Dfold, and it works fine with short sequence. However, when I try to run it with longer sequences (e.g. > 600nt), it gets stuck after printing the structures and before printing the table. 

Is there a limit with the length of the sequence for RNA2Dfold? or is there a bug in it?

I appreciate your help.

**Comment by RaumZeit** [comment]
RNA2Dfold has an asymptotic time and memory complexity of O(n^7) and O(n^4), respectively. It was tested with sequences up to about 400nt length, but should work with longer sequences as well.
For sequences of length 600, I expect it to be very slow, so computations can require a lot of memory and multiple days. Did you let it run in simpel MFE mode or partition function mode?

**Comment by AbeerMM** [comment]
@RaumZeit Thank you for your reply. That makes sense. When I run it using the simple mode, I get the results easily. It seems as you said. It needs enough resources. I wasn't patient enough to keep it running for days. 
Running it on shorter sequences works perfectly.

Thanks
