### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by orangeSi** [ViennaRNA/ViennaRNA#9]
Hi,I got this error when I installed VienaRNA-2.3.2:

In file included from ../../src/ViennaRNA/utils.h:31,
                 from popt.c:14:
../../src/ViennaRNA/string_utils.h:102: error: expected declaration specifiers or ‘...’ before ‘va_list’
../../src/ViennaRNA/string_utils.h:138: error: expected declaration specifiers or ‘...’ before ‘va_list’
In file included from popt.c:14:
../../src/ViennaRNA/utils.h:186: error: expected declaration specifiers or ‘...’ before ‘va_list’
../../src/ViennaRNA/utils.h:214: error: expected declaration specifiers or ‘...’ before ‘va_list’
../../src/ViennaRNA/utils.h:242: error: expected declaration specifiers or ‘...’ before ‘va_list’

thanks~
Si

**Comment by RaumZeit** [comment]
This error is due to a missing include of a header file and the strictness of the compiler. However, it is fixed since version 2.3.3 with commit 9766c88adfbea40a035a03c4a373dd30f3d6692e

Please either apply the above patch to the sources of version 2.3.2 or use the latest stable release, which is 2.3.4

Best,
Ronny

**Comment by orangeSi** [comment]
Hi Ronny~
I use 2.3.4，but got this error when Make ：

/usr/bin/ld: /ifshk4/BC_PUB/biosoft/PIPE_RD/Package/Python-2.7.9/lib/python2.7/config/libpython2.7.a(abstract.o): relocation R_X86_64_32 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/ifshk4/BC_PUB/biosoft/PIPE_RD/Package/Python-2.7.9/lib/python2.7/config/libpython2.7.a: could not read symbols: Bad value

thanks~

**Comment by RaumZeit** [comment]
Hi Si,
this sounds odd. since the linking process should not try to link against static `libpython2.7.a` but the shared object, something like `libpython2.7.so` instead... Can you please provide me your `config.log` file, or the entre output of the configure script?
