### ISSUE TITLE
make check fails at partition function

### ISSUE THREAD

**Issue by atanzer** [ViennaRNA/ViennaRNA#90]
hey there,

I found an issue when using floating point precision.

when compiling with --enable-floatpf, make check fails 10 times:
Testsuite summary for ViennaRNA 2.4.15

\# TOTAL: 36
\# PASS:  26
\# SKIP:  0
\# XFAIL: 0
\# FAIL:  10
\# XPASS: 0
\# ERROR: 0

the differences to standard calculations can become quite extensive, as you can see in
tests/test-suite.log

I suppose the unit tests are not aware of FPprecision?
it would be great to update the results the tests are compared to.

what is the advantage of this feature anyway?

thanks, 
andrea

**Comment by atanzer** [comment]
ok, so after a deep dive into the RNAlib manual I found what this actually is.
this option is rather a downgrade of viennarana, though the flagname suggests otherwise ;)
anyway, the unit test should still be fixed, I guess.

**Comment by RaumZeit** [comment]
This is expected, since downgrading to floating point precision in partition function computations introduces numerical errors that can't be corrected for.
The `--enable-floatpf` option is not recommended and mostly there for historical reasons.
