### ISSUE TITLE
MacOS Compiling Issues 

### ISSUE THREAD

**Issue by helenmasson** [ViennaRNA/ViennaRNA#91]
Forgive me as I am not incredibly computer savvy.

I followed installation instructions for compiling from source code (from TBI.
I was able to successfully configure using the command:
./configure --enable-macosx-installer
However when I then run 'make' it breaks and I get the following error(s):
PKG-GEN ViennaRNA Package 2.4.15 Development.pkg
pkgbuild: Inferring bundle components from contents of staging_libRNA
pkgbuild: Wrote package to ViennaRNA Package 2.4.15 Development.pkg
PREPARE staging-cluster
make[3]: *** No rule to make target `install'.  Stop.
make[2]: *** [staging-cluster] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

I also tried re-configuring with the command:
./configure --enable-universal-binary
But it ends in the following error:
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./../../install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking if malloc debugging is wanted... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/helenmasson/Downloads/ViennaRNA-2.4.15/src/Kinfold':
configure: error: C compiler cannot create executables
See `config.log' for more details
configure: error: ./configure failed for src/Kinfold

Lastly, I have tried to download the pre-compiled binary package from TBI, but it results in "Failed - Server problem."

Any suggestions on how I can go about installing the package?

**Comment by schultzm** [comment]
Hi @helenmasson,

I had similar problems.  I managed to install viennarna using `conda create -n vienna_env -c bioconda python=3.8 viennarna`.   All the packages become available after activating the environment using `conda activate vienna_env`.

**Comment by lucky5sugar** [comment]
Thank you @schultzm, I had the same problem as @helenmasson, and I overcame it with conda install!

**Comment by RaumZeit** [comment]
With recent Mac OS X versions, the use of the configure flag `--enable-universal-binary` is working incorrectly, since Apple seems to have dropped i686 support. You may try to simply configure with
```
./configure --disable-lto
```
and run `make`.
This works on our MacBook that we us to create the OS X installer executable.
