### ISSUE TITLE
installing Python bindings for different versions of Python

### ISSUE THREAD

**Issue by dave-doty** [ViennaRNA/ViennaRNA#92]
I'm having a hard time figuring out how to configure the ViennaRNA installation to target a particular Python version.

There is a `./configure` command-line switch `--with-python3`, but it is possible to have many different versions of Python on a system. ViennaRNA seems to choose one of them and install only for that version.

I have found that on Linux, after installation, if I can find the file `_RNA.cpython-37-x86_64-linux-gnu.so` (for Python 3.7) on my system, then I can copy it along with the `__init__.py` file created by SWIG into a directory such as `/usr/lib/python3.7/dist-packages/RNA/`, then the installation of Python using that directory for library files can import RNA.

But it appears that this only works if I can find the library file compiled for the appropriate version of Python, e.g., using `_RNA.cpython-36-x86_64-linux-gnu.so` in a Python 3.7 installation does not work.

And it doesn't always work: for instance, I found `ViennaRNA-2.4.15/interfaces/Python3/RNA/_RNA.cpython-37m-x86_64-linux-gnu.so` in the ViennaRNA source directory after running `make`, and I copied it to both `/usr/lib/python3.7/dist-packages/RNA/` and `/usr/local/lib/python3.7/site-packages/RNA/`, but I get this error:

```shell
$ which python3.7
/usr/bin/python3.7
$ python3.7 -c "import RNA"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/RNA/__init__.py", line 1721, in <module>
    class param(_object):
  File "/usr/lib/python3/dist-packages/RNA/__init__.py", line 1727, in param
    __swig_setmethods__["hairpin"] = _RNA.param_hairpin_set
AttributeError: module 'RNA._RNA' has no attribute 'param_hairpin_set'
```

I'm using Ubuntu 18.04 on Windows Subsystem for Linux.

**Comment by RaumZeit** [comment]
You can choose the python version to build the interface for by setting the environment variables
`PYTHON` or `PYTHON3` to point to the corresponding locatons. Note, that `PYTHON` is meant for Python2.x and `PYTHON3` for Python 3.x interpreterrs. The `./configure` script will then figure out itself how to compile, link, and where to install the respective `.so` and `__init__.py` files.

Interface files compiled for a particular ersion of Python are expected to not work with other versions. Your last issue, however, indicates that the `__init__.py` script loaded does not correspond to the `.so` binary file with the implementation. So there seems to be an issue with your Python include paths.
