### ISSUE TITLE
RNAcofold dot bracket parsing lib/tool

### ISSUE THREAD

**Issue by Nastiya** [ViennaRNA/ViennaRNA#94]
Dear All,
I received the following dot bracket output after running the RNAcofold command.
...................((((((((....((((.......))))(((.(.((((......)))).)))).((((.(((((....((((((((.......)))))))).)))))))))...(((((((........)))))))....((((.((....&....))))))))))))))............... (-47.30)
Now,I would like to get a base pairing/hybridization pairing list between seq1 and seq 2.
for example:
**Seq1- Seq2:**
G5-C40
U6-A39
U7-A38
Is there a library I can use?
Thank you.
Nastya

**Comment by RaumZeit** [comment]
There is no library function available for this particular case. However, you might want to look into the `vrna_ptable()` function, which translates a dot-bracket string into an integer array where each position `i` stores the pairing partner `j` if `i` forms a base pair `(i,j)` or 0 if it is unpaired. From that it is fairly simple to derive the list you want.
